// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: movie_service/movie_read.proto

package movie_read

import (
	movie_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/movie_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Movie Entity
// |--------------------------------------------------------------------------
type Movie struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique movie identifier
	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// Movie title
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Movie description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Movie language
	Language string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	// Movie genre
	Genres []string `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	// Movie duration in minutes
	DurationMinutes uint32 `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	// Release date timestamp
	ReleaseDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	// Poster image URL
	PosterUrl string `protobuf:"bytes,8,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	// Banner image URL
	BannerUrl string `protobuf:"bytes,9,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	// Age rating
	AgeRating string `protobuf:"bytes,10,opt,name=age_rating,json=ageRating,proto3" json:"age_rating,omitempty"`
	// Current movie status
	Status movie_service.MovieStatus `protobuf:"varint,11,opt,name=status,proto3,enum=movie_service.status.MovieStatus" json:"status,omitempty"`
	// Record creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Record update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_movie_service_movie_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_read_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Movie) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Movie) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Movie) GetDurationMinutes() uint32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *Movie) GetReleaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleaseDate
	}
	return nil
}

func (x *Movie) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *Movie) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *Movie) GetAgeRating() string {
	if x != nil {
		return x.AgeRating
	}
	return ""
}

func (x *Movie) GetStatus() movie_service.MovieStatus {
	if x != nil {
		return x.Status
	}
	return movie_service.MovieStatus(0)
}

func (x *Movie) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Movie) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// |--------------------------------------------------------------------------
// | Show Entity
// |--------------------------------------------------------------------------
type MovieShow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show identifier
	ShowId string `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	// Movie identifier
	MovieId string `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// Theatre identifier
	TheatreId string `protobuf:"bytes,3,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	// Screen identifier
	ScreenId string `protobuf:"bytes,4,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	// Show start time
	StartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Show end time
	EndTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Ticket price
	Price float64 `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	// Available seats
	AvailableSeats uint32 `protobuf:"varint,8,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MovieShow) Reset() {
	*x = MovieShow{}
	mi := &file_movie_service_movie_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieShow) ProtoMessage() {}

func (x *MovieShow) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieShow.ProtoReflect.Descriptor instead.
func (*MovieShow) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_read_proto_rawDescGZIP(), []int{1}
}

func (x *MovieShow) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *MovieShow) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *MovieShow) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

func (x *MovieShow) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *MovieShow) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *MovieShow) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *MovieShow) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MovieShow) GetAvailableSeats() uint32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

type GetMoviesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination limit
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Search keyword
	Search *string `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	// Filter by language
	Language *string `protobuf:"bytes,4,opt,name=language,proto3,oneof" json:"language,omitempty"`
	// Filter by genre
	Genre         *string `protobuf:"bytes,5,opt,name=genre,proto3,oneof" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoviesRequest) Reset() {
	*x = GetMoviesRequest{}
	mi := &file_movie_service_movie_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesRequest) ProtoMessage() {}

func (x *GetMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetMoviesRequest) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_read_proto_rawDescGZIP(), []int{2}
}

func (x *GetMoviesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMoviesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetMoviesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetMoviesRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *GetMoviesRequest) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

type GetMoviesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie list
	Movies []*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	// Total records
	Total uint64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// Pagination limit
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset
	Offset        uint32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoviesResponse) Reset() {
	*x = GetMoviesResponse{}
	mi := &file_movie_service_movie_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesResponse) ProtoMessage() {}

func (x *GetMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetMoviesResponse) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_read_proto_rawDescGZIP(), []int{3}
}

func (x *GetMoviesResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *GetMoviesResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetMoviesResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMoviesResponse) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetMovieByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie identifier
	MovieId       string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieByIdRequest) Reset() {
	*x = GetMovieByIdRequest{}
	mi := &file_movie_service_movie_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIdRequest) ProtoMessage() {}

func (x *GetMovieByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIdRequest.ProtoReflect.Descriptor instead.
func (*GetMovieByIdRequest) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_read_proto_rawDescGZIP(), []int{4}
}

func (x *GetMovieByIdRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetMovieByIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie entity
	Movie         *Movie `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieByIdResponse) Reset() {
	*x = GetMovieByIdResponse{}
	mi := &file_movie_service_movie_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIdResponse) ProtoMessage() {}

func (x *GetMovieByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIdResponse.ProtoReflect.Descriptor instead.
func (*GetMovieByIdResponse) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_read_proto_rawDescGZIP(), []int{5}
}

func (x *GetMovieByIdResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type GetMovieShowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie identifier
	MovieId       string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieShowsRequest) Reset() {
	*x = GetMovieShowsRequest{}
	mi := &file_movie_service_movie_read_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieShowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieShowsRequest) ProtoMessage() {}

func (x *GetMovieShowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_read_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieShowsRequest.ProtoReflect.Descriptor instead.
func (*GetMovieShowsRequest) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_read_proto_rawDescGZIP(), []int{6}
}

func (x *GetMovieShowsRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetMovieShowsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie shows
	Shows         []*MovieShow `protobuf:"bytes,1,rep,name=shows,proto3" json:"shows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieShowsResponse) Reset() {
	*x = GetMovieShowsResponse{}
	mi := &file_movie_service_movie_read_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieShowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieShowsResponse) ProtoMessage() {}

func (x *GetMovieShowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_read_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieShowsResponse.ProtoReflect.Descriptor instead.
func (*GetMovieShowsResponse) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_read_proto_rawDescGZIP(), []int{7}
}

func (x *GetMovieShowsResponse) GetShows() []*MovieShow {
	if x != nil {
		return x.Shows
	}
	return nil
}

var File_movie_service_movie_read_proto protoreflect.FileDescriptor

const file_movie_service_movie_read_proto_rawDesc = "" +
	"\n" +
	"\x1emovie_service/movie_read.proto\x12\x12movie_service.read\x1a\x1fgoogle/protobuf/timestamp.proto\x1a movie_service/movie_status.proto\"\x86\x04\n" +
	"\x05Movie\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\rR\x0fdurationMinutes\x12=\n" +
	"\frelease_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vreleaseDate\x12\x1d\n" +
	"\n" +
	"poster_url\x18\b \x01(\tR\tposterUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\t \x01(\tR\tbannerUrl\x12\x1d\n" +
	"\n" +
	"age_rating\x18\n" +
	" \x01(\tR\tageRating\x129\n" +
	"\x06status\x18\v \x01(\x0e2!.movie_service.status.MovieStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xac\x02\n" +
	"\tMovieShow\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x03 \x01(\tR\ttheatreId\x12\x1b\n" +
	"\tscreen_id\x18\x04 \x01(\tR\bscreenId\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12'\n" +
	"\x0favailable_seats\x18\b \x01(\rR\x0eavailableSeats\"\xbb\x01\n" +
	"\x10GetMoviesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x1b\n" +
	"\x06search\x18\x03 \x01(\tH\x00R\x06search\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x04 \x01(\tH\x01R\blanguage\x88\x01\x01\x12\x19\n" +
	"\x05genre\x18\x05 \x01(\tH\x02R\x05genre\x88\x01\x01B\t\n" +
	"\a_searchB\v\n" +
	"\t_languageB\b\n" +
	"\x06_genre\"\x8a\x01\n" +
	"\x11GetMoviesResponse\x121\n" +
	"\x06movies\x18\x01 \x03(\v2\x19.movie_service.read.MovieR\x06movies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"0\n" +
	"\x13GetMovieByIdRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"G\n" +
	"\x14GetMovieByIdResponse\x12/\n" +
	"\x05movie\x18\x01 \x01(\v2\x19.movie_service.read.MovieR\x05movie\"1\n" +
	"\x14GetMovieShowsRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"L\n" +
	"\x15GetMovieShowsResponse\x123\n" +
	"\x05shows\x18\x01 \x03(\v2\x1d.movie_service.read.MovieShowR\x05shows2\xb5\x02\n" +
	"\x10MovieReadService\x12X\n" +
	"\tGetMovies\x12$.movie_service.read.GetMoviesRequest\x1a%.movie_service.read.GetMoviesResponse\x12a\n" +
	"\fGetMovieById\x12'.movie_service.read.GetMovieByIdRequest\x1a(.movie_service.read.GetMovieByIdResponse\x12d\n" +
	"\rGetMovieShows\x12(.movie_service.read.GetMovieShowsRequest\x1a).movie_service.read.GetMovieShowsResponseBbZ`github.com/movie-reservation-system-ms/movie_reservation_proto_lib/movie_service/read;movie_readb\x06proto3"

var (
	file_movie_service_movie_read_proto_rawDescOnce sync.Once
	file_movie_service_movie_read_proto_rawDescData []byte
)

func file_movie_service_movie_read_proto_rawDescGZIP() []byte {
	file_movie_service_movie_read_proto_rawDescOnce.Do(func() {
		file_movie_service_movie_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_service_movie_read_proto_rawDesc), len(file_movie_service_movie_read_proto_rawDesc)))
	})
	return file_movie_service_movie_read_proto_rawDescData
}

var file_movie_service_movie_read_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_movie_service_movie_read_proto_goTypes = []any{
	(*Movie)(nil),                  // 0: movie_service.read.Movie
	(*MovieShow)(nil),              // 1: movie_service.read.MovieShow
	(*GetMoviesRequest)(nil),       // 2: movie_service.read.GetMoviesRequest
	(*GetMoviesResponse)(nil),      // 3: movie_service.read.GetMoviesResponse
	(*GetMovieByIdRequest)(nil),    // 4: movie_service.read.GetMovieByIdRequest
	(*GetMovieByIdResponse)(nil),   // 5: movie_service.read.GetMovieByIdResponse
	(*GetMovieShowsRequest)(nil),   // 6: movie_service.read.GetMovieShowsRequest
	(*GetMovieShowsResponse)(nil),  // 7: movie_service.read.GetMovieShowsResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(movie_service.MovieStatus)(0), // 9: movie_service.status.MovieStatus
}
var file_movie_service_movie_read_proto_depIdxs = []int32{
	8,  // 0: movie_service.read.Movie.release_date:type_name -> google.protobuf.Timestamp
	9,  // 1: movie_service.read.Movie.status:type_name -> movie_service.status.MovieStatus
	8,  // 2: movie_service.read.Movie.created_at:type_name -> google.protobuf.Timestamp
	8,  // 3: movie_service.read.Movie.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 4: movie_service.read.MovieShow.start_time:type_name -> google.protobuf.Timestamp
	8,  // 5: movie_service.read.MovieShow.end_time:type_name -> google.protobuf.Timestamp
	0,  // 6: movie_service.read.GetMoviesResponse.movies:type_name -> movie_service.read.Movie
	0,  // 7: movie_service.read.GetMovieByIdResponse.movie:type_name -> movie_service.read.Movie
	1,  // 8: movie_service.read.GetMovieShowsResponse.shows:type_name -> movie_service.read.MovieShow
	2,  // 9: movie_service.read.MovieReadService.GetMovies:input_type -> movie_service.read.GetMoviesRequest
	4,  // 10: movie_service.read.MovieReadService.GetMovieById:input_type -> movie_service.read.GetMovieByIdRequest
	6,  // 11: movie_service.read.MovieReadService.GetMovieShows:input_type -> movie_service.read.GetMovieShowsRequest
	3,  // 12: movie_service.read.MovieReadService.GetMovies:output_type -> movie_service.read.GetMoviesResponse
	5,  // 13: movie_service.read.MovieReadService.GetMovieById:output_type -> movie_service.read.GetMovieByIdResponse
	7,  // 14: movie_service.read.MovieReadService.GetMovieShows:output_type -> movie_service.read.GetMovieShowsResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_movie_service_movie_read_proto_init() }
func file_movie_service_movie_read_proto_init() {
	if File_movie_service_movie_read_proto != nil {
		return
	}
	file_movie_service_movie_read_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_service_movie_read_proto_rawDesc), len(file_movie_service_movie_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_service_movie_read_proto_goTypes,
		DependencyIndexes: file_movie_service_movie_read_proto_depIdxs,
		MessageInfos:      file_movie_service_movie_read_proto_msgTypes,
	}.Build()
	File_movie_service_movie_read_proto = out.File
	file_movie_service_movie_read_proto_goTypes = nil
	file_movie_service_movie_read_proto_depIdxs = nil
}
