// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: movie_service/movie_status.proto

package movie_status

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Movie Status
// |--------------------------------------------------------------------------
type MovieStatus int32

const (
	MovieStatus_MOVIE_STATUS_UNSPECIFIED MovieStatus = 0
	MovieStatus_MOVIE_STATUS_UPCOMING    MovieStatus = 1
	MovieStatus_MOVIE_STATUS_RUNNING     MovieStatus = 2
	MovieStatus_MOVIE_STATUS_ENDED       MovieStatus = 3
)

// Enum value maps for MovieStatus.
var (
	MovieStatus_name = map[int32]string{
		0: "MOVIE_STATUS_UNSPECIFIED",
		1: "MOVIE_STATUS_UPCOMING",
		2: "MOVIE_STATUS_RUNNING",
		3: "MOVIE_STATUS_ENDED",
	}
	MovieStatus_value = map[string]int32{
		"MOVIE_STATUS_UNSPECIFIED": 0,
		"MOVIE_STATUS_UPCOMING":    1,
		"MOVIE_STATUS_RUNNING":     2,
		"MOVIE_STATUS_ENDED":       3,
	}
)

func (x MovieStatus) Enum() *MovieStatus {
	p := new(MovieStatus)
	*p = x
	return p
}

func (x MovieStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovieStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_movie_service_movie_status_proto_enumTypes[0].Descriptor()
}

func (MovieStatus) Type() protoreflect.EnumType {
	return &file_movie_service_movie_status_proto_enumTypes[0]
}

func (x MovieStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovieStatus.Descriptor instead.
func (MovieStatus) EnumDescriptor() ([]byte, []int) {
	return file_movie_service_movie_status_proto_rawDescGZIP(), []int{0}
}

var File_movie_service_movie_status_proto protoreflect.FileDescriptor

const file_movie_service_movie_status_proto_rawDesc = "" +
	"\n" +
	" movie_service/movie_status.proto\x12\x14movie_service.status*x\n" +
	"\vMovieStatus\x12\x1c\n" +
	"\x18MOVIE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MOVIE_STATUS_UPCOMING\x10\x01\x12\x18\n" +
	"\x14MOVIE_STATUS_RUNNING\x10\x02\x12\x16\n" +
	"\x12MOVIE_STATUS_ENDED\x10\x03B`Z^github.com/movie-reservation-system-ms/movie_reservation_proto_lib/movie_service/;movie_statusb\x06proto3"

var (
	file_movie_service_movie_status_proto_rawDescOnce sync.Once
	file_movie_service_movie_status_proto_rawDescData []byte
)

func file_movie_service_movie_status_proto_rawDescGZIP() []byte {
	file_movie_service_movie_status_proto_rawDescOnce.Do(func() {
		file_movie_service_movie_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_service_movie_status_proto_rawDesc), len(file_movie_service_movie_status_proto_rawDesc)))
	})
	return file_movie_service_movie_status_proto_rawDescData
}

var file_movie_service_movie_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_movie_service_movie_status_proto_goTypes = []any{
	(MovieStatus)(0), // 0: movie_service.status.MovieStatus
}
var file_movie_service_movie_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_movie_service_movie_status_proto_init() }
func file_movie_service_movie_status_proto_init() {
	if File_movie_service_movie_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_service_movie_status_proto_rawDesc), len(file_movie_service_movie_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_movie_service_movie_status_proto_goTypes,
		DependencyIndexes: file_movie_service_movie_status_proto_depIdxs,
		EnumInfos:         file_movie_service_movie_status_proto_enumTypes,
	}.Build()
	File_movie_service_movie_status_proto = out.File
	file_movie_service_movie_status_proto_goTypes = nil
	file_movie_service_movie_status_proto_depIdxs = nil
}
