// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: movie_service/movie_write.proto

package movie_write

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MovieWriteService_CreateMovie_FullMethodName = "/movie_service.write.MovieWriteService/CreateMovie"
	MovieWriteService_UpdateMovie_FullMethodName = "/movie_service.write.MovieWriteService/UpdateMovie"
	MovieWriteService_DeleteMovie_FullMethodName = "/movie_service.write.MovieWriteService/DeleteMovie"
)

// MovieWriteServiceClient is the client API for MovieWriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieWriteServiceClient interface {
	// |--------------------------------------------------------------------------
	// | Create Movie
	// |--------------------------------------------------------------------------
	// |
	// | Creates new movie record.
	// |
	// | REST:
	// | POST /movies
	// |
	CreateMovie(ctx context.Context, in *CreateMovieRequest, opts ...grpc.CallOption) (*CreateMovieResponse, error)
	// |--------------------------------------------------------------------------
	// | Update Movie
	// |--------------------------------------------------------------------------
	// |
	// | Updates existing movie details.
	// |
	// | REST:
	// | PUT /movies/{id}
	// |
	UpdateMovie(ctx context.Context, in *UpdateMovieRequest, opts ...grpc.CallOption) (*UpdateMovieResponse, error)
	// |--------------------------------------------------------------------------
	// | Delete Movie
	// |--------------------------------------------------------------------------
	// |
	// | Deletes movie record.
	// |
	// | REST:
	// | DELETE /movies/{id}
	// |
	DeleteMovie(ctx context.Context, in *DeleteMovieRequest, opts ...grpc.CallOption) (*DeleteMovieResponse, error)
}

type movieWriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieWriteServiceClient(cc grpc.ClientConnInterface) MovieWriteServiceClient {
	return &movieWriteServiceClient{cc}
}

func (c *movieWriteServiceClient) CreateMovie(ctx context.Context, in *CreateMovieRequest, opts ...grpc.CallOption) (*CreateMovieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMovieResponse)
	err := c.cc.Invoke(ctx, MovieWriteService_CreateMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieWriteServiceClient) UpdateMovie(ctx context.Context, in *UpdateMovieRequest, opts ...grpc.CallOption) (*UpdateMovieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMovieResponse)
	err := c.cc.Invoke(ctx, MovieWriteService_UpdateMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieWriteServiceClient) DeleteMovie(ctx context.Context, in *DeleteMovieRequest, opts ...grpc.CallOption) (*DeleteMovieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMovieResponse)
	err := c.cc.Invoke(ctx, MovieWriteService_DeleteMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieWriteServiceServer is the server API for MovieWriteService service.
// All implementations must embed UnimplementedMovieWriteServiceServer
// for forward compatibility.
type MovieWriteServiceServer interface {
	// |--------------------------------------------------------------------------
	// | Create Movie
	// |--------------------------------------------------------------------------
	// |
	// | Creates new movie record.
	// |
	// | REST:
	// | POST /movies
	// |
	CreateMovie(context.Context, *CreateMovieRequest) (*CreateMovieResponse, error)
	// |--------------------------------------------------------------------------
	// | Update Movie
	// |--------------------------------------------------------------------------
	// |
	// | Updates existing movie details.
	// |
	// | REST:
	// | PUT /movies/{id}
	// |
	UpdateMovie(context.Context, *UpdateMovieRequest) (*UpdateMovieResponse, error)
	// |--------------------------------------------------------------------------
	// | Delete Movie
	// |--------------------------------------------------------------------------
	// |
	// | Deletes movie record.
	// |
	// | REST:
	// | DELETE /movies/{id}
	// |
	DeleteMovie(context.Context, *DeleteMovieRequest) (*DeleteMovieResponse, error)
	mustEmbedUnimplementedMovieWriteServiceServer()
}

// UnimplementedMovieWriteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovieWriteServiceServer struct{}

func (UnimplementedMovieWriteServiceServer) CreateMovie(context.Context, *CreateMovieRequest) (*CreateMovieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMovie not implemented")
}
func (UnimplementedMovieWriteServiceServer) UpdateMovie(context.Context, *UpdateMovieRequest) (*UpdateMovieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMovie not implemented")
}
func (UnimplementedMovieWriteServiceServer) DeleteMovie(context.Context, *DeleteMovieRequest) (*DeleteMovieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMovie not implemented")
}
func (UnimplementedMovieWriteServiceServer) mustEmbedUnimplementedMovieWriteServiceServer() {}
func (UnimplementedMovieWriteServiceServer) testEmbeddedByValue()                           {}

// UnsafeMovieWriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieWriteServiceServer will
// result in compilation errors.
type UnsafeMovieWriteServiceServer interface {
	mustEmbedUnimplementedMovieWriteServiceServer()
}

func RegisterMovieWriteServiceServer(s grpc.ServiceRegistrar, srv MovieWriteServiceServer) {
	// If the following call panics, it indicates UnimplementedMovieWriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovieWriteService_ServiceDesc, srv)
}

func _MovieWriteService_CreateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieWriteServiceServer).CreateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieWriteService_CreateMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieWriteServiceServer).CreateMovie(ctx, req.(*CreateMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieWriteService_UpdateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieWriteServiceServer).UpdateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieWriteService_UpdateMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieWriteServiceServer).UpdateMovie(ctx, req.(*UpdateMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieWriteService_DeleteMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieWriteServiceServer).DeleteMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieWriteService_DeleteMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieWriteServiceServer).DeleteMovie(ctx, req.(*DeleteMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieWriteService_ServiceDesc is the grpc.ServiceDesc for MovieWriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieWriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movie_service.write.MovieWriteService",
	HandlerType: (*MovieWriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMovie",
			Handler:    _MovieWriteService_CreateMovie_Handler,
		},
		{
			MethodName: "UpdateMovie",
			Handler:    _MovieWriteService_UpdateMovie_Handler,
		},
		{
			MethodName: "DeleteMovie",
			Handler:    _MovieWriteService_DeleteMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie_service/movie_write.proto",
}
