// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: movie_service/movie_write.proto

package movie_write

import (
	movie_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/movie_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMovieRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie title
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Movie description
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Movie language
	Language string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	// Movie genres
	Genres []string `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	// Movie duration in minutes
	DurationMinutes uint32 `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	// Release date
	ReleaseDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	// Poster image URL
	PosterUrl string `protobuf:"bytes,7,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	// Banner image URL
	BannerUrl string `protobuf:"bytes,8,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	// Age rating
	AgeRating string `protobuf:"bytes,9,opt,name=age_rating,json=ageRating,proto3" json:"age_rating,omitempty"`
	// Initial movie status
	Status        movie_service.MovieStatus `protobuf:"varint,10,opt,name=status,proto3,enum=movie_service.status.MovieStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieRequest) Reset() {
	*x = CreateMovieRequest{}
	mi := &file_movie_service_movie_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieRequest) ProtoMessage() {}

func (x *CreateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieRequest.ProtoReflect.Descriptor instead.
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_write_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMovieRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMovieRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateMovieRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *CreateMovieRequest) GetDurationMinutes() uint32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *CreateMovieRequest) GetReleaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleaseDate
	}
	return nil
}

func (x *CreateMovieRequest) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *CreateMovieRequest) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *CreateMovieRequest) GetAgeRating() string {
	if x != nil {
		return x.AgeRating
	}
	return ""
}

func (x *CreateMovieRequest) GetStatus() movie_service.MovieStatus {
	if x != nil {
		return x.Status
	}
	return movie_service.MovieStatus(0)
}

type CreateMovieResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created movie identifier
	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// Record creation timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieResponse) Reset() {
	*x = CreateMovieResponse{}
	mi := &file_movie_service_movie_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieResponse) ProtoMessage() {}

func (x *CreateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieResponse.ProtoReflect.Descriptor instead.
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_write_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMovieResponse) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *CreateMovieResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateMovieRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie identifier
	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// Movie title
	Title *string `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// Movie description
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Movie language
	Language *string `protobuf:"bytes,4,opt,name=language,proto3,oneof" json:"language,omitempty"`
	// Movie genres
	Genres []string `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	// Movie duration in minutes
	DurationMinutes *uint32 `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3,oneof" json:"duration_minutes,omitempty"`
	// Release date
	ReleaseDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=release_date,json=releaseDate,proto3,oneof" json:"release_date,omitempty"`
	// Poster image URL
	PosterUrl *string `protobuf:"bytes,8,opt,name=poster_url,json=posterUrl,proto3,oneof" json:"poster_url,omitempty"`
	// Banner image URL
	BannerUrl *string `protobuf:"bytes,9,opt,name=banner_url,json=bannerUrl,proto3,oneof" json:"banner_url,omitempty"`
	// Age rating
	AgeRating *string `protobuf:"bytes,10,opt,name=age_rating,json=ageRating,proto3,oneof" json:"age_rating,omitempty"`
	// Movie status
	Status        *movie_service.MovieStatus `protobuf:"varint,11,opt,name=status,proto3,enum=movie_service.status.MovieStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieRequest) Reset() {
	*x = UpdateMovieRequest{}
	mi := &file_movie_service_movie_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieRequest) ProtoMessage() {}

func (x *UpdateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieRequest.ProtoReflect.Descriptor instead.
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_write_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *UpdateMovieRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateMovieRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateMovieRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *UpdateMovieRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *UpdateMovieRequest) GetDurationMinutes() uint32 {
	if x != nil && x.DurationMinutes != nil {
		return *x.DurationMinutes
	}
	return 0
}

func (x *UpdateMovieRequest) GetReleaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleaseDate
	}
	return nil
}

func (x *UpdateMovieRequest) GetPosterUrl() string {
	if x != nil && x.PosterUrl != nil {
		return *x.PosterUrl
	}
	return ""
}

func (x *UpdateMovieRequest) GetBannerUrl() string {
	if x != nil && x.BannerUrl != nil {
		return *x.BannerUrl
	}
	return ""
}

func (x *UpdateMovieRequest) GetAgeRating() string {
	if x != nil && x.AgeRating != nil {
		return *x.AgeRating
	}
	return ""
}

func (x *UpdateMovieRequest) GetStatus() movie_service.MovieStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return movie_service.MovieStatus(0)
}

type UpdateMovieResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated movie identifier
	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// Record update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieResponse) Reset() {
	*x = UpdateMovieResponse{}
	mi := &file_movie_service_movie_write_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieResponse) ProtoMessage() {}

func (x *UpdateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_write_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieResponse.ProtoReflect.Descriptor instead.
func (*UpdateMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_write_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMovieResponse) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *UpdateMovieResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteMovieRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie identifier
	MovieId       string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieRequest) Reset() {
	*x = DeleteMovieRequest{}
	mi := &file_movie_service_movie_write_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRequest) ProtoMessage() {}

func (x *DeleteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_write_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRequest.ProtoReflect.Descriptor instead.
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_write_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type DeleteMovieResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Deletion timestamp
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieResponse) Reset() {
	*x = DeleteMovieResponse{}
	mi := &file_movie_service_movie_write_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieResponse) ProtoMessage() {}

func (x *DeleteMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_movie_write_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieResponse.ProtoReflect.Descriptor instead.
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_service_movie_write_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMovieResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteMovieResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_movie_service_movie_write_proto protoreflect.FileDescriptor

const file_movie_service_movie_write_proto_rawDesc = "" +
	"\n" +
	"\x1fmovie_service/movie_write.proto\x12\x13movie_service.write\x1a\x1fgoogle/protobuf/timestamp.proto\x1a movie_service/movie_status.proto\"\x82\x03\n" +
	"\x12CreateMovieRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06genres\x18\x04 \x03(\tR\x06genres\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\rR\x0fdurationMinutes\x12=\n" +
	"\frelease_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vreleaseDate\x12\x1d\n" +
	"\n" +
	"poster_url\x18\a \x01(\tR\tposterUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\b \x01(\tR\tbannerUrl\x12\x1d\n" +
	"\n" +
	"age_rating\x18\t \x01(\tR\tageRating\x129\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2!.movie_service.status.MovieStatusR\x06status\"k\n" +
	"\x13CreateMovieResponse\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xcf\x04\n" +
	"\x12UpdateMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x04 \x01(\tH\x02R\blanguage\x88\x01\x01\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\x12.\n" +
	"\x10duration_minutes\x18\x06 \x01(\rH\x03R\x0fdurationMinutes\x88\x01\x01\x12B\n" +
	"\frelease_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\vreleaseDate\x88\x01\x01\x12\"\n" +
	"\n" +
	"poster_url\x18\b \x01(\tH\x05R\tposterUrl\x88\x01\x01\x12\"\n" +
	"\n" +
	"banner_url\x18\t \x01(\tH\x06R\tbannerUrl\x88\x01\x01\x12\"\n" +
	"\n" +
	"age_rating\x18\n" +
	" \x01(\tH\aR\tageRating\x88\x01\x01\x12>\n" +
	"\x06status\x18\v \x01(\x0e2!.movie_service.status.MovieStatusH\bR\x06status\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_languageB\x13\n" +
	"\x11_duration_minutesB\x0f\n" +
	"\r_release_dateB\r\n" +
	"\v_poster_urlB\r\n" +
	"\v_banner_urlB\r\n" +
	"\v_age_ratingB\t\n" +
	"\a_status\"k\n" +
	"\x13UpdateMovieResponse\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"/\n" +
	"\x12DeleteMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"j\n" +
	"\x13DeleteMovieResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt2\xb9\x02\n" +
	"\x11MovieWriteService\x12`\n" +
	"\vCreateMovie\x12'.movie_service.write.CreateMovieRequest\x1a(.movie_service.write.CreateMovieResponse\x12`\n" +
	"\vUpdateMovie\x12'.movie_service.write.UpdateMovieRequest\x1a(.movie_service.write.UpdateMovieResponse\x12`\n" +
	"\vDeleteMovie\x12'.movie_service.write.DeleteMovieRequest\x1a(.movie_service.write.DeleteMovieResponseBdZbgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/movie_service/write;movie_writeb\x06proto3"

var (
	file_movie_service_movie_write_proto_rawDescOnce sync.Once
	file_movie_service_movie_write_proto_rawDescData []byte
)

func file_movie_service_movie_write_proto_rawDescGZIP() []byte {
	file_movie_service_movie_write_proto_rawDescOnce.Do(func() {
		file_movie_service_movie_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_service_movie_write_proto_rawDesc), len(file_movie_service_movie_write_proto_rawDesc)))
	})
	return file_movie_service_movie_write_proto_rawDescData
}

var file_movie_service_movie_write_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_movie_service_movie_write_proto_goTypes = []any{
	(*CreateMovieRequest)(nil),     // 0: movie_service.write.CreateMovieRequest
	(*CreateMovieResponse)(nil),    // 1: movie_service.write.CreateMovieResponse
	(*UpdateMovieRequest)(nil),     // 2: movie_service.write.UpdateMovieRequest
	(*UpdateMovieResponse)(nil),    // 3: movie_service.write.UpdateMovieResponse
	(*DeleteMovieRequest)(nil),     // 4: movie_service.write.DeleteMovieRequest
	(*DeleteMovieResponse)(nil),    // 5: movie_service.write.DeleteMovieResponse
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(movie_service.MovieStatus)(0), // 7: movie_service.status.MovieStatus
}
var file_movie_service_movie_write_proto_depIdxs = []int32{
	6,  // 0: movie_service.write.CreateMovieRequest.release_date:type_name -> google.protobuf.Timestamp
	7,  // 1: movie_service.write.CreateMovieRequest.status:type_name -> movie_service.status.MovieStatus
	6,  // 2: movie_service.write.CreateMovieResponse.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: movie_service.write.UpdateMovieRequest.release_date:type_name -> google.protobuf.Timestamp
	7,  // 4: movie_service.write.UpdateMovieRequest.status:type_name -> movie_service.status.MovieStatus
	6,  // 5: movie_service.write.UpdateMovieResponse.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 6: movie_service.write.DeleteMovieResponse.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 7: movie_service.write.MovieWriteService.CreateMovie:input_type -> movie_service.write.CreateMovieRequest
	2,  // 8: movie_service.write.MovieWriteService.UpdateMovie:input_type -> movie_service.write.UpdateMovieRequest
	4,  // 9: movie_service.write.MovieWriteService.DeleteMovie:input_type -> movie_service.write.DeleteMovieRequest
	1,  // 10: movie_service.write.MovieWriteService.CreateMovie:output_type -> movie_service.write.CreateMovieResponse
	3,  // 11: movie_service.write.MovieWriteService.UpdateMovie:output_type -> movie_service.write.UpdateMovieResponse
	5,  // 12: movie_service.write.MovieWriteService.DeleteMovie:output_type -> movie_service.write.DeleteMovieResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_movie_service_movie_write_proto_init() }
func file_movie_service_movie_write_proto_init() {
	if File_movie_service_movie_write_proto != nil {
		return
	}
	file_movie_service_movie_write_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_service_movie_write_proto_rawDesc), len(file_movie_service_movie_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_service_movie_write_proto_goTypes,
		DependencyIndexes: file_movie_service_movie_write_proto_depIdxs,
		MessageInfos:      file_movie_service_movie_write_proto_msgTypes,
	}.Build()
	File_movie_service_movie_write_proto = out.File
	file_movie_service_movie_write_proto_goTypes = nil
	file_movie_service_movie_write_proto_depIdxs = nil
}
