// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: seat_service/seat_write.proto

package seat_write

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeatWriteService_CreateSeat_FullMethodName = "/seat_service.write.SeatWriteService/CreateSeat"
	SeatWriteService_UpdateSeat_FullMethodName = "/seat_service.write.SeatWriteService/UpdateSeat"
	SeatWriteService_DeleteSeat_FullMethodName = "/seat_service.write.SeatWriteService/DeleteSeat"
)

// SeatWriteServiceClient is the client API for SeatWriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeatWriteServiceClient interface {
	// |--------------------------------------------------------------------------
	// | Create Seat
	// |--------------------------------------------------------------------------
	// |
	// | Create new seat for screen.
	// |
	// | REST:
	// | POST /screens/{id}/seats
	// |
	CreateSeat(ctx context.Context, in *CreateSeatRequest, opts ...grpc.CallOption) (*CreateSeatResponse, error)
	// |--------------------------------------------------------------------------
	// | Update Seat
	// |--------------------------------------------------------------------------
	// |
	// | Update seat details.
	// |
	// | REST:
	// | PUT /seats/{id}
	// |
	UpdateSeat(ctx context.Context, in *UpdateSeatRequest, opts ...grpc.CallOption) (*UpdateSeatResponse, error)
	// |--------------------------------------------------------------------------
	// | Delete Seat
	// |--------------------------------------------------------------------------
	// |
	// | Delete seat.
	// |
	// | REST:
	// | DELETE /seats/{id}
	// |
	DeleteSeat(ctx context.Context, in *DeleteSeatRequest, opts ...grpc.CallOption) (*DeleteSeatResponse, error)
}

type seatWriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeatWriteServiceClient(cc grpc.ClientConnInterface) SeatWriteServiceClient {
	return &seatWriteServiceClient{cc}
}

func (c *seatWriteServiceClient) CreateSeat(ctx context.Context, in *CreateSeatRequest, opts ...grpc.CallOption) (*CreateSeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSeatResponse)
	err := c.cc.Invoke(ctx, SeatWriteService_CreateSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatWriteServiceClient) UpdateSeat(ctx context.Context, in *UpdateSeatRequest, opts ...grpc.CallOption) (*UpdateSeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSeatResponse)
	err := c.cc.Invoke(ctx, SeatWriteService_UpdateSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatWriteServiceClient) DeleteSeat(ctx context.Context, in *DeleteSeatRequest, opts ...grpc.CallOption) (*DeleteSeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSeatResponse)
	err := c.cc.Invoke(ctx, SeatWriteService_DeleteSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeatWriteServiceServer is the server API for SeatWriteService service.
// All implementations must embed UnimplementedSeatWriteServiceServer
// for forward compatibility.
type SeatWriteServiceServer interface {
	// |--------------------------------------------------------------------------
	// | Create Seat
	// |--------------------------------------------------------------------------
	// |
	// | Create new seat for screen.
	// |
	// | REST:
	// | POST /screens/{id}/seats
	// |
	CreateSeat(context.Context, *CreateSeatRequest) (*CreateSeatResponse, error)
	// |--------------------------------------------------------------------------
	// | Update Seat
	// |--------------------------------------------------------------------------
	// |
	// | Update seat details.
	// |
	// | REST:
	// | PUT /seats/{id}
	// |
	UpdateSeat(context.Context, *UpdateSeatRequest) (*UpdateSeatResponse, error)
	// |--------------------------------------------------------------------------
	// | Delete Seat
	// |--------------------------------------------------------------------------
	// |
	// | Delete seat.
	// |
	// | REST:
	// | DELETE /seats/{id}
	// |
	DeleteSeat(context.Context, *DeleteSeatRequest) (*DeleteSeatResponse, error)
	mustEmbedUnimplementedSeatWriteServiceServer()
}

// UnimplementedSeatWriteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeatWriteServiceServer struct{}

func (UnimplementedSeatWriteServiceServer) CreateSeat(context.Context, *CreateSeatRequest) (*CreateSeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSeat not implemented")
}
func (UnimplementedSeatWriteServiceServer) UpdateSeat(context.Context, *UpdateSeatRequest) (*UpdateSeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSeat not implemented")
}
func (UnimplementedSeatWriteServiceServer) DeleteSeat(context.Context, *DeleteSeatRequest) (*DeleteSeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSeat not implemented")
}
func (UnimplementedSeatWriteServiceServer) mustEmbedUnimplementedSeatWriteServiceServer() {}
func (UnimplementedSeatWriteServiceServer) testEmbeddedByValue()                          {}

// UnsafeSeatWriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeatWriteServiceServer will
// result in compilation errors.
type UnsafeSeatWriteServiceServer interface {
	mustEmbedUnimplementedSeatWriteServiceServer()
}

func RegisterSeatWriteServiceServer(s grpc.ServiceRegistrar, srv SeatWriteServiceServer) {
	// If the following call panics, it indicates UnimplementedSeatWriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeatWriteService_ServiceDesc, srv)
}

func _SeatWriteService_CreateSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatWriteServiceServer).CreateSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatWriteService_CreateSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatWriteServiceServer).CreateSeat(ctx, req.(*CreateSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatWriteService_UpdateSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatWriteServiceServer).UpdateSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatWriteService_UpdateSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatWriteServiceServer).UpdateSeat(ctx, req.(*UpdateSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatWriteService_DeleteSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatWriteServiceServer).DeleteSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatWriteService_DeleteSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatWriteServiceServer).DeleteSeat(ctx, req.(*DeleteSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeatWriteService_ServiceDesc is the grpc.ServiceDesc for SeatWriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeatWriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seat_service.write.SeatWriteService",
	HandlerType: (*SeatWriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSeat",
			Handler:    _SeatWriteService_CreateSeat_Handler,
		},
		{
			MethodName: "UpdateSeat",
			Handler:    _SeatWriteService_UpdateSeat_Handler,
		},
		{
			MethodName: "DeleteSeat",
			Handler:    _SeatWriteService_DeleteSeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seat_service/seat_write.proto",
}
