// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: seat_service/seat_read.proto

package seat_read

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeatReadService_GetScreenSeats_FullMethodName    = "/seat_service.read.SeatReadService/GetScreenSeats"
	SeatReadService_GetAvailableSeats_FullMethodName = "/seat_service.read.SeatReadService/GetAvailableSeats"
	SeatReadService_GetBookedSeats_FullMethodName    = "/seat_service.read.SeatReadService/GetBookedSeats"
)

// SeatReadServiceClient is the client API for SeatReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeatReadServiceClient interface {
	// |--------------------------------------------------------------------------
	// | Get Screen Seats
	// |--------------------------------------------------------------------------
	// |
	// | Fetch all seats for screen.
	// |
	// | REST:
	// | GET /screens/{id}/seats
	// |
	GetScreenSeats(ctx context.Context, in *GetScreenSeatsRequest, opts ...grpc.CallOption) (*GetScreenSeatsResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Available Seats
	// |--------------------------------------------------------------------------
	// |
	// | Fetch available seats for show.
	// |
	// | REST:
	// | GET /shows/{id}/available-seats
	// |
	GetAvailableSeats(ctx context.Context, in *GetAvailableSeatsRequest, opts ...grpc.CallOption) (*GetAvailableSeatsResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Booked Seats
	// |--------------------------------------------------------------------------
	// |
	// | Fetch booked seats for show.
	// |
	// | REST:
	// | GET /shows/{id}/booked-seats
	// |
	GetBookedSeats(ctx context.Context, in *GetBookedSeatsRequest, opts ...grpc.CallOption) (*GetBookedSeatsResponse, error)
}

type seatReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeatReadServiceClient(cc grpc.ClientConnInterface) SeatReadServiceClient {
	return &seatReadServiceClient{cc}
}

func (c *seatReadServiceClient) GetScreenSeats(ctx context.Context, in *GetScreenSeatsRequest, opts ...grpc.CallOption) (*GetScreenSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScreenSeatsResponse)
	err := c.cc.Invoke(ctx, SeatReadService_GetScreenSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatReadServiceClient) GetAvailableSeats(ctx context.Context, in *GetAvailableSeatsRequest, opts ...grpc.CallOption) (*GetAvailableSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableSeatsResponse)
	err := c.cc.Invoke(ctx, SeatReadService_GetAvailableSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatReadServiceClient) GetBookedSeats(ctx context.Context, in *GetBookedSeatsRequest, opts ...grpc.CallOption) (*GetBookedSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBookedSeatsResponse)
	err := c.cc.Invoke(ctx, SeatReadService_GetBookedSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeatReadServiceServer is the server API for SeatReadService service.
// All implementations must embed UnimplementedSeatReadServiceServer
// for forward compatibility.
type SeatReadServiceServer interface {
	// |--------------------------------------------------------------------------
	// | Get Screen Seats
	// |--------------------------------------------------------------------------
	// |
	// | Fetch all seats for screen.
	// |
	// | REST:
	// | GET /screens/{id}/seats
	// |
	GetScreenSeats(context.Context, *GetScreenSeatsRequest) (*GetScreenSeatsResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Available Seats
	// |--------------------------------------------------------------------------
	// |
	// | Fetch available seats for show.
	// |
	// | REST:
	// | GET /shows/{id}/available-seats
	// |
	GetAvailableSeats(context.Context, *GetAvailableSeatsRequest) (*GetAvailableSeatsResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Booked Seats
	// |--------------------------------------------------------------------------
	// |
	// | Fetch booked seats for show.
	// |
	// | REST:
	// | GET /shows/{id}/booked-seats
	// |
	GetBookedSeats(context.Context, *GetBookedSeatsRequest) (*GetBookedSeatsResponse, error)
	mustEmbedUnimplementedSeatReadServiceServer()
}

// UnimplementedSeatReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeatReadServiceServer struct{}

func (UnimplementedSeatReadServiceServer) GetScreenSeats(context.Context, *GetScreenSeatsRequest) (*GetScreenSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScreenSeats not implemented")
}
func (UnimplementedSeatReadServiceServer) GetAvailableSeats(context.Context, *GetAvailableSeatsRequest) (*GetAvailableSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableSeats not implemented")
}
func (UnimplementedSeatReadServiceServer) GetBookedSeats(context.Context, *GetBookedSeatsRequest) (*GetBookedSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookedSeats not implemented")
}
func (UnimplementedSeatReadServiceServer) mustEmbedUnimplementedSeatReadServiceServer() {}
func (UnimplementedSeatReadServiceServer) testEmbeddedByValue()                         {}

// UnsafeSeatReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeatReadServiceServer will
// result in compilation errors.
type UnsafeSeatReadServiceServer interface {
	mustEmbedUnimplementedSeatReadServiceServer()
}

func RegisterSeatReadServiceServer(s grpc.ServiceRegistrar, srv SeatReadServiceServer) {
	// If the following call panics, it indicates UnimplementedSeatReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeatReadService_ServiceDesc, srv)
}

func _SeatReadService_GetScreenSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScreenSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatReadServiceServer).GetScreenSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatReadService_GetScreenSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatReadServiceServer).GetScreenSeats(ctx, req.(*GetScreenSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatReadService_GetAvailableSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatReadServiceServer).GetAvailableSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatReadService_GetAvailableSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatReadServiceServer).GetAvailableSeats(ctx, req.(*GetAvailableSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatReadService_GetBookedSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookedSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatReadServiceServer).GetBookedSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatReadService_GetBookedSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatReadServiceServer).GetBookedSeats(ctx, req.(*GetBookedSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeatReadService_ServiceDesc is the grpc.ServiceDesc for SeatReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeatReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seat_service.read.SeatReadService",
	HandlerType: (*SeatReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScreenSeats",
			Handler:    _SeatReadService_GetScreenSeats_Handler,
		},
		{
			MethodName: "GetAvailableSeats",
			Handler:    _SeatReadService_GetAvailableSeats_Handler,
		},
		{
			MethodName: "GetBookedSeats",
			Handler:    _SeatReadService_GetBookedSeats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seat_service/seat_read.proto",
}
