// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: seat_service/seat_write.proto

package seat_write

import (
	seat_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/seat_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Screen identifier
	ScreenId string `protobuf:"bytes,1,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	// Seat row
	Row string `protobuf:"bytes,2,opt,name=row,proto3" json:"row,omitempty"`
	// Seat number
	Number string `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	// Seat type
	//
	// Example:
	// REGULAR
	// PREMIUM
	// VIP
	SeatType      string `protobuf:"bytes,4,opt,name=seat_type,json=seatType,proto3" json:"seat_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeatRequest) Reset() {
	*x = CreateSeatRequest{}
	mi := &file_seat_service_seat_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeatRequest) ProtoMessage() {}

func (x *CreateSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeatRequest.ProtoReflect.Descriptor instead.
func (*CreateSeatRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_write_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSeatRequest) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *CreateSeatRequest) GetRow() string {
	if x != nil {
		return x.Row
	}
	return ""
}

func (x *CreateSeatRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreateSeatRequest) GetSeatType() string {
	if x != nil {
		return x.SeatType
	}
	return ""
}

type CreateSeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created seat identifier
	SeatId string `protobuf:"bytes,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	// Creation timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeatResponse) Reset() {
	*x = CreateSeatResponse{}
	mi := &file_seat_service_seat_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeatResponse) ProtoMessage() {}

func (x *CreateSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeatResponse.ProtoReflect.Descriptor instead.
func (*CreateSeatResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_write_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSeatResponse) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *CreateSeatResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateSeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Seat identifier
	SeatId string `protobuf:"bytes,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	// Seat row
	Row *string `protobuf:"bytes,2,opt,name=row,proto3,oneof" json:"row,omitempty"`
	// Seat number
	Number *string `protobuf:"bytes,3,opt,name=number,proto3,oneof" json:"number,omitempty"`
	// Seat type
	SeatType *string `protobuf:"bytes,4,opt,name=seat_type,json=seatType,proto3,oneof" json:"seat_type,omitempty"`
	// Seat status
	Status        *seat_service.SeatStatus `protobuf:"varint,5,opt,name=status,proto3,enum=seat_service.status.SeatStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeatRequest) Reset() {
	*x = UpdateSeatRequest{}
	mi := &file_seat_service_seat_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatRequest) ProtoMessage() {}

func (x *UpdateSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatRequest.ProtoReflect.Descriptor instead.
func (*UpdateSeatRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_write_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSeatRequest) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *UpdateSeatRequest) GetRow() string {
	if x != nil && x.Row != nil {
		return *x.Row
	}
	return ""
}

func (x *UpdateSeatRequest) GetNumber() string {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return ""
}

func (x *UpdateSeatRequest) GetSeatType() string {
	if x != nil && x.SeatType != nil {
		return *x.SeatType
	}
	return ""
}

func (x *UpdateSeatRequest) GetStatus() seat_service.SeatStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return seat_service.SeatStatus(0)
}

type UpdateSeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated seat identifier
	SeatId string `protobuf:"bytes,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	// Update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeatResponse) Reset() {
	*x = UpdateSeatResponse{}
	mi := &file_seat_service_seat_write_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatResponse) ProtoMessage() {}

func (x *UpdateSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_write_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatResponse.ProtoReflect.Descriptor instead.
func (*UpdateSeatResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_write_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSeatResponse) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *UpdateSeatResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteSeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Seat identifier
	SeatId        string `protobuf:"bytes,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSeatRequest) Reset() {
	*x = DeleteSeatRequest{}
	mi := &file_seat_service_seat_write_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeatRequest) ProtoMessage() {}

func (x *DeleteSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_write_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeatRequest.ProtoReflect.Descriptor instead.
func (*DeleteSeatRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_write_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSeatRequest) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

type DeleteSeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Deletion timestamp
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSeatResponse) Reset() {
	*x = DeleteSeatResponse{}
	mi := &file_seat_service_seat_write_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeatResponse) ProtoMessage() {}

func (x *DeleteSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_write_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeatResponse.ProtoReflect.Descriptor instead.
func (*DeleteSeatResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_write_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSeatResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_seat_service_seat_write_proto protoreflect.FileDescriptor

const file_seat_service_seat_write_proto_rawDesc = "" +
	"\n" +
	"\x1dseat_service/seat_write.proto\x12\x12seat_service.write\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eseat_service/seat_status.proto\"w\n" +
	"\x11CreateSeatRequest\x12\x1b\n" +
	"\tscreen_id\x18\x01 \x01(\tR\bscreenId\x12\x10\n" +
	"\x03row\x18\x02 \x01(\tR\x03row\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x1b\n" +
	"\tseat_type\x18\x04 \x01(\tR\bseatType\"h\n" +
	"\x12CreateSeatResponse\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\tR\x06seatId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xec\x01\n" +
	"\x11UpdateSeatRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\tR\x06seatId\x12\x15\n" +
	"\x03row\x18\x02 \x01(\tH\x00R\x03row\x88\x01\x01\x12\x1b\n" +
	"\x06number\x18\x03 \x01(\tH\x01R\x06number\x88\x01\x01\x12 \n" +
	"\tseat_type\x18\x04 \x01(\tH\x02R\bseatType\x88\x01\x01\x12<\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1f.seat_service.status.SeatStatusH\x03R\x06status\x88\x01\x01B\x06\n" +
	"\x04_rowB\t\n" +
	"\a_numberB\f\n" +
	"\n" +
	"_seat_typeB\t\n" +
	"\a_status\"h\n" +
	"\x12UpdateSeatResponse\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\tR\x06seatId\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x11DeleteSeatRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\tR\x06seatId\"i\n" +
	"\x12DeleteSeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt2\xa9\x02\n" +
	"\x10SeatWriteService\x12[\n" +
	"\n" +
	"CreateSeat\x12%.seat_service.write.CreateSeatRequest\x1a&.seat_service.write.CreateSeatResponse\x12[\n" +
	"\n" +
	"UpdateSeat\x12%.seat_service.write.UpdateSeatRequest\x1a&.seat_service.write.UpdateSeatResponse\x12[\n" +
	"\n" +
	"DeleteSeat\x12%.seat_service.write.DeleteSeatRequest\x1a&.seat_service.write.DeleteSeatResponseBbZ`github.com/movie-reservation-system-ms/movie_reservation_proto_lib/seat_service/write;seat_writeb\x06proto3"

var (
	file_seat_service_seat_write_proto_rawDescOnce sync.Once
	file_seat_service_seat_write_proto_rawDescData []byte
)

func file_seat_service_seat_write_proto_rawDescGZIP() []byte {
	file_seat_service_seat_write_proto_rawDescOnce.Do(func() {
		file_seat_service_seat_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seat_service_seat_write_proto_rawDesc), len(file_seat_service_seat_write_proto_rawDesc)))
	})
	return file_seat_service_seat_write_proto_rawDescData
}

var file_seat_service_seat_write_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_seat_service_seat_write_proto_goTypes = []any{
	(*CreateSeatRequest)(nil),     // 0: seat_service.write.CreateSeatRequest
	(*CreateSeatResponse)(nil),    // 1: seat_service.write.CreateSeatResponse
	(*UpdateSeatRequest)(nil),     // 2: seat_service.write.UpdateSeatRequest
	(*UpdateSeatResponse)(nil),    // 3: seat_service.write.UpdateSeatResponse
	(*DeleteSeatRequest)(nil),     // 4: seat_service.write.DeleteSeatRequest
	(*DeleteSeatResponse)(nil),    // 5: seat_service.write.DeleteSeatResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(seat_service.SeatStatus)(0),  // 7: seat_service.status.SeatStatus
}
var file_seat_service_seat_write_proto_depIdxs = []int32{
	6, // 0: seat_service.write.CreateSeatResponse.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: seat_service.write.UpdateSeatRequest.status:type_name -> seat_service.status.SeatStatus
	6, // 2: seat_service.write.UpdateSeatResponse.updated_at:type_name -> google.protobuf.Timestamp
	6, // 3: seat_service.write.DeleteSeatResponse.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 4: seat_service.write.SeatWriteService.CreateSeat:input_type -> seat_service.write.CreateSeatRequest
	2, // 5: seat_service.write.SeatWriteService.UpdateSeat:input_type -> seat_service.write.UpdateSeatRequest
	4, // 6: seat_service.write.SeatWriteService.DeleteSeat:input_type -> seat_service.write.DeleteSeatRequest
	1, // 7: seat_service.write.SeatWriteService.CreateSeat:output_type -> seat_service.write.CreateSeatResponse
	3, // 8: seat_service.write.SeatWriteService.UpdateSeat:output_type -> seat_service.write.UpdateSeatResponse
	5, // 9: seat_service.write.SeatWriteService.DeleteSeat:output_type -> seat_service.write.DeleteSeatResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_seat_service_seat_write_proto_init() }
func file_seat_service_seat_write_proto_init() {
	if File_seat_service_seat_write_proto != nil {
		return
	}
	file_seat_service_seat_write_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seat_service_seat_write_proto_rawDesc), len(file_seat_service_seat_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seat_service_seat_write_proto_goTypes,
		DependencyIndexes: file_seat_service_seat_write_proto_depIdxs,
		MessageInfos:      file_seat_service_seat_write_proto_msgTypes,
	}.Build()
	File_seat_service_seat_write_proto = out.File
	file_seat_service_seat_write_proto_goTypes = nil
	file_seat_service_seat_write_proto_depIdxs = nil
}
