// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: seat_service/seat_read.proto

package seat_read

import (
	seat_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/seat_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Seat Entity
// |--------------------------------------------------------------------------
type Seat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Seat identifier
	SeatId string `protobuf:"bytes,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	// Screen identifier
	ScreenId string `protobuf:"bytes,2,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	// Seat row
	//
	// Example:
	// A
	Row string `protobuf:"bytes,3,opt,name=row,proto3" json:"row,omitempty"`
	// Seat number
	//
	// Example:
	// 12
	Number string `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	// Seat type
	//
	// Example:
	// REGULAR
	// PREMIUM
	// VIP
	SeatType string `protobuf:"bytes,5,opt,name=seat_type,json=seatType,proto3" json:"seat_type,omitempty"`
	// Current seat status
	Status seat_service.SeatStatus `protobuf:"varint,6,opt,name=status,proto3,enum=seat_service.status.SeatStatus" json:"status,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_seat_service_seat_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_read_proto_rawDescGZIP(), []int{0}
}

func (x *Seat) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *Seat) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *Seat) GetRow() string {
	if x != nil {
		return x.Row
	}
	return ""
}

func (x *Seat) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Seat) GetSeatType() string {
	if x != nil {
		return x.SeatType
	}
	return ""
}

func (x *Seat) GetStatus() seat_service.SeatStatus {
	if x != nil {
		return x.Status
	}
	return seat_service.SeatStatus(0)
}

func (x *Seat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Seat) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetScreenSeatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Screen identifier
	ScreenId      string `protobuf:"bytes,1,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScreenSeatsRequest) Reset() {
	*x = GetScreenSeatsRequest{}
	mi := &file_seat_service_seat_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScreenSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenSeatsRequest) ProtoMessage() {}

func (x *GetScreenSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetScreenSeatsRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_read_proto_rawDescGZIP(), []int{1}
}

func (x *GetScreenSeatsRequest) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

type GetScreenSeatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Seat list
	Seats         []*Seat `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScreenSeatsResponse) Reset() {
	*x = GetScreenSeatsResponse{}
	mi := &file_seat_service_seat_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScreenSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenSeatsResponse) ProtoMessage() {}

func (x *GetScreenSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenSeatsResponse.ProtoReflect.Descriptor instead.
func (*GetScreenSeatsResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_read_proto_rawDescGZIP(), []int{2}
}

func (x *GetScreenSeatsResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type GetAvailableSeatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show identifier
	ShowId        string `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableSeatsRequest) Reset() {
	*x = GetAvailableSeatsRequest{}
	mi := &file_seat_service_seat_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableSeatsRequest) ProtoMessage() {}

func (x *GetAvailableSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableSeatsRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_read_proto_rawDescGZIP(), []int{3}
}

func (x *GetAvailableSeatsRequest) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

type GetAvailableSeatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Available seats
	Seats         []*Seat `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableSeatsResponse) Reset() {
	*x = GetAvailableSeatsResponse{}
	mi := &file_seat_service_seat_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableSeatsResponse) ProtoMessage() {}

func (x *GetAvailableSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableSeatsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableSeatsResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_read_proto_rawDescGZIP(), []int{4}
}

func (x *GetAvailableSeatsResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type GetBookedSeatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show identifier
	ShowId        string `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookedSeatsRequest) Reset() {
	*x = GetBookedSeatsRequest{}
	mi := &file_seat_service_seat_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookedSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookedSeatsRequest) ProtoMessage() {}

func (x *GetBookedSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookedSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetBookedSeatsRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_read_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookedSeatsRequest) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

type GetBookedSeatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Booked seats
	Seats         []*Seat `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookedSeatsResponse) Reset() {
	*x = GetBookedSeatsResponse{}
	mi := &file_seat_service_seat_read_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookedSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookedSeatsResponse) ProtoMessage() {}

func (x *GetBookedSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_seat_read_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookedSeatsResponse.ProtoReflect.Descriptor instead.
func (*GetBookedSeatsResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_seat_read_proto_rawDescGZIP(), []int{6}
}

func (x *GetBookedSeatsResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

var File_seat_service_seat_read_proto protoreflect.FileDescriptor

const file_seat_service_seat_read_proto_rawDesc = "" +
	"\n" +
	"\x1cseat_service/seat_read.proto\x12\x11seat_service.read\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eseat_service/seat_status.proto\"\xb2\x02\n" +
	"\x04Seat\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\tR\x06seatId\x12\x1b\n" +
	"\tscreen_id\x18\x02 \x01(\tR\bscreenId\x12\x10\n" +
	"\x03row\x18\x03 \x01(\tR\x03row\x12\x16\n" +
	"\x06number\x18\x04 \x01(\tR\x06number\x12\x1b\n" +
	"\tseat_type\x18\x05 \x01(\tR\bseatType\x127\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1f.seat_service.status.SeatStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"4\n" +
	"\x15GetScreenSeatsRequest\x12\x1b\n" +
	"\tscreen_id\x18\x01 \x01(\tR\bscreenId\"G\n" +
	"\x16GetScreenSeatsResponse\x12-\n" +
	"\x05seats\x18\x01 \x03(\v2\x17.seat_service.read.SeatR\x05seats\"3\n" +
	"\x18GetAvailableSeatsRequest\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\"J\n" +
	"\x19GetAvailableSeatsResponse\x12-\n" +
	"\x05seats\x18\x01 \x03(\v2\x17.seat_service.read.SeatR\x05seats\"0\n" +
	"\x15GetBookedSeatsRequest\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\"G\n" +
	"\x16GetBookedSeatsResponse\x12-\n" +
	"\x05seats\x18\x01 \x03(\v2\x17.seat_service.read.SeatR\x05seats2\xcf\x02\n" +
	"\x0fSeatReadService\x12e\n" +
	"\x0eGetScreenSeats\x12(.seat_service.read.GetScreenSeatsRequest\x1a).seat_service.read.GetScreenSeatsResponse\x12n\n" +
	"\x11GetAvailableSeats\x12+.seat_service.read.GetAvailableSeatsRequest\x1a,.seat_service.read.GetAvailableSeatsResponse\x12e\n" +
	"\x0eGetBookedSeats\x12(.seat_service.read.GetBookedSeatsRequest\x1a).seat_service.read.GetBookedSeatsResponseB`Z^github.com/movie-reservation-system-ms/movie_reservation_proto_lib/seat_service/read;seat_readb\x06proto3"

var (
	file_seat_service_seat_read_proto_rawDescOnce sync.Once
	file_seat_service_seat_read_proto_rawDescData []byte
)

func file_seat_service_seat_read_proto_rawDescGZIP() []byte {
	file_seat_service_seat_read_proto_rawDescOnce.Do(func() {
		file_seat_service_seat_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seat_service_seat_read_proto_rawDesc), len(file_seat_service_seat_read_proto_rawDesc)))
	})
	return file_seat_service_seat_read_proto_rawDescData
}

var file_seat_service_seat_read_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_seat_service_seat_read_proto_goTypes = []any{
	(*Seat)(nil),                      // 0: seat_service.read.Seat
	(*GetScreenSeatsRequest)(nil),     // 1: seat_service.read.GetScreenSeatsRequest
	(*GetScreenSeatsResponse)(nil),    // 2: seat_service.read.GetScreenSeatsResponse
	(*GetAvailableSeatsRequest)(nil),  // 3: seat_service.read.GetAvailableSeatsRequest
	(*GetAvailableSeatsResponse)(nil), // 4: seat_service.read.GetAvailableSeatsResponse
	(*GetBookedSeatsRequest)(nil),     // 5: seat_service.read.GetBookedSeatsRequest
	(*GetBookedSeatsResponse)(nil),    // 6: seat_service.read.GetBookedSeatsResponse
	(seat_service.SeatStatus)(0),      // 7: seat_service.status.SeatStatus
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_seat_service_seat_read_proto_depIdxs = []int32{
	7, // 0: seat_service.read.Seat.status:type_name -> seat_service.status.SeatStatus
	8, // 1: seat_service.read.Seat.created_at:type_name -> google.protobuf.Timestamp
	8, // 2: seat_service.read.Seat.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: seat_service.read.GetScreenSeatsResponse.seats:type_name -> seat_service.read.Seat
	0, // 4: seat_service.read.GetAvailableSeatsResponse.seats:type_name -> seat_service.read.Seat
	0, // 5: seat_service.read.GetBookedSeatsResponse.seats:type_name -> seat_service.read.Seat
	1, // 6: seat_service.read.SeatReadService.GetScreenSeats:input_type -> seat_service.read.GetScreenSeatsRequest
	3, // 7: seat_service.read.SeatReadService.GetAvailableSeats:input_type -> seat_service.read.GetAvailableSeatsRequest
	5, // 8: seat_service.read.SeatReadService.GetBookedSeats:input_type -> seat_service.read.GetBookedSeatsRequest
	2, // 9: seat_service.read.SeatReadService.GetScreenSeats:output_type -> seat_service.read.GetScreenSeatsResponse
	4, // 10: seat_service.read.SeatReadService.GetAvailableSeats:output_type -> seat_service.read.GetAvailableSeatsResponse
	6, // 11: seat_service.read.SeatReadService.GetBookedSeats:output_type -> seat_service.read.GetBookedSeatsResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_seat_service_seat_read_proto_init() }
func file_seat_service_seat_read_proto_init() {
	if File_seat_service_seat_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seat_service_seat_read_proto_rawDesc), len(file_seat_service_seat_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seat_service_seat_read_proto_goTypes,
		DependencyIndexes: file_seat_service_seat_read_proto_depIdxs,
		MessageInfos:      file_seat_service_seat_read_proto_msgTypes,
	}.Build()
	File_seat_service_seat_read_proto = out.File
	file_seat_service_seat_read_proto_goTypes = nil
	file_seat_service_seat_read_proto_depIdxs = nil
}
