// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: analytics_service/analytics_write.proto

package analytics_write

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Export Format
// |--------------------------------------------------------------------------
type ExportFormat int32

const (
	ExportFormat_EXPORT_FORMAT_UNSPECIFIED ExportFormat = 0
	ExportFormat_EXPORT_FORMAT_PDF         ExportFormat = 1
	ExportFormat_EXPORT_FORMAT_CSV         ExportFormat = 2
	ExportFormat_EXPORT_FORMAT_XLSX        ExportFormat = 3
)

// Enum value maps for ExportFormat.
var (
	ExportFormat_name = map[int32]string{
		0: "EXPORT_FORMAT_UNSPECIFIED",
		1: "EXPORT_FORMAT_PDF",
		2: "EXPORT_FORMAT_CSV",
		3: "EXPORT_FORMAT_XLSX",
	}
	ExportFormat_value = map[string]int32{
		"EXPORT_FORMAT_UNSPECIFIED": 0,
		"EXPORT_FORMAT_PDF":         1,
		"EXPORT_FORMAT_CSV":         2,
		"EXPORT_FORMAT_XLSX":        3,
	}
)

func (x ExportFormat) Enum() *ExportFormat {
	p := new(ExportFormat)
	*p = x
	return p
}

func (x ExportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_service_analytics_write_proto_enumTypes[0].Descriptor()
}

func (ExportFormat) Type() protoreflect.EnumType {
	return &file_analytics_service_analytics_write_proto_enumTypes[0]
}

func (x ExportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportFormat.Descriptor instead.
func (ExportFormat) EnumDescriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{0}
}

type RefreshRevenueAnalyticsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From date
	//
	// Format:
	// YYYY-MM-DD
	From *string `protobuf:"bytes,1,opt,name=from,proto3,oneof" json:"from,omitempty"`
	// To date
	//
	// Format:
	// YYYY-MM-DD
	To            *string `protobuf:"bytes,2,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRevenueAnalyticsRequest) Reset() {
	*x = RefreshRevenueAnalyticsRequest{}
	mi := &file_analytics_service_analytics_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRevenueAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRevenueAnalyticsRequest) ProtoMessage() {}

func (x *RefreshRevenueAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRevenueAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*RefreshRevenueAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshRevenueAnalyticsRequest) GetFrom() string {
	if x != nil && x.From != nil {
		return *x.From
	}
	return ""
}

func (x *RefreshRevenueAnalyticsRequest) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

type RefreshRevenueAnalyticsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Refresh timestamp
	RefreshedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=refreshed_at,json=refreshedAt,proto3" json:"refreshed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRevenueAnalyticsResponse) Reset() {
	*x = RefreshRevenueAnalyticsResponse{}
	mi := &file_analytics_service_analytics_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRevenueAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRevenueAnalyticsResponse) ProtoMessage() {}

func (x *RefreshRevenueAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRevenueAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*RefreshRevenueAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshRevenueAnalyticsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshRevenueAnalyticsResponse) GetRefreshedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshedAt
	}
	return nil
}

type RefreshBookingAnalyticsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From date
	//
	// Format:
	// YYYY-MM-DD
	From *string `protobuf:"bytes,1,opt,name=from,proto3,oneof" json:"from,omitempty"`
	// To date
	//
	// Format:
	// YYYY-MM-DD
	To            *string `protobuf:"bytes,2,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshBookingAnalyticsRequest) Reset() {
	*x = RefreshBookingAnalyticsRequest{}
	mi := &file_analytics_service_analytics_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshBookingAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshBookingAnalyticsRequest) ProtoMessage() {}

func (x *RefreshBookingAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshBookingAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*RefreshBookingAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshBookingAnalyticsRequest) GetFrom() string {
	if x != nil && x.From != nil {
		return *x.From
	}
	return ""
}

func (x *RefreshBookingAnalyticsRequest) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

type RefreshBookingAnalyticsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Refresh timestamp
	RefreshedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=refreshed_at,json=refreshedAt,proto3" json:"refreshed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshBookingAnalyticsResponse) Reset() {
	*x = RefreshBookingAnalyticsResponse{}
	mi := &file_analytics_service_analytics_write_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshBookingAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshBookingAnalyticsResponse) ProtoMessage() {}

func (x *RefreshBookingAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_write_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshBookingAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*RefreshBookingAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshBookingAnalyticsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshBookingAnalyticsResponse) GetRefreshedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshedAt
	}
	return nil
}

type RefreshPopularMoviesAnalyticsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result limit
	Limit         uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPopularMoviesAnalyticsRequest) Reset() {
	*x = RefreshPopularMoviesAnalyticsRequest{}
	mi := &file_analytics_service_analytics_write_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPopularMoviesAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPopularMoviesAnalyticsRequest) ProtoMessage() {}

func (x *RefreshPopularMoviesAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_write_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPopularMoviesAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*RefreshPopularMoviesAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshPopularMoviesAnalyticsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RefreshPopularMoviesAnalyticsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Refresh timestamp
	RefreshedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=refreshed_at,json=refreshedAt,proto3" json:"refreshed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPopularMoviesAnalyticsResponse) Reset() {
	*x = RefreshPopularMoviesAnalyticsResponse{}
	mi := &file_analytics_service_analytics_write_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPopularMoviesAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPopularMoviesAnalyticsResponse) ProtoMessage() {}

func (x *RefreshPopularMoviesAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_write_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPopularMoviesAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*RefreshPopularMoviesAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshPopularMoviesAnalyticsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshPopularMoviesAnalyticsResponse) GetRefreshedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshedAt
	}
	return nil
}

type RefreshTheatrePerformanceAnalyticsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result limit
	Limit         uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTheatrePerformanceAnalyticsRequest) Reset() {
	*x = RefreshTheatrePerformanceAnalyticsRequest{}
	mi := &file_analytics_service_analytics_write_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTheatrePerformanceAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTheatrePerformanceAnalyticsRequest) ProtoMessage() {}

func (x *RefreshTheatrePerformanceAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_write_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTheatrePerformanceAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*RefreshTheatrePerformanceAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTheatrePerformanceAnalyticsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RefreshTheatrePerformanceAnalyticsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Refresh timestamp
	RefreshedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=refreshed_at,json=refreshedAt,proto3" json:"refreshed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTheatrePerformanceAnalyticsResponse) Reset() {
	*x = RefreshTheatrePerformanceAnalyticsResponse{}
	mi := &file_analytics_service_analytics_write_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTheatrePerformanceAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTheatrePerformanceAnalyticsResponse) ProtoMessage() {}

func (x *RefreshTheatrePerformanceAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_write_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTheatrePerformanceAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*RefreshTheatrePerformanceAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTheatrePerformanceAnalyticsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTheatrePerformanceAnalyticsResponse) GetRefreshedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshedAt
	}
	return nil
}

type ExportAnalyticsReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From date
	//
	// Format:
	// YYYY-MM-DD
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// To date
	//
	// Format:
	// YYYY-MM-DD
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Export format
	Format        ExportFormat `protobuf:"varint,3,opt,name=format,proto3,enum=analytics_service.write.ExportFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAnalyticsReportRequest) Reset() {
	*x = ExportAnalyticsReportRequest{}
	mi := &file_analytics_service_analytics_write_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAnalyticsReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAnalyticsReportRequest) ProtoMessage() {}

func (x *ExportAnalyticsReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_write_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAnalyticsReportRequest.ProtoReflect.Descriptor instead.
func (*ExportAnalyticsReportRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{8}
}

func (x *ExportAnalyticsReportRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ExportAnalyticsReportRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ExportAnalyticsReportRequest) GetFormat() ExportFormat {
	if x != nil {
		return x.Format
	}
	return ExportFormat_EXPORT_FORMAT_UNSPECIFIED
}

type ExportAnalyticsReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Export file URL
	FileUrl string `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	// Export timestamp
	ExportedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=exported_at,json=exportedAt,proto3" json:"exported_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAnalyticsReportResponse) Reset() {
	*x = ExportAnalyticsReportResponse{}
	mi := &file_analytics_service_analytics_write_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAnalyticsReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAnalyticsReportResponse) ProtoMessage() {}

func (x *ExportAnalyticsReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_write_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAnalyticsReportResponse.ProtoReflect.Descriptor instead.
func (*ExportAnalyticsReportResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_write_proto_rawDescGZIP(), []int{9}
}

func (x *ExportAnalyticsReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExportAnalyticsReportResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *ExportAnalyticsReportResponse) GetExportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExportedAt
	}
	return nil
}

var File_analytics_service_analytics_write_proto protoreflect.FileDescriptor

const file_analytics_service_analytics_write_proto_rawDesc = "" +
	"\n" +
	"'analytics_service/analytics_write.proto\x12\x17analytics_service.write\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\x1eRefreshRevenueAnalyticsRequest\x12\x17\n" +
	"\x04from\x18\x01 \x01(\tH\x00R\x04from\x88\x01\x01\x12\x13\n" +
	"\x02to\x18\x02 \x01(\tH\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"z\n" +
	"\x1fRefreshRevenueAnalyticsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12=\n" +
	"\frefreshed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vrefreshedAt\"^\n" +
	"\x1eRefreshBookingAnalyticsRequest\x12\x17\n" +
	"\x04from\x18\x01 \x01(\tH\x00R\x04from\x88\x01\x01\x12\x13\n" +
	"\x02to\x18\x02 \x01(\tH\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"z\n" +
	"\x1fRefreshBookingAnalyticsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12=\n" +
	"\frefreshed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vrefreshedAt\"<\n" +
	"$RefreshPopularMoviesAnalyticsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"\x80\x01\n" +
	"%RefreshPopularMoviesAnalyticsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12=\n" +
	"\frefreshed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vrefreshedAt\"A\n" +
	")RefreshTheatrePerformanceAnalyticsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"\x85\x01\n" +
	"*RefreshTheatrePerformanceAnalyticsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12=\n" +
	"\frefreshed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vrefreshedAt\"\x81\x01\n" +
	"\x1cExportAnalyticsReportRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12=\n" +
	"\x06format\x18\x03 \x01(\x0e2%.analytics_service.write.ExportFormatR\x06format\"\x91\x01\n" +
	"\x1dExportAnalyticsReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\x12;\n" +
	"\vexported_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"exportedAt*s\n" +
	"\fExportFormat\x12\x1d\n" +
	"\x19EXPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EXPORT_FORMAT_PDF\x10\x01\x12\x15\n" +
	"\x11EXPORT_FORMAT_CSV\x10\x02\x12\x16\n" +
	"\x12EXPORT_FORMAT_XLSX\x10\x032\x8f\x06\n" +
	"\x15AnalyticsWriteService\x12\x8c\x01\n" +
	"\x17RefreshRevenueAnalytics\x127.analytics_service.write.RefreshRevenueAnalyticsRequest\x1a8.analytics_service.write.RefreshRevenueAnalyticsResponse\x12\x8c\x01\n" +
	"\x17RefreshBookingAnalytics\x127.analytics_service.write.RefreshBookingAnalyticsRequest\x1a8.analytics_service.write.RefreshBookingAnalyticsResponse\x12\x9e\x01\n" +
	"\x1dRefreshPopularMoviesAnalytics\x12=.analytics_service.write.RefreshPopularMoviesAnalyticsRequest\x1a>.analytics_service.write.RefreshPopularMoviesAnalyticsResponse\x12\xad\x01\n" +
	"\"RefreshTheatrePerformanceAnalytics\x12B.analytics_service.write.RefreshTheatrePerformanceAnalyticsRequest\x1aC.analytics_service.write.RefreshTheatrePerformanceAnalyticsResponse\x12\x86\x01\n" +
	"\x15ExportAnalyticsReport\x125.analytics_service.write.ExportAnalyticsReportRequest\x1a6.analytics_service.write.ExportAnalyticsReportResponseBlZjgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/analytics_service/write;analytics_writeb\x06proto3"

var (
	file_analytics_service_analytics_write_proto_rawDescOnce sync.Once
	file_analytics_service_analytics_write_proto_rawDescData []byte
)

func file_analytics_service_analytics_write_proto_rawDescGZIP() []byte {
	file_analytics_service_analytics_write_proto_rawDescOnce.Do(func() {
		file_analytics_service_analytics_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_service_analytics_write_proto_rawDesc), len(file_analytics_service_analytics_write_proto_rawDesc)))
	})
	return file_analytics_service_analytics_write_proto_rawDescData
}

var file_analytics_service_analytics_write_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_analytics_service_analytics_write_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_analytics_service_analytics_write_proto_goTypes = []any{
	(ExportFormat)(0),                                  // 0: analytics_service.write.ExportFormat
	(*RefreshRevenueAnalyticsRequest)(nil),             // 1: analytics_service.write.RefreshRevenueAnalyticsRequest
	(*RefreshRevenueAnalyticsResponse)(nil),            // 2: analytics_service.write.RefreshRevenueAnalyticsResponse
	(*RefreshBookingAnalyticsRequest)(nil),             // 3: analytics_service.write.RefreshBookingAnalyticsRequest
	(*RefreshBookingAnalyticsResponse)(nil),            // 4: analytics_service.write.RefreshBookingAnalyticsResponse
	(*RefreshPopularMoviesAnalyticsRequest)(nil),       // 5: analytics_service.write.RefreshPopularMoviesAnalyticsRequest
	(*RefreshPopularMoviesAnalyticsResponse)(nil),      // 6: analytics_service.write.RefreshPopularMoviesAnalyticsResponse
	(*RefreshTheatrePerformanceAnalyticsRequest)(nil),  // 7: analytics_service.write.RefreshTheatrePerformanceAnalyticsRequest
	(*RefreshTheatrePerformanceAnalyticsResponse)(nil), // 8: analytics_service.write.RefreshTheatrePerformanceAnalyticsResponse
	(*ExportAnalyticsReportRequest)(nil),               // 9: analytics_service.write.ExportAnalyticsReportRequest
	(*ExportAnalyticsReportResponse)(nil),              // 10: analytics_service.write.ExportAnalyticsReportResponse
	(*timestamppb.Timestamp)(nil),                      // 11: google.protobuf.Timestamp
}
var file_analytics_service_analytics_write_proto_depIdxs = []int32{
	11, // 0: analytics_service.write.RefreshRevenueAnalyticsResponse.refreshed_at:type_name -> google.protobuf.Timestamp
	11, // 1: analytics_service.write.RefreshBookingAnalyticsResponse.refreshed_at:type_name -> google.protobuf.Timestamp
	11, // 2: analytics_service.write.RefreshPopularMoviesAnalyticsResponse.refreshed_at:type_name -> google.protobuf.Timestamp
	11, // 3: analytics_service.write.RefreshTheatrePerformanceAnalyticsResponse.refreshed_at:type_name -> google.protobuf.Timestamp
	0,  // 4: analytics_service.write.ExportAnalyticsReportRequest.format:type_name -> analytics_service.write.ExportFormat
	11, // 5: analytics_service.write.ExportAnalyticsReportResponse.exported_at:type_name -> google.protobuf.Timestamp
	1,  // 6: analytics_service.write.AnalyticsWriteService.RefreshRevenueAnalytics:input_type -> analytics_service.write.RefreshRevenueAnalyticsRequest
	3,  // 7: analytics_service.write.AnalyticsWriteService.RefreshBookingAnalytics:input_type -> analytics_service.write.RefreshBookingAnalyticsRequest
	5,  // 8: analytics_service.write.AnalyticsWriteService.RefreshPopularMoviesAnalytics:input_type -> analytics_service.write.RefreshPopularMoviesAnalyticsRequest
	7,  // 9: analytics_service.write.AnalyticsWriteService.RefreshTheatrePerformanceAnalytics:input_type -> analytics_service.write.RefreshTheatrePerformanceAnalyticsRequest
	9,  // 10: analytics_service.write.AnalyticsWriteService.ExportAnalyticsReport:input_type -> analytics_service.write.ExportAnalyticsReportRequest
	2,  // 11: analytics_service.write.AnalyticsWriteService.RefreshRevenueAnalytics:output_type -> analytics_service.write.RefreshRevenueAnalyticsResponse
	4,  // 12: analytics_service.write.AnalyticsWriteService.RefreshBookingAnalytics:output_type -> analytics_service.write.RefreshBookingAnalyticsResponse
	6,  // 13: analytics_service.write.AnalyticsWriteService.RefreshPopularMoviesAnalytics:output_type -> analytics_service.write.RefreshPopularMoviesAnalyticsResponse
	8,  // 14: analytics_service.write.AnalyticsWriteService.RefreshTheatrePerformanceAnalytics:output_type -> analytics_service.write.RefreshTheatrePerformanceAnalyticsResponse
	10, // 15: analytics_service.write.AnalyticsWriteService.ExportAnalyticsReport:output_type -> analytics_service.write.ExportAnalyticsReportResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_analytics_service_analytics_write_proto_init() }
func file_analytics_service_analytics_write_proto_init() {
	if File_analytics_service_analytics_write_proto != nil {
		return
	}
	file_analytics_service_analytics_write_proto_msgTypes[0].OneofWrappers = []any{}
	file_analytics_service_analytics_write_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_service_analytics_write_proto_rawDesc), len(file_analytics_service_analytics_write_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_service_analytics_write_proto_goTypes,
		DependencyIndexes: file_analytics_service_analytics_write_proto_depIdxs,
		EnumInfos:         file_analytics_service_analytics_write_proto_enumTypes,
		MessageInfos:      file_analytics_service_analytics_write_proto_msgTypes,
	}.Build()
	File_analytics_service_analytics_write_proto = out.File
	file_analytics_service_analytics_write_proto_goTypes = nil
	file_analytics_service_analytics_write_proto_depIdxs = nil
}
