// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: analytics_service/analytics_write.proto

package analytics_write

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsWriteService_RefreshRevenueAnalytics_FullMethodName            = "/analytics_service.write.AnalyticsWriteService/RefreshRevenueAnalytics"
	AnalyticsWriteService_RefreshBookingAnalytics_FullMethodName            = "/analytics_service.write.AnalyticsWriteService/RefreshBookingAnalytics"
	AnalyticsWriteService_RefreshPopularMoviesAnalytics_FullMethodName      = "/analytics_service.write.AnalyticsWriteService/RefreshPopularMoviesAnalytics"
	AnalyticsWriteService_RefreshTheatrePerformanceAnalytics_FullMethodName = "/analytics_service.write.AnalyticsWriteService/RefreshTheatrePerformanceAnalytics"
	AnalyticsWriteService_ExportAnalyticsReport_FullMethodName              = "/analytics_service.write.AnalyticsWriteService/ExportAnalyticsReport"
)

// AnalyticsWriteServiceClient is the client API for AnalyticsWriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsWriteServiceClient interface {
	// |--------------------------------------------------------------------------
	// | Refresh Revenue Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Refresh revenue analytics cache/data.
	// |
	// | REST:
	// | POST /analytics/revenue/refresh
	// |
	RefreshRevenueAnalytics(ctx context.Context, in *RefreshRevenueAnalyticsRequest, opts ...grpc.CallOption) (*RefreshRevenueAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Refresh Booking Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Refresh booking analytics cache/data.
	// |
	// | REST:
	// | POST /analytics/bookings/refresh
	// |
	RefreshBookingAnalytics(ctx context.Context, in *RefreshBookingAnalyticsRequest, opts ...grpc.CallOption) (*RefreshBookingAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Refresh Popular Movies Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Refresh popular movies analytics.
	// |
	// | REST:
	// | POST /analytics/movies/popular/refresh
	// |
	RefreshPopularMoviesAnalytics(ctx context.Context, in *RefreshPopularMoviesAnalyticsRequest, opts ...grpc.CallOption) (*RefreshPopularMoviesAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Refresh Theatre Performance Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Refresh theatre performance analytics.
	// |
	// | REST:
	// | POST /analytics/theatres/performance/refresh
	// |
	RefreshTheatrePerformanceAnalytics(ctx context.Context, in *RefreshTheatrePerformanceAnalyticsRequest, opts ...grpc.CallOption) (*RefreshTheatrePerformanceAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Export Analytics Report
	// |--------------------------------------------------------------------------
	// |
	// | Export analytics report.
	// |
	// | Supported formats:
	// | - PDF
	// | - CSV
	// | - XLSX
	// |
	// | REST:
	// | POST /analytics/export
	// |
	ExportAnalyticsReport(ctx context.Context, in *ExportAnalyticsReportRequest, opts ...grpc.CallOption) (*ExportAnalyticsReportResponse, error)
}

type analyticsWriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsWriteServiceClient(cc grpc.ClientConnInterface) AnalyticsWriteServiceClient {
	return &analyticsWriteServiceClient{cc}
}

func (c *analyticsWriteServiceClient) RefreshRevenueAnalytics(ctx context.Context, in *RefreshRevenueAnalyticsRequest, opts ...grpc.CallOption) (*RefreshRevenueAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshRevenueAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsWriteService_RefreshRevenueAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsWriteServiceClient) RefreshBookingAnalytics(ctx context.Context, in *RefreshBookingAnalyticsRequest, opts ...grpc.CallOption) (*RefreshBookingAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshBookingAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsWriteService_RefreshBookingAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsWriteServiceClient) RefreshPopularMoviesAnalytics(ctx context.Context, in *RefreshPopularMoviesAnalyticsRequest, opts ...grpc.CallOption) (*RefreshPopularMoviesAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshPopularMoviesAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsWriteService_RefreshPopularMoviesAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsWriteServiceClient) RefreshTheatrePerformanceAnalytics(ctx context.Context, in *RefreshTheatrePerformanceAnalyticsRequest, opts ...grpc.CallOption) (*RefreshTheatrePerformanceAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTheatrePerformanceAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsWriteService_RefreshTheatrePerformanceAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsWriteServiceClient) ExportAnalyticsReport(ctx context.Context, in *ExportAnalyticsReportRequest, opts ...grpc.CallOption) (*ExportAnalyticsReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportAnalyticsReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsWriteService_ExportAnalyticsReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsWriteServiceServer is the server API for AnalyticsWriteService service.
// All implementations must embed UnimplementedAnalyticsWriteServiceServer
// for forward compatibility.
type AnalyticsWriteServiceServer interface {
	// |--------------------------------------------------------------------------
	// | Refresh Revenue Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Refresh revenue analytics cache/data.
	// |
	// | REST:
	// | POST /analytics/revenue/refresh
	// |
	RefreshRevenueAnalytics(context.Context, *RefreshRevenueAnalyticsRequest) (*RefreshRevenueAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Refresh Booking Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Refresh booking analytics cache/data.
	// |
	// | REST:
	// | POST /analytics/bookings/refresh
	// |
	RefreshBookingAnalytics(context.Context, *RefreshBookingAnalyticsRequest) (*RefreshBookingAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Refresh Popular Movies Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Refresh popular movies analytics.
	// |
	// | REST:
	// | POST /analytics/movies/popular/refresh
	// |
	RefreshPopularMoviesAnalytics(context.Context, *RefreshPopularMoviesAnalyticsRequest) (*RefreshPopularMoviesAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Refresh Theatre Performance Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Refresh theatre performance analytics.
	// |
	// | REST:
	// | POST /analytics/theatres/performance/refresh
	// |
	RefreshTheatrePerformanceAnalytics(context.Context, *RefreshTheatrePerformanceAnalyticsRequest) (*RefreshTheatrePerformanceAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Export Analytics Report
	// |--------------------------------------------------------------------------
	// |
	// | Export analytics report.
	// |
	// | Supported formats:
	// | - PDF
	// | - CSV
	// | - XLSX
	// |
	// | REST:
	// | POST /analytics/export
	// |
	ExportAnalyticsReport(context.Context, *ExportAnalyticsReportRequest) (*ExportAnalyticsReportResponse, error)
	mustEmbedUnimplementedAnalyticsWriteServiceServer()
}

// UnimplementedAnalyticsWriteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsWriteServiceServer struct{}

func (UnimplementedAnalyticsWriteServiceServer) RefreshRevenueAnalytics(context.Context, *RefreshRevenueAnalyticsRequest) (*RefreshRevenueAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshRevenueAnalytics not implemented")
}
func (UnimplementedAnalyticsWriteServiceServer) RefreshBookingAnalytics(context.Context, *RefreshBookingAnalyticsRequest) (*RefreshBookingAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshBookingAnalytics not implemented")
}
func (UnimplementedAnalyticsWriteServiceServer) RefreshPopularMoviesAnalytics(context.Context, *RefreshPopularMoviesAnalyticsRequest) (*RefreshPopularMoviesAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshPopularMoviesAnalytics not implemented")
}
func (UnimplementedAnalyticsWriteServiceServer) RefreshTheatrePerformanceAnalytics(context.Context, *RefreshTheatrePerformanceAnalyticsRequest) (*RefreshTheatrePerformanceAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshTheatrePerformanceAnalytics not implemented")
}
func (UnimplementedAnalyticsWriteServiceServer) ExportAnalyticsReport(context.Context, *ExportAnalyticsReportRequest) (*ExportAnalyticsReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportAnalyticsReport not implemented")
}
func (UnimplementedAnalyticsWriteServiceServer) mustEmbedUnimplementedAnalyticsWriteServiceServer() {}
func (UnimplementedAnalyticsWriteServiceServer) testEmbeddedByValue()                               {}

// UnsafeAnalyticsWriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsWriteServiceServer will
// result in compilation errors.
type UnsafeAnalyticsWriteServiceServer interface {
	mustEmbedUnimplementedAnalyticsWriteServiceServer()
}

func RegisterAnalyticsWriteServiceServer(s grpc.ServiceRegistrar, srv AnalyticsWriteServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsWriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsWriteService_ServiceDesc, srv)
}

func _AnalyticsWriteService_RefreshRevenueAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRevenueAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsWriteServiceServer).RefreshRevenueAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsWriteService_RefreshRevenueAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsWriteServiceServer).RefreshRevenueAnalytics(ctx, req.(*RefreshRevenueAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsWriteService_RefreshBookingAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshBookingAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsWriteServiceServer).RefreshBookingAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsWriteService_RefreshBookingAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsWriteServiceServer).RefreshBookingAnalytics(ctx, req.(*RefreshBookingAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsWriteService_RefreshPopularMoviesAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshPopularMoviesAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsWriteServiceServer).RefreshPopularMoviesAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsWriteService_RefreshPopularMoviesAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsWriteServiceServer).RefreshPopularMoviesAnalytics(ctx, req.(*RefreshPopularMoviesAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsWriteService_RefreshTheatrePerformanceAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTheatrePerformanceAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsWriteServiceServer).RefreshTheatrePerformanceAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsWriteService_RefreshTheatrePerformanceAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsWriteServiceServer).RefreshTheatrePerformanceAnalytics(ctx, req.(*RefreshTheatrePerformanceAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsWriteService_ExportAnalyticsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportAnalyticsReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsWriteServiceServer).ExportAnalyticsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsWriteService_ExportAnalyticsReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsWriteServiceServer).ExportAnalyticsReport(ctx, req.(*ExportAnalyticsReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsWriteService_ServiceDesc is the grpc.ServiceDesc for AnalyticsWriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsWriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics_service.write.AnalyticsWriteService",
	HandlerType: (*AnalyticsWriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshRevenueAnalytics",
			Handler:    _AnalyticsWriteService_RefreshRevenueAnalytics_Handler,
		},
		{
			MethodName: "RefreshBookingAnalytics",
			Handler:    _AnalyticsWriteService_RefreshBookingAnalytics_Handler,
		},
		{
			MethodName: "RefreshPopularMoviesAnalytics",
			Handler:    _AnalyticsWriteService_RefreshPopularMoviesAnalytics_Handler,
		},
		{
			MethodName: "RefreshTheatrePerformanceAnalytics",
			Handler:    _AnalyticsWriteService_RefreshTheatrePerformanceAnalytics_Handler,
		},
		{
			MethodName: "ExportAnalyticsReport",
			Handler:    _AnalyticsWriteService_ExportAnalyticsReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics_service/analytics_write.proto",
}
