// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: analytics_service/analytics_read.proto

package analytics_read

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsReadService_GetRevenueAnalytics_FullMethodName     = "/analytics_service.read.AnalyticsReadService/GetRevenueAnalytics"
	AnalyticsReadService_GetBookingAnalytics_FullMethodName     = "/analytics_service.read.AnalyticsReadService/GetBookingAnalytics"
	AnalyticsReadService_GetPopularMovies_FullMethodName        = "/analytics_service.read.AnalyticsReadService/GetPopularMovies"
	AnalyticsReadService_GetTheatrePerformance_FullMethodName   = "/analytics_service.read.AnalyticsReadService/GetTheatrePerformance"
	AnalyticsReadService_GetAnalyticsByDateRange_FullMethodName = "/analytics_service.read.AnalyticsReadService/GetAnalyticsByDateRange"
)

// AnalyticsReadServiceClient is the client API for AnalyticsReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsReadServiceClient interface {
	// |--------------------------------------------------------------------------
	// | Get Revenue Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Fetch revenue analytics summary.
	// |
	// | REST:
	// | GET /analytics/revenue
	// |
	GetRevenueAnalytics(ctx context.Context, in *GetRevenueAnalyticsRequest, opts ...grpc.CallOption) (*GetRevenueAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Booking Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Fetch booking analytics summary.
	// |
	// | REST:
	// | GET /analytics/bookings
	// |
	GetBookingAnalytics(ctx context.Context, in *GetBookingAnalyticsRequest, opts ...grpc.CallOption) (*GetBookingAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Popular Movies
	// |--------------------------------------------------------------------------
	// |
	// | Fetch most popular movies.
	// |
	// | REST:
	// | GET /analytics/movies/popular
	// |
	GetPopularMovies(ctx context.Context, in *GetPopularMoviesRequest, opts ...grpc.CallOption) (*GetPopularMoviesResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Theatre Performance
	// |--------------------------------------------------------------------------
	// |
	// | Fetch theatre performance analytics.
	// |
	// | REST:
	// | GET /analytics/theatres/performance
	// |
	GetTheatrePerformance(ctx context.Context, in *GetTheatrePerformanceRequest, opts ...grpc.CallOption) (*GetTheatrePerformanceResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Analytics By Date Range
	// |--------------------------------------------------------------------------
	// |
	// | Fetch analytics between date range.
	// |
	// | REST:
	// | GET /analytics?from=DATE&to=DATE
	// |
	GetAnalyticsByDateRange(ctx context.Context, in *GetAnalyticsByDateRangeRequest, opts ...grpc.CallOption) (*GetAnalyticsByDateRangeResponse, error)
}

type analyticsReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsReadServiceClient(cc grpc.ClientConnInterface) AnalyticsReadServiceClient {
	return &analyticsReadServiceClient{cc}
}

func (c *analyticsReadServiceClient) GetRevenueAnalytics(ctx context.Context, in *GetRevenueAnalyticsRequest, opts ...grpc.CallOption) (*GetRevenueAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevenueAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsReadService_GetRevenueAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsReadServiceClient) GetBookingAnalytics(ctx context.Context, in *GetBookingAnalyticsRequest, opts ...grpc.CallOption) (*GetBookingAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBookingAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsReadService_GetBookingAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsReadServiceClient) GetPopularMovies(ctx context.Context, in *GetPopularMoviesRequest, opts ...grpc.CallOption) (*GetPopularMoviesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPopularMoviesResponse)
	err := c.cc.Invoke(ctx, AnalyticsReadService_GetPopularMovies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsReadServiceClient) GetTheatrePerformance(ctx context.Context, in *GetTheatrePerformanceRequest, opts ...grpc.CallOption) (*GetTheatrePerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTheatrePerformanceResponse)
	err := c.cc.Invoke(ctx, AnalyticsReadService_GetTheatrePerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsReadServiceClient) GetAnalyticsByDateRange(ctx context.Context, in *GetAnalyticsByDateRangeRequest, opts ...grpc.CallOption) (*GetAnalyticsByDateRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalyticsByDateRangeResponse)
	err := c.cc.Invoke(ctx, AnalyticsReadService_GetAnalyticsByDateRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsReadServiceServer is the server API for AnalyticsReadService service.
// All implementations must embed UnimplementedAnalyticsReadServiceServer
// for forward compatibility.
type AnalyticsReadServiceServer interface {
	// |--------------------------------------------------------------------------
	// | Get Revenue Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Fetch revenue analytics summary.
	// |
	// | REST:
	// | GET /analytics/revenue
	// |
	GetRevenueAnalytics(context.Context, *GetRevenueAnalyticsRequest) (*GetRevenueAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Booking Analytics
	// |--------------------------------------------------------------------------
	// |
	// | Fetch booking analytics summary.
	// |
	// | REST:
	// | GET /analytics/bookings
	// |
	GetBookingAnalytics(context.Context, *GetBookingAnalyticsRequest) (*GetBookingAnalyticsResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Popular Movies
	// |--------------------------------------------------------------------------
	// |
	// | Fetch most popular movies.
	// |
	// | REST:
	// | GET /analytics/movies/popular
	// |
	GetPopularMovies(context.Context, *GetPopularMoviesRequest) (*GetPopularMoviesResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Theatre Performance
	// |--------------------------------------------------------------------------
	// |
	// | Fetch theatre performance analytics.
	// |
	// | REST:
	// | GET /analytics/theatres/performance
	// |
	GetTheatrePerformance(context.Context, *GetTheatrePerformanceRequest) (*GetTheatrePerformanceResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Analytics By Date Range
	// |--------------------------------------------------------------------------
	// |
	// | Fetch analytics between date range.
	// |
	// | REST:
	// | GET /analytics?from=DATE&to=DATE
	// |
	GetAnalyticsByDateRange(context.Context, *GetAnalyticsByDateRangeRequest) (*GetAnalyticsByDateRangeResponse, error)
	mustEmbedUnimplementedAnalyticsReadServiceServer()
}

// UnimplementedAnalyticsReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsReadServiceServer struct{}

func (UnimplementedAnalyticsReadServiceServer) GetRevenueAnalytics(context.Context, *GetRevenueAnalyticsRequest) (*GetRevenueAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevenueAnalytics not implemented")
}
func (UnimplementedAnalyticsReadServiceServer) GetBookingAnalytics(context.Context, *GetBookingAnalyticsRequest) (*GetBookingAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookingAnalytics not implemented")
}
func (UnimplementedAnalyticsReadServiceServer) GetPopularMovies(context.Context, *GetPopularMoviesRequest) (*GetPopularMoviesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularMovies not implemented")
}
func (UnimplementedAnalyticsReadServiceServer) GetTheatrePerformance(context.Context, *GetTheatrePerformanceRequest) (*GetTheatrePerformanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTheatrePerformance not implemented")
}
func (UnimplementedAnalyticsReadServiceServer) GetAnalyticsByDateRange(context.Context, *GetAnalyticsByDateRangeRequest) (*GetAnalyticsByDateRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalyticsByDateRange not implemented")
}
func (UnimplementedAnalyticsReadServiceServer) mustEmbedUnimplementedAnalyticsReadServiceServer() {}
func (UnimplementedAnalyticsReadServiceServer) testEmbeddedByValue()                              {}

// UnsafeAnalyticsReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsReadServiceServer will
// result in compilation errors.
type UnsafeAnalyticsReadServiceServer interface {
	mustEmbedUnimplementedAnalyticsReadServiceServer()
}

func RegisterAnalyticsReadServiceServer(s grpc.ServiceRegistrar, srv AnalyticsReadServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsReadService_ServiceDesc, srv)
}

func _AnalyticsReadService_GetRevenueAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevenueAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsReadServiceServer).GetRevenueAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsReadService_GetRevenueAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsReadServiceServer).GetRevenueAnalytics(ctx, req.(*GetRevenueAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsReadService_GetBookingAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsReadServiceServer).GetBookingAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsReadService_GetBookingAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsReadServiceServer).GetBookingAnalytics(ctx, req.(*GetBookingAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsReadService_GetPopularMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularMoviesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsReadServiceServer).GetPopularMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsReadService_GetPopularMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsReadServiceServer).GetPopularMovies(ctx, req.(*GetPopularMoviesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsReadService_GetTheatrePerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTheatrePerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsReadServiceServer).GetTheatrePerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsReadService_GetTheatrePerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsReadServiceServer).GetTheatrePerformance(ctx, req.(*GetTheatrePerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsReadService_GetAnalyticsByDateRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalyticsByDateRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsReadServiceServer).GetAnalyticsByDateRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsReadService_GetAnalyticsByDateRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsReadServiceServer).GetAnalyticsByDateRange(ctx, req.(*GetAnalyticsByDateRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsReadService_ServiceDesc is the grpc.ServiceDesc for AnalyticsReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics_service.read.AnalyticsReadService",
	HandlerType: (*AnalyticsReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRevenueAnalytics",
			Handler:    _AnalyticsReadService_GetRevenueAnalytics_Handler,
		},
		{
			MethodName: "GetBookingAnalytics",
			Handler:    _AnalyticsReadService_GetBookingAnalytics_Handler,
		},
		{
			MethodName: "GetPopularMovies",
			Handler:    _AnalyticsReadService_GetPopularMovies_Handler,
		},
		{
			MethodName: "GetTheatrePerformance",
			Handler:    _AnalyticsReadService_GetTheatrePerformance_Handler,
		},
		{
			MethodName: "GetAnalyticsByDateRange",
			Handler:    _AnalyticsReadService_GetAnalyticsByDateRange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics_service/analytics_read.proto",
}
