// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: analytics_service/analytics_read.proto

package analytics_read

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Revenue Analytics
// |--------------------------------------------------------------------------
type RevenueAnalytics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total revenue
	TotalRevenue float64 `protobuf:"fixed64,1,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	// Total successful payments
	SuccessfulPayments uint64 `protobuf:"varint,2,opt,name=successful_payments,json=successfulPayments,proto3" json:"successful_payments,omitempty"`
	// Total refunded amount
	RefundedAmount float64 `protobuf:"fixed64,3,opt,name=refunded_amount,json=refundedAmount,proto3" json:"refunded_amount,omitempty"`
	// Currency
	Currency      string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevenueAnalytics) Reset() {
	*x = RevenueAnalytics{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenueAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueAnalytics) ProtoMessage() {}

func (x *RevenueAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueAnalytics.ProtoReflect.Descriptor instead.
func (*RevenueAnalytics) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{0}
}

func (x *RevenueAnalytics) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *RevenueAnalytics) GetSuccessfulPayments() uint64 {
	if x != nil {
		return x.SuccessfulPayments
	}
	return 0
}

func (x *RevenueAnalytics) GetRefundedAmount() float64 {
	if x != nil {
		return x.RefundedAmount
	}
	return 0
}

func (x *RevenueAnalytics) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// |--------------------------------------------------------------------------
// | Booking Analytics
// |--------------------------------------------------------------------------
type BookingAnalytics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total bookings
	TotalBookings uint64 `protobuf:"varint,1,opt,name=total_bookings,json=totalBookings,proto3" json:"total_bookings,omitempty"`
	// Confirmed bookings
	ConfirmedBookings uint64 `protobuf:"varint,2,opt,name=confirmed_bookings,json=confirmedBookings,proto3" json:"confirmed_bookings,omitempty"`
	// Cancelled bookings
	CancelledBookings uint64 `protobuf:"varint,3,opt,name=cancelled_bookings,json=cancelledBookings,proto3" json:"cancelled_bookings,omitempty"`
	// Failed bookings
	FailedBookings uint64 `protobuf:"varint,4,opt,name=failed_bookings,json=failedBookings,proto3" json:"failed_bookings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookingAnalytics) Reset() {
	*x = BookingAnalytics{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingAnalytics) ProtoMessage() {}

func (x *BookingAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingAnalytics.ProtoReflect.Descriptor instead.
func (*BookingAnalytics) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{1}
}

func (x *BookingAnalytics) GetTotalBookings() uint64 {
	if x != nil {
		return x.TotalBookings
	}
	return 0
}

func (x *BookingAnalytics) GetConfirmedBookings() uint64 {
	if x != nil {
		return x.ConfirmedBookings
	}
	return 0
}

func (x *BookingAnalytics) GetCancelledBookings() uint64 {
	if x != nil {
		return x.CancelledBookings
	}
	return 0
}

func (x *BookingAnalytics) GetFailedBookings() uint64 {
	if x != nil {
		return x.FailedBookings
	}
	return 0
}

// |--------------------------------------------------------------------------
// | Popular Movie Entity
// |--------------------------------------------------------------------------
type PopularMovie struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie identifier
	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// Movie title
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Total bookings
	Bookings uint64 `protobuf:"varint,3,opt,name=bookings,proto3" json:"bookings,omitempty"`
	// Total revenue
	Revenue       float64 `protobuf:"fixed64,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularMovie) Reset() {
	*x = PopularMovie{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularMovie) ProtoMessage() {}

func (x *PopularMovie) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularMovie.ProtoReflect.Descriptor instead.
func (*PopularMovie) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{2}
}

func (x *PopularMovie) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *PopularMovie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PopularMovie) GetBookings() uint64 {
	if x != nil {
		return x.Bookings
	}
	return 0
}

func (x *PopularMovie) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

// |--------------------------------------------------------------------------
// | Theatre Performance Entity
// |--------------------------------------------------------------------------
type TheatrePerformance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Theatre identifier
	TheatreId string `protobuf:"bytes,1,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	// Theatre name
	TheatreName string `protobuf:"bytes,2,opt,name=theatre_name,json=theatreName,proto3" json:"theatre_name,omitempty"`
	// Total bookings
	Bookings uint64 `protobuf:"varint,3,opt,name=bookings,proto3" json:"bookings,omitempty"`
	// Total revenue
	Revenue float64 `protobuf:"fixed64,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	// Occupancy percentage
	OccupancyRate float64 `protobuf:"fixed64,5,opt,name=occupancy_rate,json=occupancyRate,proto3" json:"occupancy_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TheatrePerformance) Reset() {
	*x = TheatrePerformance{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TheatrePerformance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TheatrePerformance) ProtoMessage() {}

func (x *TheatrePerformance) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TheatrePerformance.ProtoReflect.Descriptor instead.
func (*TheatrePerformance) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{3}
}

func (x *TheatrePerformance) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

func (x *TheatrePerformance) GetTheatreName() string {
	if x != nil {
		return x.TheatreName
	}
	return ""
}

func (x *TheatrePerformance) GetBookings() uint64 {
	if x != nil {
		return x.Bookings
	}
	return 0
}

func (x *TheatrePerformance) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *TheatrePerformance) GetOccupancyRate() float64 {
	if x != nil {
		return x.OccupancyRate
	}
	return 0
}

// |--------------------------------------------------------------------------
// | Analytics Summary
// |--------------------------------------------------------------------------
type AnalyticsSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total revenue
	TotalRevenue float64 `protobuf:"fixed64,1,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	// Total bookings
	TotalBookings uint64 `protobuf:"varint,2,opt,name=total_bookings,json=totalBookings,proto3" json:"total_bookings,omitempty"`
	// Total tickets sold
	TotalTicketsSold uint64 `protobuf:"varint,3,opt,name=total_tickets_sold,json=totalTicketsSold,proto3" json:"total_tickets_sold,omitempty"`
	// Total cancelled bookings
	TotalCancelledBookings uint64 `protobuf:"varint,4,opt,name=total_cancelled_bookings,json=totalCancelledBookings,proto3" json:"total_cancelled_bookings,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AnalyticsSummary) Reset() {
	*x = AnalyticsSummary{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsSummary) ProtoMessage() {}

func (x *AnalyticsSummary) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsSummary.ProtoReflect.Descriptor instead.
func (*AnalyticsSummary) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyticsSummary) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *AnalyticsSummary) GetTotalBookings() uint64 {
	if x != nil {
		return x.TotalBookings
	}
	return 0
}

func (x *AnalyticsSummary) GetTotalTicketsSold() uint64 {
	if x != nil {
		return x.TotalTicketsSold
	}
	return 0
}

func (x *AnalyticsSummary) GetTotalCancelledBookings() uint64 {
	if x != nil {
		return x.TotalCancelledBookings
	}
	return 0
}

type GetRevenueAnalyticsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From date
	//
	// Format:
	// YYYY-MM-DD
	From *string `protobuf:"bytes,1,opt,name=from,proto3,oneof" json:"from,omitempty"`
	// To date
	//
	// Format:
	// YYYY-MM-DD
	To            *string `protobuf:"bytes,2,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevenueAnalyticsRequest) Reset() {
	*x = GetRevenueAnalyticsRequest{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevenueAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevenueAnalyticsRequest) ProtoMessage() {}

func (x *GetRevenueAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevenueAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetRevenueAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{5}
}

func (x *GetRevenueAnalyticsRequest) GetFrom() string {
	if x != nil && x.From != nil {
		return *x.From
	}
	return ""
}

func (x *GetRevenueAnalyticsRequest) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

type GetRevenueAnalyticsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Revenue analytics
	Analytics     *RevenueAnalytics `protobuf:"bytes,1,opt,name=analytics,proto3" json:"analytics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevenueAnalyticsResponse) Reset() {
	*x = GetRevenueAnalyticsResponse{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevenueAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevenueAnalyticsResponse) ProtoMessage() {}

func (x *GetRevenueAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevenueAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetRevenueAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{6}
}

func (x *GetRevenueAnalyticsResponse) GetAnalytics() *RevenueAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

type GetBookingAnalyticsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From date
	//
	// Format:
	// YYYY-MM-DD
	From *string `protobuf:"bytes,1,opt,name=from,proto3,oneof" json:"from,omitempty"`
	// To date
	//
	// Format:
	// YYYY-MM-DD
	To            *string `protobuf:"bytes,2,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingAnalyticsRequest) Reset() {
	*x = GetBookingAnalyticsRequest{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingAnalyticsRequest) ProtoMessage() {}

func (x *GetBookingAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetBookingAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{7}
}

func (x *GetBookingAnalyticsRequest) GetFrom() string {
	if x != nil && x.From != nil {
		return *x.From
	}
	return ""
}

func (x *GetBookingAnalyticsRequest) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

type GetBookingAnalyticsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Booking analytics
	Analytics     *BookingAnalytics `protobuf:"bytes,1,opt,name=analytics,proto3" json:"analytics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingAnalyticsResponse) Reset() {
	*x = GetBookingAnalyticsResponse{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingAnalyticsResponse) ProtoMessage() {}

func (x *GetBookingAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetBookingAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{8}
}

func (x *GetBookingAnalyticsResponse) GetAnalytics() *BookingAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

type GetPopularMoviesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result limit
	Limit         uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularMoviesRequest) Reset() {
	*x = GetPopularMoviesRequest{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularMoviesRequest) ProtoMessage() {}

func (x *GetPopularMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetPopularMoviesRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{9}
}

func (x *GetPopularMoviesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPopularMoviesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Popular movies
	Movies        []*PopularMovie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularMoviesResponse) Reset() {
	*x = GetPopularMoviesResponse{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularMoviesResponse) ProtoMessage() {}

func (x *GetPopularMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetPopularMoviesResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{10}
}

func (x *GetPopularMoviesResponse) GetMovies() []*PopularMovie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type GetTheatrePerformanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result limit
	Limit         uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTheatrePerformanceRequest) Reset() {
	*x = GetTheatrePerformanceRequest{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTheatrePerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatrePerformanceRequest) ProtoMessage() {}

func (x *GetTheatrePerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatrePerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetTheatrePerformanceRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{11}
}

func (x *GetTheatrePerformanceRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTheatrePerformanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Theatre performance list
	Theatres      []*TheatrePerformance `protobuf:"bytes,1,rep,name=theatres,proto3" json:"theatres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTheatrePerformanceResponse) Reset() {
	*x = GetTheatrePerformanceResponse{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTheatrePerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatrePerformanceResponse) ProtoMessage() {}

func (x *GetTheatrePerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatrePerformanceResponse.ProtoReflect.Descriptor instead.
func (*GetTheatrePerformanceResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{12}
}

func (x *GetTheatrePerformanceResponse) GetTheatres() []*TheatrePerformance {
	if x != nil {
		return x.Theatres
	}
	return nil
}

type GetAnalyticsByDateRangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From date
	//
	// Format:
	// YYYY-MM-DD
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// To date
	//
	// Format:
	// YYYY-MM-DD
	To            string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsByDateRangeRequest) Reset() {
	*x = GetAnalyticsByDateRangeRequest{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsByDateRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsByDateRangeRequest) ProtoMessage() {}

func (x *GetAnalyticsByDateRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsByDateRangeRequest.ProtoReflect.Descriptor instead.
func (*GetAnalyticsByDateRangeRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{13}
}

func (x *GetAnalyticsByDateRangeRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetAnalyticsByDateRangeRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type GetAnalyticsByDateRangeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Analytics summary
	Analytics *AnalyticsSummary `protobuf:"bytes,1,opt,name=analytics,proto3" json:"analytics,omitempty"`
	// Generated timestamp
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsByDateRangeResponse) Reset() {
	*x = GetAnalyticsByDateRangeResponse{}
	mi := &file_analytics_service_analytics_read_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsByDateRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsByDateRangeResponse) ProtoMessage() {}

func (x *GetAnalyticsByDateRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_read_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsByDateRangeResponse.ProtoReflect.Descriptor instead.
func (*GetAnalyticsByDateRangeResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_read_proto_rawDescGZIP(), []int{14}
}

func (x *GetAnalyticsByDateRangeResponse) GetAnalytics() *AnalyticsSummary {
	if x != nil {
		return x.Analytics
	}
	return nil
}

func (x *GetAnalyticsByDateRangeResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

var File_analytics_service_analytics_read_proto protoreflect.FileDescriptor

const file_analytics_service_analytics_read_proto_rawDesc = "" +
	"\n" +
	"&analytics_service/analytics_read.proto\x12\x16analytics_service.read\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x01\n" +
	"\x10RevenueAnalytics\x12#\n" +
	"\rtotal_revenue\x18\x01 \x01(\x01R\ftotalRevenue\x12/\n" +
	"\x13successful_payments\x18\x02 \x01(\x04R\x12successfulPayments\x12'\n" +
	"\x0frefunded_amount\x18\x03 \x01(\x01R\x0erefundedAmount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\xc0\x01\n" +
	"\x10BookingAnalytics\x12%\n" +
	"\x0etotal_bookings\x18\x01 \x01(\x04R\rtotalBookings\x12-\n" +
	"\x12confirmed_bookings\x18\x02 \x01(\x04R\x11confirmedBookings\x12-\n" +
	"\x12cancelled_bookings\x18\x03 \x01(\x04R\x11cancelledBookings\x12'\n" +
	"\x0ffailed_bookings\x18\x04 \x01(\x04R\x0efailedBookings\"u\n" +
	"\fPopularMovie\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bbookings\x18\x03 \x01(\x04R\bbookings\x12\x18\n" +
	"\arevenue\x18\x04 \x01(\x01R\arevenue\"\xb3\x01\n" +
	"\x12TheatrePerformance\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x01 \x01(\tR\ttheatreId\x12!\n" +
	"\ftheatre_name\x18\x02 \x01(\tR\vtheatreName\x12\x1a\n" +
	"\bbookings\x18\x03 \x01(\x04R\bbookings\x12\x18\n" +
	"\arevenue\x18\x04 \x01(\x01R\arevenue\x12%\n" +
	"\x0eoccupancy_rate\x18\x05 \x01(\x01R\roccupancyRate\"\xc6\x01\n" +
	"\x10AnalyticsSummary\x12#\n" +
	"\rtotal_revenue\x18\x01 \x01(\x01R\ftotalRevenue\x12%\n" +
	"\x0etotal_bookings\x18\x02 \x01(\x04R\rtotalBookings\x12,\n" +
	"\x12total_tickets_sold\x18\x03 \x01(\x04R\x10totalTicketsSold\x128\n" +
	"\x18total_cancelled_bookings\x18\x04 \x01(\x04R\x16totalCancelledBookings\"Z\n" +
	"\x1aGetRevenueAnalyticsRequest\x12\x17\n" +
	"\x04from\x18\x01 \x01(\tH\x00R\x04from\x88\x01\x01\x12\x13\n" +
	"\x02to\x18\x02 \x01(\tH\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"e\n" +
	"\x1bGetRevenueAnalyticsResponse\x12F\n" +
	"\tanalytics\x18\x01 \x01(\v2(.analytics_service.read.RevenueAnalyticsR\tanalytics\"Z\n" +
	"\x1aGetBookingAnalyticsRequest\x12\x17\n" +
	"\x04from\x18\x01 \x01(\tH\x00R\x04from\x88\x01\x01\x12\x13\n" +
	"\x02to\x18\x02 \x01(\tH\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"e\n" +
	"\x1bGetBookingAnalyticsResponse\x12F\n" +
	"\tanalytics\x18\x01 \x01(\v2(.analytics_service.read.BookingAnalyticsR\tanalytics\"/\n" +
	"\x17GetPopularMoviesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"X\n" +
	"\x18GetPopularMoviesResponse\x12<\n" +
	"\x06movies\x18\x01 \x03(\v2$.analytics_service.read.PopularMovieR\x06movies\"4\n" +
	"\x1cGetTheatrePerformanceRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"g\n" +
	"\x1dGetTheatrePerformanceResponse\x12F\n" +
	"\btheatres\x18\x01 \x03(\v2*.analytics_service.read.TheatrePerformanceR\btheatres\"D\n" +
	"\x1eGetAnalyticsByDateRangeRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\xa8\x01\n" +
	"\x1fGetAnalyticsByDateRangeResponse\x12F\n" +
	"\tanalytics\x18\x01 \x01(\v2(.analytics_service.read.AnalyticsSummaryR\tanalytics\x12=\n" +
	"\fgenerated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt2\xa1\x05\n" +
	"\x14AnalyticsReadService\x12~\n" +
	"\x13GetRevenueAnalytics\x122.analytics_service.read.GetRevenueAnalyticsRequest\x1a3.analytics_service.read.GetRevenueAnalyticsResponse\x12~\n" +
	"\x13GetBookingAnalytics\x122.analytics_service.read.GetBookingAnalyticsRequest\x1a3.analytics_service.read.GetBookingAnalyticsResponse\x12u\n" +
	"\x10GetPopularMovies\x12/.analytics_service.read.GetPopularMoviesRequest\x1a0.analytics_service.read.GetPopularMoviesResponse\x12\x84\x01\n" +
	"\x15GetTheatrePerformance\x124.analytics_service.read.GetTheatrePerformanceRequest\x1a5.analytics_service.read.GetTheatrePerformanceResponse\x12\x8a\x01\n" +
	"\x17GetAnalyticsByDateRange\x126.analytics_service.read.GetAnalyticsByDateRangeRequest\x1a7.analytics_service.read.GetAnalyticsByDateRangeResponseBjZhgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/analytics_service/read;analytics_readb\x06proto3"

var (
	file_analytics_service_analytics_read_proto_rawDescOnce sync.Once
	file_analytics_service_analytics_read_proto_rawDescData []byte
)

func file_analytics_service_analytics_read_proto_rawDescGZIP() []byte {
	file_analytics_service_analytics_read_proto_rawDescOnce.Do(func() {
		file_analytics_service_analytics_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_service_analytics_read_proto_rawDesc), len(file_analytics_service_analytics_read_proto_rawDesc)))
	})
	return file_analytics_service_analytics_read_proto_rawDescData
}

var file_analytics_service_analytics_read_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_analytics_service_analytics_read_proto_goTypes = []any{
	(*RevenueAnalytics)(nil),                // 0: analytics_service.read.RevenueAnalytics
	(*BookingAnalytics)(nil),                // 1: analytics_service.read.BookingAnalytics
	(*PopularMovie)(nil),                    // 2: analytics_service.read.PopularMovie
	(*TheatrePerformance)(nil),              // 3: analytics_service.read.TheatrePerformance
	(*AnalyticsSummary)(nil),                // 4: analytics_service.read.AnalyticsSummary
	(*GetRevenueAnalyticsRequest)(nil),      // 5: analytics_service.read.GetRevenueAnalyticsRequest
	(*GetRevenueAnalyticsResponse)(nil),     // 6: analytics_service.read.GetRevenueAnalyticsResponse
	(*GetBookingAnalyticsRequest)(nil),      // 7: analytics_service.read.GetBookingAnalyticsRequest
	(*GetBookingAnalyticsResponse)(nil),     // 8: analytics_service.read.GetBookingAnalyticsResponse
	(*GetPopularMoviesRequest)(nil),         // 9: analytics_service.read.GetPopularMoviesRequest
	(*GetPopularMoviesResponse)(nil),        // 10: analytics_service.read.GetPopularMoviesResponse
	(*GetTheatrePerformanceRequest)(nil),    // 11: analytics_service.read.GetTheatrePerformanceRequest
	(*GetTheatrePerformanceResponse)(nil),   // 12: analytics_service.read.GetTheatrePerformanceResponse
	(*GetAnalyticsByDateRangeRequest)(nil),  // 13: analytics_service.read.GetAnalyticsByDateRangeRequest
	(*GetAnalyticsByDateRangeResponse)(nil), // 14: analytics_service.read.GetAnalyticsByDateRangeResponse
	(*timestamppb.Timestamp)(nil),           // 15: google.protobuf.Timestamp
}
var file_analytics_service_analytics_read_proto_depIdxs = []int32{
	0,  // 0: analytics_service.read.GetRevenueAnalyticsResponse.analytics:type_name -> analytics_service.read.RevenueAnalytics
	1,  // 1: analytics_service.read.GetBookingAnalyticsResponse.analytics:type_name -> analytics_service.read.BookingAnalytics
	2,  // 2: analytics_service.read.GetPopularMoviesResponse.movies:type_name -> analytics_service.read.PopularMovie
	3,  // 3: analytics_service.read.GetTheatrePerformanceResponse.theatres:type_name -> analytics_service.read.TheatrePerformance
	4,  // 4: analytics_service.read.GetAnalyticsByDateRangeResponse.analytics:type_name -> analytics_service.read.AnalyticsSummary
	15, // 5: analytics_service.read.GetAnalyticsByDateRangeResponse.generated_at:type_name -> google.protobuf.Timestamp
	5,  // 6: analytics_service.read.AnalyticsReadService.GetRevenueAnalytics:input_type -> analytics_service.read.GetRevenueAnalyticsRequest
	7,  // 7: analytics_service.read.AnalyticsReadService.GetBookingAnalytics:input_type -> analytics_service.read.GetBookingAnalyticsRequest
	9,  // 8: analytics_service.read.AnalyticsReadService.GetPopularMovies:input_type -> analytics_service.read.GetPopularMoviesRequest
	11, // 9: analytics_service.read.AnalyticsReadService.GetTheatrePerformance:input_type -> analytics_service.read.GetTheatrePerformanceRequest
	13, // 10: analytics_service.read.AnalyticsReadService.GetAnalyticsByDateRange:input_type -> analytics_service.read.GetAnalyticsByDateRangeRequest
	6,  // 11: analytics_service.read.AnalyticsReadService.GetRevenueAnalytics:output_type -> analytics_service.read.GetRevenueAnalyticsResponse
	8,  // 12: analytics_service.read.AnalyticsReadService.GetBookingAnalytics:output_type -> analytics_service.read.GetBookingAnalyticsResponse
	10, // 13: analytics_service.read.AnalyticsReadService.GetPopularMovies:output_type -> analytics_service.read.GetPopularMoviesResponse
	12, // 14: analytics_service.read.AnalyticsReadService.GetTheatrePerformance:output_type -> analytics_service.read.GetTheatrePerformanceResponse
	14, // 15: analytics_service.read.AnalyticsReadService.GetAnalyticsByDateRange:output_type -> analytics_service.read.GetAnalyticsByDateRangeResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_analytics_service_analytics_read_proto_init() }
func file_analytics_service_analytics_read_proto_init() {
	if File_analytics_service_analytics_read_proto != nil {
		return
	}
	file_analytics_service_analytics_read_proto_msgTypes[5].OneofWrappers = []any{}
	file_analytics_service_analytics_read_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_service_analytics_read_proto_rawDesc), len(file_analytics_service_analytics_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_service_analytics_read_proto_goTypes,
		DependencyIndexes: file_analytics_service_analytics_read_proto_depIdxs,
		MessageInfos:      file_analytics_service_analytics_read_proto_msgTypes,
	}.Build()
	File_analytics_service_analytics_read_proto = out.File
	file_analytics_service_analytics_read_proto_goTypes = nil
	file_analytics_service_analytics_read_proto_depIdxs = nil
}
