// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: shedule_service/shedule_write.proto

package schedule_write

import (
	schedule_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/schedule_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie identifier
	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// Theatre identifier
	TheatreId string `protobuf:"bytes,2,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	// Screen identifier
	ScreenId string `protobuf:"bytes,3,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	// Show start time
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Show end time
	EndTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Ticket price
	Price float64 `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	// Total seats
	TotalSeats    uint32 `protobuf:"varint,7,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShowRequest) Reset() {
	*x = CreateShowRequest{}
	mi := &file_shedule_service_shedule_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowRequest) ProtoMessage() {}

func (x *CreateShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowRequest.ProtoReflect.Descriptor instead.
func (*CreateShowRequest) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_write_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShowRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *CreateShowRequest) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

func (x *CreateShowRequest) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *CreateShowRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateShowRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CreateShowRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateShowRequest) GetTotalSeats() uint32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

type CreateShowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created show identifier
	ShowId string `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	// Creation timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShowResponse) Reset() {
	*x = CreateShowResponse{}
	mi := &file_shedule_service_shedule_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowResponse) ProtoMessage() {}

func (x *CreateShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowResponse.ProtoReflect.Descriptor instead.
func (*CreateShowResponse) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_write_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShowResponse) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *CreateShowResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateShowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show identifier
	ShowId string `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	// Show start time
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	// Show end time
	EndTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	// Ticket price
	Price *float64 `protobuf:"fixed64,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	// Show status
	Status        *schedule_service.ShowStatus `protobuf:"varint,5,opt,name=status,proto3,enum=shedule_service.show_status.ShowStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShowRequest) Reset() {
	*x = UpdateShowRequest{}
	mi := &file_shedule_service_shedule_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShowRequest) ProtoMessage() {}

func (x *UpdateShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShowRequest.ProtoReflect.Descriptor instead.
func (*UpdateShowRequest) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_write_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateShowRequest) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *UpdateShowRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateShowRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *UpdateShowRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateShowRequest) GetStatus() schedule_service.ShowStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return schedule_service.ShowStatus(0)
}

type UpdateShowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated show identifier
	ShowId string `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	// Update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShowResponse) Reset() {
	*x = UpdateShowResponse{}
	mi := &file_shedule_service_shedule_write_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShowResponse) ProtoMessage() {}

func (x *UpdateShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_write_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShowResponse.ProtoReflect.Descriptor instead.
func (*UpdateShowResponse) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_write_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateShowResponse) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *UpdateShowResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteShowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show identifier
	ShowId        string `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShowRequest) Reset() {
	*x = DeleteShowRequest{}
	mi := &file_shedule_service_shedule_write_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShowRequest) ProtoMessage() {}

func (x *DeleteShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_write_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShowRequest.ProtoReflect.Descriptor instead.
func (*DeleteShowRequest) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_write_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteShowRequest) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

type DeleteShowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Deletion timestamp
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShowResponse) Reset() {
	*x = DeleteShowResponse{}
	mi := &file_shedule_service_shedule_write_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShowResponse) ProtoMessage() {}

func (x *DeleteShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_write_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShowResponse.ProtoReflect.Descriptor instead.
func (*DeleteShowResponse) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_write_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteShowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteShowResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_shedule_service_shedule_write_proto protoreflect.FileDescriptor

const file_shedule_service_shedule_write_proto_rawDesc = "" +
	"\n" +
	"#shedule_service/shedule_write.proto\x12\x16schedule_service.write\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!shedule_service/show_status.proto\"\x93\x02\n" +
	"\x11CreateShowRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x02 \x01(\tR\ttheatreId\x12\x1b\n" +
	"\tscreen_id\x18\x03 \x01(\tR\bscreenId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1f\n" +
	"\vtotal_seats\x18\a \x01(\rR\n" +
	"totalSeats\"h\n" +
	"\x12CreateShowResponse\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xba\x02\n" +
	"\x11UpdateShowRequest\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x12>\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendTime\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x04 \x01(\x01H\x02R\x05price\x88\x01\x01\x12D\n" +
	"\x06status\x18\x05 \x01(\x0e2'.shedule_service.show_status.ShowStatusH\x03R\x06status\x88\x01\x01B\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_timeB\b\n" +
	"\x06_priceB\t\n" +
	"\a_status\"h\n" +
	"\x12UpdateShowResponse\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x11DeleteShowRequest\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\"i\n" +
	"\x12DeleteShowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt2\xc5\x02\n" +
	"\x14ScheduleWriteService\x12c\n" +
	"\n" +
	"CreateShow\x12).schedule_service.write.CreateShowRequest\x1a*.schedule_service.write.CreateShowResponse\x12c\n" +
	"\n" +
	"UpdateShow\x12).schedule_service.write.UpdateShowRequest\x1a*.schedule_service.write.UpdateShowResponse\x12c\n" +
	"\n" +
	"DeleteShow\x12).schedule_service.write.DeleteShowRequest\x1a*.schedule_service.write.DeleteShowResponseBjZhgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/schedule_service/write;schedule_writeb\x06proto3"

var (
	file_shedule_service_shedule_write_proto_rawDescOnce sync.Once
	file_shedule_service_shedule_write_proto_rawDescData []byte
)

func file_shedule_service_shedule_write_proto_rawDescGZIP() []byte {
	file_shedule_service_shedule_write_proto_rawDescOnce.Do(func() {
		file_shedule_service_shedule_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shedule_service_shedule_write_proto_rawDesc), len(file_shedule_service_shedule_write_proto_rawDesc)))
	})
	return file_shedule_service_shedule_write_proto_rawDescData
}

var file_shedule_service_shedule_write_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shedule_service_shedule_write_proto_goTypes = []any{
	(*CreateShowRequest)(nil),        // 0: schedule_service.write.CreateShowRequest
	(*CreateShowResponse)(nil),       // 1: schedule_service.write.CreateShowResponse
	(*UpdateShowRequest)(nil),        // 2: schedule_service.write.UpdateShowRequest
	(*UpdateShowResponse)(nil),       // 3: schedule_service.write.UpdateShowResponse
	(*DeleteShowRequest)(nil),        // 4: schedule_service.write.DeleteShowRequest
	(*DeleteShowResponse)(nil),       // 5: schedule_service.write.DeleteShowResponse
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
	(schedule_service.ShowStatus)(0), // 7: shedule_service.show_status.ShowStatus
}
var file_shedule_service_shedule_write_proto_depIdxs = []int32{
	6,  // 0: schedule_service.write.CreateShowRequest.start_time:type_name -> google.protobuf.Timestamp
	6,  // 1: schedule_service.write.CreateShowRequest.end_time:type_name -> google.protobuf.Timestamp
	6,  // 2: schedule_service.write.CreateShowResponse.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: schedule_service.write.UpdateShowRequest.start_time:type_name -> google.protobuf.Timestamp
	6,  // 4: schedule_service.write.UpdateShowRequest.end_time:type_name -> google.protobuf.Timestamp
	7,  // 5: schedule_service.write.UpdateShowRequest.status:type_name -> shedule_service.show_status.ShowStatus
	6,  // 6: schedule_service.write.UpdateShowResponse.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 7: schedule_service.write.DeleteShowResponse.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 8: schedule_service.write.ScheduleWriteService.CreateShow:input_type -> schedule_service.write.CreateShowRequest
	2,  // 9: schedule_service.write.ScheduleWriteService.UpdateShow:input_type -> schedule_service.write.UpdateShowRequest
	4,  // 10: schedule_service.write.ScheduleWriteService.DeleteShow:input_type -> schedule_service.write.DeleteShowRequest
	1,  // 11: schedule_service.write.ScheduleWriteService.CreateShow:output_type -> schedule_service.write.CreateShowResponse
	3,  // 12: schedule_service.write.ScheduleWriteService.UpdateShow:output_type -> schedule_service.write.UpdateShowResponse
	5,  // 13: schedule_service.write.ScheduleWriteService.DeleteShow:output_type -> schedule_service.write.DeleteShowResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_shedule_service_shedule_write_proto_init() }
func file_shedule_service_shedule_write_proto_init() {
	if File_shedule_service_shedule_write_proto != nil {
		return
	}
	file_shedule_service_shedule_write_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shedule_service_shedule_write_proto_rawDesc), len(file_shedule_service_shedule_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shedule_service_shedule_write_proto_goTypes,
		DependencyIndexes: file_shedule_service_shedule_write_proto_depIdxs,
		MessageInfos:      file_shedule_service_shedule_write_proto_msgTypes,
	}.Build()
	File_shedule_service_shedule_write_proto = out.File
	file_shedule_service_shedule_write_proto_goTypes = nil
	file_shedule_service_shedule_write_proto_depIdxs = nil
}
