// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: shedule_service/shedule_read.proto

package schedule_read

import (
	schedule_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/schedule_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Show Entity
// |--------------------------------------------------------------------------
type Show struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show identifier
	ShowId string `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	// Movie identifier
	MovieId string `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// Theatre identifier
	TheatreId string `protobuf:"bytes,3,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	// Screen identifier
	ScreenId string `protobuf:"bytes,4,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	// Show start time
	StartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Show end time
	EndTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Ticket price
	Price float64 `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	// Total seats
	TotalSeats uint32 `protobuf:"varint,8,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	// Available seats
	AvailableSeats uint32 `protobuf:"varint,9,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	// Current show status
	Status schedule_service.ShowStatus `protobuf:"varint,10,opt,name=status,proto3,enum=shedule_service.show_status.ShowStatus" json:"status,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Show) Reset() {
	*x = Show{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Show) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Show) ProtoMessage() {}

func (x *Show) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Show.ProtoReflect.Descriptor instead.
func (*Show) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{0}
}

func (x *Show) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *Show) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Show) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

func (x *Show) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *Show) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Show) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Show) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Show) GetTotalSeats() uint32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *Show) GetAvailableSeats() uint32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

func (x *Show) GetStatus() schedule_service.ShowStatus {
	if x != nil {
		return x.Status
	}
	return schedule_service.ShowStatus(0)
}

func (x *Show) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Show) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetShowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination limit
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset
	Offset        uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowsRequest) Reset() {
	*x = GetShowsRequest{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowsRequest) ProtoMessage() {}

func (x *GetShowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowsRequest.ProtoReflect.Descriptor instead.
func (*GetShowsRequest) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{1}
}

func (x *GetShowsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetShowsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetShowsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show list
	Shows []*Show `protobuf:"bytes,1,rep,name=shows,proto3" json:"shows,omitempty"`
	// Total records
	Total uint64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// Pagination limit
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset
	Offset        uint32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowsResponse) Reset() {
	*x = GetShowsResponse{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowsResponse) ProtoMessage() {}

func (x *GetShowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowsResponse.ProtoReflect.Descriptor instead.
func (*GetShowsResponse) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{2}
}

func (x *GetShowsResponse) GetShows() []*Show {
	if x != nil {
		return x.Shows
	}
	return nil
}

func (x *GetShowsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetShowsResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetShowsResponse) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetShowByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show identifier
	ShowId        string `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowByIdRequest) Reset() {
	*x = GetShowByIdRequest{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowByIdRequest) ProtoMessage() {}

func (x *GetShowByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowByIdRequest.ProtoReflect.Descriptor instead.
func (*GetShowByIdRequest) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{3}
}

func (x *GetShowByIdRequest) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

type GetShowByIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show entity
	Show          *Show `protobuf:"bytes,1,opt,name=show,proto3" json:"show,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowByIdResponse) Reset() {
	*x = GetShowByIdResponse{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowByIdResponse) ProtoMessage() {}

func (x *GetShowByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowByIdResponse.ProtoReflect.Descriptor instead.
func (*GetShowByIdResponse) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{4}
}

func (x *GetShowByIdResponse) GetShow() *Show {
	if x != nil {
		return x.Show
	}
	return nil
}

type GetMovieShowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie identifier
	MovieId       string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieShowsRequest) Reset() {
	*x = GetMovieShowsRequest{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieShowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieShowsRequest) ProtoMessage() {}

func (x *GetMovieShowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieShowsRequest.ProtoReflect.Descriptor instead.
func (*GetMovieShowsRequest) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{5}
}

func (x *GetMovieShowsRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetMovieShowsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show list
	Shows         []*Show `protobuf:"bytes,1,rep,name=shows,proto3" json:"shows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieShowsResponse) Reset() {
	*x = GetMovieShowsResponse{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieShowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieShowsResponse) ProtoMessage() {}

func (x *GetMovieShowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieShowsResponse.ProtoReflect.Descriptor instead.
func (*GetMovieShowsResponse) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{6}
}

func (x *GetMovieShowsResponse) GetShows() []*Show {
	if x != nil {
		return x.Shows
	}
	return nil
}

type GetTheatreShowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Theatre identifier
	TheatreId     string `protobuf:"bytes,1,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTheatreShowsRequest) Reset() {
	*x = GetTheatreShowsRequest{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTheatreShowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatreShowsRequest) ProtoMessage() {}

func (x *GetTheatreShowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatreShowsRequest.ProtoReflect.Descriptor instead.
func (*GetTheatreShowsRequest) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{7}
}

func (x *GetTheatreShowsRequest) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

type GetTheatreShowsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show list
	Shows         []*Show `protobuf:"bytes,1,rep,name=shows,proto3" json:"shows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTheatreShowsResponse) Reset() {
	*x = GetTheatreShowsResponse{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTheatreShowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatreShowsResponse) ProtoMessage() {}

func (x *GetTheatreShowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatreShowsResponse.ProtoReflect.Descriptor instead.
func (*GetTheatreShowsResponse) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{8}
}

func (x *GetTheatreShowsResponse) GetShows() []*Show {
	if x != nil {
		return x.Shows
	}
	return nil
}

type GetShowsByDateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Date
	//
	// Format:
	// YYYY-MM-DD
	Date          string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowsByDateRequest) Reset() {
	*x = GetShowsByDateRequest{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowsByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowsByDateRequest) ProtoMessage() {}

func (x *GetShowsByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowsByDateRequest.ProtoReflect.Descriptor instead.
func (*GetShowsByDateRequest) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{9}
}

func (x *GetShowsByDateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetShowsByDateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show list
	Shows         []*Show `protobuf:"bytes,1,rep,name=shows,proto3" json:"shows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowsByDateResponse) Reset() {
	*x = GetShowsByDateResponse{}
	mi := &file_shedule_service_shedule_read_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowsByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowsByDateResponse) ProtoMessage() {}

func (x *GetShowsByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shedule_service_shedule_read_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowsByDateResponse.ProtoReflect.Descriptor instead.
func (*GetShowsByDateResponse) Descriptor() ([]byte, []int) {
	return file_shedule_service_shedule_read_proto_rawDescGZIP(), []int{10}
}

func (x *GetShowsByDateResponse) GetShows() []*Show {
	if x != nil {
		return x.Shows
	}
	return nil
}

var File_shedule_service_shedule_read_proto protoreflect.FileDescriptor

const file_shedule_service_shedule_read_proto_rawDesc = "" +
	"\n" +
	"\"shedule_service/shedule_read.proto\x12\x15schedule_service.read\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!shedule_service/show_status.proto\"\xff\x03\n" +
	"\x04Show\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x03 \x01(\tR\ttheatreId\x12\x1b\n" +
	"\tscreen_id\x18\x04 \x01(\tR\bscreenId\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1f\n" +
	"\vtotal_seats\x18\b \x01(\rR\n" +
	"totalSeats\x12'\n" +
	"\x0favailable_seats\x18\t \x01(\rR\x0eavailableSeats\x12?\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2'.shedule_service.show_status.ShowStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"?\n" +
	"\x0fGetShowsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"\x89\x01\n" +
	"\x10GetShowsResponse\x121\n" +
	"\x05shows\x18\x01 \x03(\v2\x1b.schedule_service.read.ShowR\x05shows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"-\n" +
	"\x12GetShowByIdRequest\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\"F\n" +
	"\x13GetShowByIdResponse\x12/\n" +
	"\x04show\x18\x01 \x01(\v2\x1b.schedule_service.read.ShowR\x04show\"1\n" +
	"\x14GetMovieShowsRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"J\n" +
	"\x15GetMovieShowsResponse\x121\n" +
	"\x05shows\x18\x01 \x03(\v2\x1b.schedule_service.read.ShowR\x05shows\"7\n" +
	"\x16GetTheatreShowsRequest\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x01 \x01(\tR\ttheatreId\"L\n" +
	"\x17GetTheatreShowsResponse\x121\n" +
	"\x05shows\x18\x01 \x03(\v2\x1b.schedule_service.read.ShowR\x05shows\"+\n" +
	"\x15GetShowsByDateRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"K\n" +
	"\x16GetShowsByDateResponse\x121\n" +
	"\x05shows\x18\x01 \x03(\v2\x1b.schedule_service.read.ShowR\x05shows2\xa5\x04\n" +
	"\x13ScheduleReadService\x12[\n" +
	"\bGetShows\x12&.schedule_service.read.GetShowsRequest\x1a'.schedule_service.read.GetShowsResponse\x12d\n" +
	"\vGetShowById\x12).schedule_service.read.GetShowByIdRequest\x1a*.schedule_service.read.GetShowByIdResponse\x12j\n" +
	"\rGetMovieShows\x12+.schedule_service.read.GetMovieShowsRequest\x1a,.schedule_service.read.GetMovieShowsResponse\x12p\n" +
	"\x0fGetTheatreShows\x12-.schedule_service.read.GetTheatreShowsRequest\x1a..schedule_service.read.GetTheatreShowsResponse\x12m\n" +
	"\x0eGetShowsByDate\x12,.schedule_service.read.GetShowsByDateRequest\x1a-.schedule_service.read.GetShowsByDateResponseBhZfgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/schedule_service/read;schedule_readb\x06proto3"

var (
	file_shedule_service_shedule_read_proto_rawDescOnce sync.Once
	file_shedule_service_shedule_read_proto_rawDescData []byte
)

func file_shedule_service_shedule_read_proto_rawDescGZIP() []byte {
	file_shedule_service_shedule_read_proto_rawDescOnce.Do(func() {
		file_shedule_service_shedule_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shedule_service_shedule_read_proto_rawDesc), len(file_shedule_service_shedule_read_proto_rawDesc)))
	})
	return file_shedule_service_shedule_read_proto_rawDescData
}

var file_shedule_service_shedule_read_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shedule_service_shedule_read_proto_goTypes = []any{
	(*Show)(nil),                     // 0: schedule_service.read.Show
	(*GetShowsRequest)(nil),          // 1: schedule_service.read.GetShowsRequest
	(*GetShowsResponse)(nil),         // 2: schedule_service.read.GetShowsResponse
	(*GetShowByIdRequest)(nil),       // 3: schedule_service.read.GetShowByIdRequest
	(*GetShowByIdResponse)(nil),      // 4: schedule_service.read.GetShowByIdResponse
	(*GetMovieShowsRequest)(nil),     // 5: schedule_service.read.GetMovieShowsRequest
	(*GetMovieShowsResponse)(nil),    // 6: schedule_service.read.GetMovieShowsResponse
	(*GetTheatreShowsRequest)(nil),   // 7: schedule_service.read.GetTheatreShowsRequest
	(*GetTheatreShowsResponse)(nil),  // 8: schedule_service.read.GetTheatreShowsResponse
	(*GetShowsByDateRequest)(nil),    // 9: schedule_service.read.GetShowsByDateRequest
	(*GetShowsByDateResponse)(nil),   // 10: schedule_service.read.GetShowsByDateResponse
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(schedule_service.ShowStatus)(0), // 12: shedule_service.show_status.ShowStatus
}
var file_shedule_service_shedule_read_proto_depIdxs = []int32{
	11, // 0: schedule_service.read.Show.start_time:type_name -> google.protobuf.Timestamp
	11, // 1: schedule_service.read.Show.end_time:type_name -> google.protobuf.Timestamp
	12, // 2: schedule_service.read.Show.status:type_name -> shedule_service.show_status.ShowStatus
	11, // 3: schedule_service.read.Show.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: schedule_service.read.Show.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: schedule_service.read.GetShowsResponse.shows:type_name -> schedule_service.read.Show
	0,  // 6: schedule_service.read.GetShowByIdResponse.show:type_name -> schedule_service.read.Show
	0,  // 7: schedule_service.read.GetMovieShowsResponse.shows:type_name -> schedule_service.read.Show
	0,  // 8: schedule_service.read.GetTheatreShowsResponse.shows:type_name -> schedule_service.read.Show
	0,  // 9: schedule_service.read.GetShowsByDateResponse.shows:type_name -> schedule_service.read.Show
	1,  // 10: schedule_service.read.ScheduleReadService.GetShows:input_type -> schedule_service.read.GetShowsRequest
	3,  // 11: schedule_service.read.ScheduleReadService.GetShowById:input_type -> schedule_service.read.GetShowByIdRequest
	5,  // 12: schedule_service.read.ScheduleReadService.GetMovieShows:input_type -> schedule_service.read.GetMovieShowsRequest
	7,  // 13: schedule_service.read.ScheduleReadService.GetTheatreShows:input_type -> schedule_service.read.GetTheatreShowsRequest
	9,  // 14: schedule_service.read.ScheduleReadService.GetShowsByDate:input_type -> schedule_service.read.GetShowsByDateRequest
	2,  // 15: schedule_service.read.ScheduleReadService.GetShows:output_type -> schedule_service.read.GetShowsResponse
	4,  // 16: schedule_service.read.ScheduleReadService.GetShowById:output_type -> schedule_service.read.GetShowByIdResponse
	6,  // 17: schedule_service.read.ScheduleReadService.GetMovieShows:output_type -> schedule_service.read.GetMovieShowsResponse
	8,  // 18: schedule_service.read.ScheduleReadService.GetTheatreShows:output_type -> schedule_service.read.GetTheatreShowsResponse
	10, // 19: schedule_service.read.ScheduleReadService.GetShowsByDate:output_type -> schedule_service.read.GetShowsByDateResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_shedule_service_shedule_read_proto_init() }
func file_shedule_service_shedule_read_proto_init() {
	if File_shedule_service_shedule_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shedule_service_shedule_read_proto_rawDesc), len(file_shedule_service_shedule_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shedule_service_shedule_read_proto_goTypes,
		DependencyIndexes: file_shedule_service_shedule_read_proto_depIdxs,
		MessageInfos:      file_shedule_service_shedule_read_proto_msgTypes,
	}.Build()
	File_shedule_service_shedule_read_proto = out.File
	file_shedule_service_shedule_read_proto_goTypes = nil
	file_shedule_service_shedule_read_proto_depIdxs = nil
}
