// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: shedule_service/show_status.proto

package show_status

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Show Status
// |--------------------------------------------------------------------------
type ShowStatus int32

const (
	ShowStatus_SHOW_STATUS_UNSPECIFIED ShowStatus = 0
	ShowStatus_SHOW_STATUS_SCHEDULED   ShowStatus = 1
	ShowStatus_SHOW_STATUS_RUNNING     ShowStatus = 2
	ShowStatus_SHOW_STATUS_COMPLETED   ShowStatus = 3
	ShowStatus_SHOW_STATUS_CANCELLED   ShowStatus = 4
)

// Enum value maps for ShowStatus.
var (
	ShowStatus_name = map[int32]string{
		0: "SHOW_STATUS_UNSPECIFIED",
		1: "SHOW_STATUS_SCHEDULED",
		2: "SHOW_STATUS_RUNNING",
		3: "SHOW_STATUS_COMPLETED",
		4: "SHOW_STATUS_CANCELLED",
	}
	ShowStatus_value = map[string]int32{
		"SHOW_STATUS_UNSPECIFIED": 0,
		"SHOW_STATUS_SCHEDULED":   1,
		"SHOW_STATUS_RUNNING":     2,
		"SHOW_STATUS_COMPLETED":   3,
		"SHOW_STATUS_CANCELLED":   4,
	}
)

func (x ShowStatus) Enum() *ShowStatus {
	p := new(ShowStatus)
	*p = x
	return p
}

func (x ShowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shedule_service_show_status_proto_enumTypes[0].Descriptor()
}

func (ShowStatus) Type() protoreflect.EnumType {
	return &file_shedule_service_show_status_proto_enumTypes[0]
}

func (x ShowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShowStatus.Descriptor instead.
func (ShowStatus) EnumDescriptor() ([]byte, []int) {
	return file_shedule_service_show_status_proto_rawDescGZIP(), []int{0}
}

var File_shedule_service_show_status_proto protoreflect.FileDescriptor

const file_shedule_service_show_status_proto_rawDesc = "" +
	"\n" +
	"!shedule_service/show_status.proto\x12\x1bshedule_service.show_status*\x93\x01\n" +
	"\n" +
	"ShowStatus\x12\x1b\n" +
	"\x17SHOW_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SHOW_STATUS_SCHEDULED\x10\x01\x12\x17\n" +
	"\x13SHOW_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15SHOW_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15SHOW_STATUS_CANCELLED\x10\x04BbZ`github.com/movie-reservation-system-ms/movie_reservation_proto_lib/schedule_service/;show_statusb\x06proto3"

var (
	file_shedule_service_show_status_proto_rawDescOnce sync.Once
	file_shedule_service_show_status_proto_rawDescData []byte
)

func file_shedule_service_show_status_proto_rawDescGZIP() []byte {
	file_shedule_service_show_status_proto_rawDescOnce.Do(func() {
		file_shedule_service_show_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shedule_service_show_status_proto_rawDesc), len(file_shedule_service_show_status_proto_rawDesc)))
	})
	return file_shedule_service_show_status_proto_rawDescData
}

var file_shedule_service_show_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shedule_service_show_status_proto_goTypes = []any{
	(ShowStatus)(0), // 0: shedule_service.show_status.ShowStatus
}
var file_shedule_service_show_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shedule_service_show_status_proto_init() }
func file_shedule_service_show_status_proto_init() {
	if File_shedule_service_show_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shedule_service_show_status_proto_rawDesc), len(file_shedule_service_show_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shedule_service_show_status_proto_goTypes,
		DependencyIndexes: file_shedule_service_show_status_proto_depIdxs,
		EnumInfos:         file_shedule_service_show_status_proto_enumTypes,
	}.Build()
	File_shedule_service_show_status_proto = out.File
	file_shedule_service_show_status_proto_goTypes = nil
	file_shedule_service_show_status_proto_depIdxs = nil
}
