// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: booking_service/booking_read.proto

package booking_read

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookingReadService_GetBookingById_FullMethodName = "/booking_service.read.BookingReadService/GetBookingById"
	BookingReadService_GetBookings_FullMethodName    = "/booking_service.read.BookingReadService/GetBookings"
)

// BookingReadServiceClient is the client API for BookingReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingReadServiceClient interface {
	// |--------------------------------------------------------------------------
	// | Get Booking By ID
	// |--------------------------------------------------------------------------
	// |
	// | Fetch a single booking using booking ID.
	// |
	// | REST:
	// | GET /booking/{id}
	// |
	GetBookingById(ctx context.Context, in *GetBookingByIdRequest, opts ...grpc.CallOption) (*GetBookingByIdResponse, error)
	// |--------------------------------------------------------------------------
	// | Get User Bookings
	// |--------------------------------------------------------------------------
	// |
	// | Fetch all bookings for authenticated user.
	// |
	// | REST:
	// | GET /booking/
	// |
	GetBookings(ctx context.Context, in *GetBookingsRequest, opts ...grpc.CallOption) (*GetBookingsResponse, error)
}

type bookingReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingReadServiceClient(cc grpc.ClientConnInterface) BookingReadServiceClient {
	return &bookingReadServiceClient{cc}
}

func (c *bookingReadServiceClient) GetBookingById(ctx context.Context, in *GetBookingByIdRequest, opts ...grpc.CallOption) (*GetBookingByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBookingByIdResponse)
	err := c.cc.Invoke(ctx, BookingReadService_GetBookingById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingReadServiceClient) GetBookings(ctx context.Context, in *GetBookingsRequest, opts ...grpc.CallOption) (*GetBookingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBookingsResponse)
	err := c.cc.Invoke(ctx, BookingReadService_GetBookings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingReadServiceServer is the server API for BookingReadService service.
// All implementations must embed UnimplementedBookingReadServiceServer
// for forward compatibility.
type BookingReadServiceServer interface {
	// |--------------------------------------------------------------------------
	// | Get Booking By ID
	// |--------------------------------------------------------------------------
	// |
	// | Fetch a single booking using booking ID.
	// |
	// | REST:
	// | GET /booking/{id}
	// |
	GetBookingById(context.Context, *GetBookingByIdRequest) (*GetBookingByIdResponse, error)
	// |--------------------------------------------------------------------------
	// | Get User Bookings
	// |--------------------------------------------------------------------------
	// |
	// | Fetch all bookings for authenticated user.
	// |
	// | REST:
	// | GET /booking/
	// |
	GetBookings(context.Context, *GetBookingsRequest) (*GetBookingsResponse, error)
	mustEmbedUnimplementedBookingReadServiceServer()
}

// UnimplementedBookingReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookingReadServiceServer struct{}

func (UnimplementedBookingReadServiceServer) GetBookingById(context.Context, *GetBookingByIdRequest) (*GetBookingByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookingById not implemented")
}
func (UnimplementedBookingReadServiceServer) GetBookings(context.Context, *GetBookingsRequest) (*GetBookingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookings not implemented")
}
func (UnimplementedBookingReadServiceServer) mustEmbedUnimplementedBookingReadServiceServer() {}
func (UnimplementedBookingReadServiceServer) testEmbeddedByValue()                            {}

// UnsafeBookingReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingReadServiceServer will
// result in compilation errors.
type UnsafeBookingReadServiceServer interface {
	mustEmbedUnimplementedBookingReadServiceServer()
}

func RegisterBookingReadServiceServer(s grpc.ServiceRegistrar, srv BookingReadServiceServer) {
	// If the following call panics, it indicates UnimplementedBookingReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookingReadService_ServiceDesc, srv)
}

func _BookingReadService_GetBookingById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingReadServiceServer).GetBookingById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingReadService_GetBookingById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingReadServiceServer).GetBookingById(ctx, req.(*GetBookingByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingReadService_GetBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingReadServiceServer).GetBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingReadService_GetBookings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingReadServiceServer).GetBookings(ctx, req.(*GetBookingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingReadService_ServiceDesc is the grpc.ServiceDesc for BookingReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booking_service.read.BookingReadService",
	HandlerType: (*BookingReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookingById",
			Handler:    _BookingReadService_GetBookingById_Handler,
		},
		{
			MethodName: "GetBookings",
			Handler:    _BookingReadService_GetBookings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking_service/booking_read.proto",
}
