// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: booking_service/booking_write.proto

package booking_write

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookingWriteService_InitiateBooking_FullMethodName = "/booking_service.write.BookingWriteService/InitiateBooking"
	BookingWriteService_LockSeats_FullMethodName       = "/booking_service.write.BookingWriteService/LockSeats"
	BookingWriteService_ConfirmBooking_FullMethodName  = "/booking_service.write.BookingWriteService/ConfirmBooking"
	BookingWriteService_CancelBooking_FullMethodName   = "/booking_service.write.BookingWriteService/CancelBooking"
)

// BookingWriteServiceClient is the client API for BookingWriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingWriteServiceClient interface {
	// |--------------------------------------------------------------------------
	// | Initiate Booking
	// |--------------------------------------------------------------------------
	// |
	// | Starts booking workflow.
	// |
	// | Validations:
	// | - Movie exists
	// | - Schedule exists
	// | - Seats available
	// |
	// | REST:
	// | POST /booking/initiate
	// |
	InitiateBooking(ctx context.Context, in *InitiateBookingRequest, opts ...grpc.CallOption) (*InitiateBookingResponse, error)
	// |--------------------------------------------------------------------------
	// | Lock Seats
	// |--------------------------------------------------------------------------
	// |
	// | Temporarily locks seats before payment.
	// |
	// | REST:
	// | POST /booking/lock-seats
	// |
	LockSeats(ctx context.Context, in *LockSeatsRequest, opts ...grpc.CallOption) (*LockSeatsResponse, error)
	// |--------------------------------------------------------------------------
	// | Confirm Booking
	// |--------------------------------------------------------------------------
	// |
	// | Confirms booking after successful payment.
	// |
	// | REST:
	// | POST /booking/confirm
	// |
	ConfirmBooking(ctx context.Context, in *ConfirmBookingRequest, opts ...grpc.CallOption) (*ConfirmBookingResponse, error)
	// |--------------------------------------------------------------------------
	// | Cancel Booking
	// |--------------------------------------------------------------------------
	// |
	// | Cancels existing booking.
	// |
	// | REST:
	// | POST /booking/cancel
	// |
	CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*CancelBookingResponse, error)
}

type bookingWriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingWriteServiceClient(cc grpc.ClientConnInterface) BookingWriteServiceClient {
	return &bookingWriteServiceClient{cc}
}

func (c *bookingWriteServiceClient) InitiateBooking(ctx context.Context, in *InitiateBookingRequest, opts ...grpc.CallOption) (*InitiateBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateBookingResponse)
	err := c.cc.Invoke(ctx, BookingWriteService_InitiateBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingWriteServiceClient) LockSeats(ctx context.Context, in *LockSeatsRequest, opts ...grpc.CallOption) (*LockSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockSeatsResponse)
	err := c.cc.Invoke(ctx, BookingWriteService_LockSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingWriteServiceClient) ConfirmBooking(ctx context.Context, in *ConfirmBookingRequest, opts ...grpc.CallOption) (*ConfirmBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmBookingResponse)
	err := c.cc.Invoke(ctx, BookingWriteService_ConfirmBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingWriteServiceClient) CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*CancelBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelBookingResponse)
	err := c.cc.Invoke(ctx, BookingWriteService_CancelBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingWriteServiceServer is the server API for BookingWriteService service.
// All implementations must embed UnimplementedBookingWriteServiceServer
// for forward compatibility.
type BookingWriteServiceServer interface {
	// |--------------------------------------------------------------------------
	// | Initiate Booking
	// |--------------------------------------------------------------------------
	// |
	// | Starts booking workflow.
	// |
	// | Validations:
	// | - Movie exists
	// | - Schedule exists
	// | - Seats available
	// |
	// | REST:
	// | POST /booking/initiate
	// |
	InitiateBooking(context.Context, *InitiateBookingRequest) (*InitiateBookingResponse, error)
	// |--------------------------------------------------------------------------
	// | Lock Seats
	// |--------------------------------------------------------------------------
	// |
	// | Temporarily locks seats before payment.
	// |
	// | REST:
	// | POST /booking/lock-seats
	// |
	LockSeats(context.Context, *LockSeatsRequest) (*LockSeatsResponse, error)
	// |--------------------------------------------------------------------------
	// | Confirm Booking
	// |--------------------------------------------------------------------------
	// |
	// | Confirms booking after successful payment.
	// |
	// | REST:
	// | POST /booking/confirm
	// |
	ConfirmBooking(context.Context, *ConfirmBookingRequest) (*ConfirmBookingResponse, error)
	// |--------------------------------------------------------------------------
	// | Cancel Booking
	// |--------------------------------------------------------------------------
	// |
	// | Cancels existing booking.
	// |
	// | REST:
	// | POST /booking/cancel
	// |
	CancelBooking(context.Context, *CancelBookingRequest) (*CancelBookingResponse, error)
	mustEmbedUnimplementedBookingWriteServiceServer()
}

// UnimplementedBookingWriteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookingWriteServiceServer struct{}

func (UnimplementedBookingWriteServiceServer) InitiateBooking(context.Context, *InitiateBookingRequest) (*InitiateBookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateBooking not implemented")
}
func (UnimplementedBookingWriteServiceServer) LockSeats(context.Context, *LockSeatsRequest) (*LockSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockSeats not implemented")
}
func (UnimplementedBookingWriteServiceServer) ConfirmBooking(context.Context, *ConfirmBookingRequest) (*ConfirmBookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmBooking not implemented")
}
func (UnimplementedBookingWriteServiceServer) CancelBooking(context.Context, *CancelBookingRequest) (*CancelBookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBooking not implemented")
}
func (UnimplementedBookingWriteServiceServer) mustEmbedUnimplementedBookingWriteServiceServer() {}
func (UnimplementedBookingWriteServiceServer) testEmbeddedByValue()                             {}

// UnsafeBookingWriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingWriteServiceServer will
// result in compilation errors.
type UnsafeBookingWriteServiceServer interface {
	mustEmbedUnimplementedBookingWriteServiceServer()
}

func RegisterBookingWriteServiceServer(s grpc.ServiceRegistrar, srv BookingWriteServiceServer) {
	// If the following call panics, it indicates UnimplementedBookingWriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookingWriteService_ServiceDesc, srv)
}

func _BookingWriteService_InitiateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingWriteServiceServer).InitiateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingWriteService_InitiateBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingWriteServiceServer).InitiateBooking(ctx, req.(*InitiateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingWriteService_LockSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingWriteServiceServer).LockSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingWriteService_LockSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingWriteServiceServer).LockSeats(ctx, req.(*LockSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingWriteService_ConfirmBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingWriteServiceServer).ConfirmBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingWriteService_ConfirmBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingWriteServiceServer).ConfirmBooking(ctx, req.(*ConfirmBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingWriteService_CancelBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingWriteServiceServer).CancelBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingWriteService_CancelBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingWriteServiceServer).CancelBooking(ctx, req.(*CancelBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingWriteService_ServiceDesc is the grpc.ServiceDesc for BookingWriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingWriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booking_service.write.BookingWriteService",
	HandlerType: (*BookingWriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateBooking",
			Handler:    _BookingWriteService_InitiateBooking_Handler,
		},
		{
			MethodName: "LockSeats",
			Handler:    _BookingWriteService_LockSeats_Handler,
		},
		{
			MethodName: "ConfirmBooking",
			Handler:    _BookingWriteService_ConfirmBooking_Handler,
		},
		{
			MethodName: "CancelBooking",
			Handler:    _BookingWriteService_CancelBooking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking_service/booking_write.proto",
}
