// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: booking_service/booking_write.proto

package booking_write

import (
	common "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/booking_service/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateBookingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Movie identifier
	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// Theatre identifier
	TheatreId string `protobuf:"bytes,2,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	// Schedule identifier
	ScheduleId string `protobuf:"bytes,3,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	// Requested seat identifiers
	SeatIds       []string `protobuf:"bytes,4,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateBookingRequest) Reset() {
	*x = InitiateBookingRequest{}
	mi := &file_booking_service_booking_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateBookingRequest) ProtoMessage() {}

func (x *InitiateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_booking_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateBookingRequest.ProtoReflect.Descriptor instead.
func (*InitiateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_booking_write_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateBookingRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *InitiateBookingRequest) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

func (x *InitiateBookingRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *InitiateBookingRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type InitiateBookingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Temporary booking identifier
	BookingId string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	// Booking status
	Status common.BookingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=booking_service.status.BookingStatus" json:"status,omitempty"`
	// Seat lock expiration timestamp
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateBookingResponse) Reset() {
	*x = InitiateBookingResponse{}
	mi := &file_booking_service_booking_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateBookingResponse) ProtoMessage() {}

func (x *InitiateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_booking_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateBookingResponse.ProtoReflect.Descriptor instead.
func (*InitiateBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_booking_write_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *InitiateBookingResponse) GetStatus() common.BookingStatus {
	if x != nil {
		return x.Status
	}
	return common.BookingStatus(0)
}

func (x *InitiateBookingResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type LockSeatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Booking identifier
	BookingId string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	// Seat identifiers
	SeatIds       []string `protobuf:"bytes,2,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockSeatsRequest) Reset() {
	*x = LockSeatsRequest{}
	mi := &file_booking_service_booking_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockSeatsRequest) ProtoMessage() {}

func (x *LockSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_booking_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockSeatsRequest.ProtoReflect.Descriptor instead.
func (*LockSeatsRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_booking_write_proto_rawDescGZIP(), []int{2}
}

func (x *LockSeatsRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *LockSeatsRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type LockSeatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Booking status
	Status common.BookingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=booking_service.status.BookingStatus" json:"status,omitempty"`
	// Seat lock expiration timestamp
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockSeatsResponse) Reset() {
	*x = LockSeatsResponse{}
	mi := &file_booking_service_booking_write_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockSeatsResponse) ProtoMessage() {}

func (x *LockSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_booking_write_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockSeatsResponse.ProtoReflect.Descriptor instead.
func (*LockSeatsResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_booking_write_proto_rawDescGZIP(), []int{3}
}

func (x *LockSeatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LockSeatsResponse) GetStatus() common.BookingStatus {
	if x != nil {
		return x.Status
	}
	return common.BookingStatus(0)
}

func (x *LockSeatsResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ConfirmBookingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Booking identifier
	BookingId string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	// Payment transaction identifier
	PaymentId     string `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingRequest) Reset() {
	*x = ConfirmBookingRequest{}
	mi := &file_booking_service_booking_write_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingRequest) ProtoMessage() {}

func (x *ConfirmBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_booking_write_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_booking_write_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ConfirmBookingRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type ConfirmBookingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Booking identifier
	BookingId string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	// Booking status
	Status common.BookingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=booking_service.status.BookingStatus" json:"status,omitempty"`
	// Confirmation timestamp
	ConfirmedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingResponse) Reset() {
	*x = ConfirmBookingResponse{}
	mi := &file_booking_service_booking_write_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingResponse) ProtoMessage() {}

func (x *ConfirmBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_booking_write_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_booking_write_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ConfirmBookingResponse) GetStatus() common.BookingStatus {
	if x != nil {
		return x.Status
	}
	return common.BookingStatus(0)
}

func (x *ConfirmBookingResponse) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

type CancelBookingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Booking identifier
	BookingId string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	// Cancellation reason
	Reason        *string `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_booking_service_booking_write_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_booking_write_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_booking_write_proto_rawDescGZIP(), []int{6}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CancelBookingRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type CancelBookingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Booking status
	Status common.BookingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=booking_service.status.BookingStatus" json:"status,omitempty"`
	// Cancellation timestamp
	CancelledAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_booking_service_booking_write_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_booking_write_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_booking_write_proto_rawDescGZIP(), []int{7}
}

func (x *CancelBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelBookingResponse) GetStatus() common.BookingStatus {
	if x != nil {
		return x.Status
	}
	return common.BookingStatus(0)
}

func (x *CancelBookingResponse) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

var File_booking_service_booking_write_proto protoreflect.FileDescriptor

const file_booking_service_booking_write_proto_rawDesc = "" +
	"\n" +
	"#booking_service/booking_write.proto\x12\x15booking_service.write\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$booking_service/booking_status.proto\"\x8e\x01\n" +
	"\x16InitiateBookingRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x02 \x01(\tR\ttheatreId\x12\x1f\n" +
	"\vschedule_id\x18\x03 \x01(\tR\n" +
	"scheduleId\x12\x19\n" +
	"\bseat_ids\x18\x04 \x03(\tR\aseatIds\"\xb2\x01\n" +
	"\x17InitiateBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.booking_service.status.BookingStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"L\n" +
	"\x10LockSeatsRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x19\n" +
	"\bseat_ids\x18\x02 \x03(\tR\aseatIds\"\xa7\x01\n" +
	"\x11LockSeatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.booking_service.status.BookingStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"U\n" +
	"\x15ConfirmBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"\xb5\x01\n" +
	"\x16ConfirmBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.booking_service.status.BookingStatusR\x06status\x12=\n" +
	"\fconfirmed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\"]\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\xaf\x01\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.booking_service.status.BookingStatusR\x06status\x12=\n" +
	"\fcancelled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt2\xc2\x03\n" +
	"\x13BookingWriteService\x12p\n" +
	"\x0fInitiateBooking\x12-.booking_service.write.InitiateBookingRequest\x1a..booking_service.write.InitiateBookingResponse\x12^\n" +
	"\tLockSeats\x12'.booking_service.write.LockSeatsRequest\x1a(.booking_service.write.LockSeatsResponse\x12m\n" +
	"\x0eConfirmBooking\x12,.booking_service.write.ConfirmBookingRequest\x1a-.booking_service.write.ConfirmBookingResponse\x12j\n" +
	"\rCancelBooking\x12+.booking_service.write.CancelBookingRequest\x1a,.booking_service.write.CancelBookingResponseBhZfgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/booking_service/write;booking_writeb\x06proto3"

var (
	file_booking_service_booking_write_proto_rawDescOnce sync.Once
	file_booking_service_booking_write_proto_rawDescData []byte
)

func file_booking_service_booking_write_proto_rawDescGZIP() []byte {
	file_booking_service_booking_write_proto_rawDescOnce.Do(func() {
		file_booking_service_booking_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_service_booking_write_proto_rawDesc), len(file_booking_service_booking_write_proto_rawDesc)))
	})
	return file_booking_service_booking_write_proto_rawDescData
}

var file_booking_service_booking_write_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_booking_service_booking_write_proto_goTypes = []any{
	(*InitiateBookingRequest)(nil),  // 0: booking_service.write.InitiateBookingRequest
	(*InitiateBookingResponse)(nil), // 1: booking_service.write.InitiateBookingResponse
	(*LockSeatsRequest)(nil),        // 2: booking_service.write.LockSeatsRequest
	(*LockSeatsResponse)(nil),       // 3: booking_service.write.LockSeatsResponse
	(*ConfirmBookingRequest)(nil),   // 4: booking_service.write.ConfirmBookingRequest
	(*ConfirmBookingResponse)(nil),  // 5: booking_service.write.ConfirmBookingResponse
	(*CancelBookingRequest)(nil),    // 6: booking_service.write.CancelBookingRequest
	(*CancelBookingResponse)(nil),   // 7: booking_service.write.CancelBookingResponse
	(common.BookingStatus)(0),       // 8: booking_service.status.BookingStatus
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_booking_service_booking_write_proto_depIdxs = []int32{
	8,  // 0: booking_service.write.InitiateBookingResponse.status:type_name -> booking_service.status.BookingStatus
	9,  // 1: booking_service.write.InitiateBookingResponse.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 2: booking_service.write.LockSeatsResponse.status:type_name -> booking_service.status.BookingStatus
	9,  // 3: booking_service.write.LockSeatsResponse.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 4: booking_service.write.ConfirmBookingResponse.status:type_name -> booking_service.status.BookingStatus
	9,  // 5: booking_service.write.ConfirmBookingResponse.confirmed_at:type_name -> google.protobuf.Timestamp
	8,  // 6: booking_service.write.CancelBookingResponse.status:type_name -> booking_service.status.BookingStatus
	9,  // 7: booking_service.write.CancelBookingResponse.cancelled_at:type_name -> google.protobuf.Timestamp
	0,  // 8: booking_service.write.BookingWriteService.InitiateBooking:input_type -> booking_service.write.InitiateBookingRequest
	2,  // 9: booking_service.write.BookingWriteService.LockSeats:input_type -> booking_service.write.LockSeatsRequest
	4,  // 10: booking_service.write.BookingWriteService.ConfirmBooking:input_type -> booking_service.write.ConfirmBookingRequest
	6,  // 11: booking_service.write.BookingWriteService.CancelBooking:input_type -> booking_service.write.CancelBookingRequest
	1,  // 12: booking_service.write.BookingWriteService.InitiateBooking:output_type -> booking_service.write.InitiateBookingResponse
	3,  // 13: booking_service.write.BookingWriteService.LockSeats:output_type -> booking_service.write.LockSeatsResponse
	5,  // 14: booking_service.write.BookingWriteService.ConfirmBooking:output_type -> booking_service.write.ConfirmBookingResponse
	7,  // 15: booking_service.write.BookingWriteService.CancelBooking:output_type -> booking_service.write.CancelBookingResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_booking_service_booking_write_proto_init() }
func file_booking_service_booking_write_proto_init() {
	if File_booking_service_booking_write_proto != nil {
		return
	}
	file_booking_service_booking_write_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_service_booking_write_proto_rawDesc), len(file_booking_service_booking_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_service_booking_write_proto_goTypes,
		DependencyIndexes: file_booking_service_booking_write_proto_depIdxs,
		MessageInfos:      file_booking_service_booking_write_proto_msgTypes,
	}.Build()
	File_booking_service_booking_write_proto = out.File
	file_booking_service_booking_write_proto_goTypes = nil
	file_booking_service_booking_write_proto_depIdxs = nil
}
