// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: theatre_service/theatre_screen_type.proto

package screen_type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScreenType int32

const (
	ScreenType_IMAX   ScreenType = 0
	ScreenType_ThreeD ScreenType = 1
	ScreenType_TwoD   ScreenType = 2
)

// Enum value maps for ScreenType.
var (
	ScreenType_name = map[int32]string{
		0: "IMAX",
		1: "ThreeD",
		2: "TwoD",
	}
	ScreenType_value = map[string]int32{
		"IMAX":   0,
		"ThreeD": 1,
		"TwoD":   2,
	}
)

func (x ScreenType) Enum() *ScreenType {
	p := new(ScreenType)
	*p = x
	return p
}

func (x ScreenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScreenType) Descriptor() protoreflect.EnumDescriptor {
	return file_theatre_service_theatre_screen_type_proto_enumTypes[0].Descriptor()
}

func (ScreenType) Type() protoreflect.EnumType {
	return &file_theatre_service_theatre_screen_type_proto_enumTypes[0]
}

func (x ScreenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScreenType.Descriptor instead.
func (ScreenType) EnumDescriptor() ([]byte, []int) {
	return file_theatre_service_theatre_screen_type_proto_rawDescGZIP(), []int{0}
}

var File_theatre_service_theatre_screen_type_proto protoreflect.FileDescriptor

const file_theatre_service_theatre_screen_type_proto_rawDesc = "" +
	"\n" +
	")theatre_service/theatre_screen_type.proto\x12\x1btheatre_service.screen_type*,\n" +
	"\n" +
	"ScreenType\x12\b\n" +
	"\x04IMAX\x10\x00\x12\n" +
	"\n" +
	"\x06ThreeD\x10\x01\x12\b\n" +
	"\x04TwoD\x10\x02BaZ_github.com/movie-reservation-system-ms/movie_reservation_proto_lib/theatre_service/;screen_typeb\x06proto3"

var (
	file_theatre_service_theatre_screen_type_proto_rawDescOnce sync.Once
	file_theatre_service_theatre_screen_type_proto_rawDescData []byte
)

func file_theatre_service_theatre_screen_type_proto_rawDescGZIP() []byte {
	file_theatre_service_theatre_screen_type_proto_rawDescOnce.Do(func() {
		file_theatre_service_theatre_screen_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_theatre_service_theatre_screen_type_proto_rawDesc), len(file_theatre_service_theatre_screen_type_proto_rawDesc)))
	})
	return file_theatre_service_theatre_screen_type_proto_rawDescData
}

var file_theatre_service_theatre_screen_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_theatre_service_theatre_screen_type_proto_goTypes = []any{
	(ScreenType)(0), // 0: theatre_service.screen_type.ScreenType
}
var file_theatre_service_theatre_screen_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_theatre_service_theatre_screen_type_proto_init() }
func file_theatre_service_theatre_screen_type_proto_init() {
	if File_theatre_service_theatre_screen_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_theatre_service_theatre_screen_type_proto_rawDesc), len(file_theatre_service_theatre_screen_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_theatre_service_theatre_screen_type_proto_goTypes,
		DependencyIndexes: file_theatre_service_theatre_screen_type_proto_depIdxs,
		EnumInfos:         file_theatre_service_theatre_screen_type_proto_enumTypes,
	}.Build()
	File_theatre_service_theatre_screen_type_proto = out.File
	file_theatre_service_theatre_screen_type_proto_goTypes = nil
	file_theatre_service_theatre_screen_type_proto_depIdxs = nil
}
