// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: theatre_service/theatre_write.proto

package theatre_write

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TheatreWriteService_CreateTheatre_FullMethodName = "/theatre_service.write.TheatreWriteService/CreateTheatre"
	TheatreWriteService_UpdateTheatre_FullMethodName = "/theatre_service.write.TheatreWriteService/UpdateTheatre"
	TheatreWriteService_DeleteTheatre_FullMethodName = "/theatre_service.write.TheatreWriteService/DeleteTheatre"
	TheatreWriteService_CreateScreen_FullMethodName  = "/theatre_service.write.TheatreWriteService/CreateScreen"
)

// TheatreWriteServiceClient is the client API for TheatreWriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TheatreWriteServiceClient interface {
	// |--------------------------------------------------------------------------
	// | Create Theatre
	// |--------------------------------------------------------------------------
	CreateTheatre(ctx context.Context, in *CreateTheatreRequest, opts ...grpc.CallOption) (*CreateTheatreResponse, error)
	// |--------------------------------------------------------------------------
	// | Update Theatre
	// |--------------------------------------------------------------------------
	UpdateTheatre(ctx context.Context, in *UpdateTheatreRequest, opts ...grpc.CallOption) (*UpdateTheatreResponse, error)
	// |--------------------------------------------------------------------------
	// | Delete Theatre
	// |--------------------------------------------------------------------------
	DeleteTheatre(ctx context.Context, in *DeleteTheatreRequest, opts ...grpc.CallOption) (*DeleteTheatreResponse, error)
	// |--------------------------------------------------------------------------
	// | Create Screen
	// |--------------------------------------------------------------------------
	CreateScreen(ctx context.Context, in *CreateScreenRequest, opts ...grpc.CallOption) (*CreateScreenResponse, error)
}

type theatreWriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTheatreWriteServiceClient(cc grpc.ClientConnInterface) TheatreWriteServiceClient {
	return &theatreWriteServiceClient{cc}
}

func (c *theatreWriteServiceClient) CreateTheatre(ctx context.Context, in *CreateTheatreRequest, opts ...grpc.CallOption) (*CreateTheatreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTheatreResponse)
	err := c.cc.Invoke(ctx, TheatreWriteService_CreateTheatre_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theatreWriteServiceClient) UpdateTheatre(ctx context.Context, in *UpdateTheatreRequest, opts ...grpc.CallOption) (*UpdateTheatreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTheatreResponse)
	err := c.cc.Invoke(ctx, TheatreWriteService_UpdateTheatre_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theatreWriteServiceClient) DeleteTheatre(ctx context.Context, in *DeleteTheatreRequest, opts ...grpc.CallOption) (*DeleteTheatreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTheatreResponse)
	err := c.cc.Invoke(ctx, TheatreWriteService_DeleteTheatre_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theatreWriteServiceClient) CreateScreen(ctx context.Context, in *CreateScreenRequest, opts ...grpc.CallOption) (*CreateScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateScreenResponse)
	err := c.cc.Invoke(ctx, TheatreWriteService_CreateScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TheatreWriteServiceServer is the server API for TheatreWriteService service.
// All implementations must embed UnimplementedTheatreWriteServiceServer
// for forward compatibility.
type TheatreWriteServiceServer interface {
	// |--------------------------------------------------------------------------
	// | Create Theatre
	// |--------------------------------------------------------------------------
	CreateTheatre(context.Context, *CreateTheatreRequest) (*CreateTheatreResponse, error)
	// |--------------------------------------------------------------------------
	// | Update Theatre
	// |--------------------------------------------------------------------------
	UpdateTheatre(context.Context, *UpdateTheatreRequest) (*UpdateTheatreResponse, error)
	// |--------------------------------------------------------------------------
	// | Delete Theatre
	// |--------------------------------------------------------------------------
	DeleteTheatre(context.Context, *DeleteTheatreRequest) (*DeleteTheatreResponse, error)
	// |--------------------------------------------------------------------------
	// | Create Screen
	// |--------------------------------------------------------------------------
	CreateScreen(context.Context, *CreateScreenRequest) (*CreateScreenResponse, error)
	mustEmbedUnimplementedTheatreWriteServiceServer()
}

// UnimplementedTheatreWriteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTheatreWriteServiceServer struct{}

func (UnimplementedTheatreWriteServiceServer) CreateTheatre(context.Context, *CreateTheatreRequest) (*CreateTheatreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTheatre not implemented")
}
func (UnimplementedTheatreWriteServiceServer) UpdateTheatre(context.Context, *UpdateTheatreRequest) (*UpdateTheatreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTheatre not implemented")
}
func (UnimplementedTheatreWriteServiceServer) DeleteTheatre(context.Context, *DeleteTheatreRequest) (*DeleteTheatreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTheatre not implemented")
}
func (UnimplementedTheatreWriteServiceServer) CreateScreen(context.Context, *CreateScreenRequest) (*CreateScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScreen not implemented")
}
func (UnimplementedTheatreWriteServiceServer) mustEmbedUnimplementedTheatreWriteServiceServer() {}
func (UnimplementedTheatreWriteServiceServer) testEmbeddedByValue()                             {}

// UnsafeTheatreWriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TheatreWriteServiceServer will
// result in compilation errors.
type UnsafeTheatreWriteServiceServer interface {
	mustEmbedUnimplementedTheatreWriteServiceServer()
}

func RegisterTheatreWriteServiceServer(s grpc.ServiceRegistrar, srv TheatreWriteServiceServer) {
	// If the following call panics, it indicates UnimplementedTheatreWriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TheatreWriteService_ServiceDesc, srv)
}

func _TheatreWriteService_CreateTheatre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTheatreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheatreWriteServiceServer).CreateTheatre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheatreWriteService_CreateTheatre_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheatreWriteServiceServer).CreateTheatre(ctx, req.(*CreateTheatreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheatreWriteService_UpdateTheatre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTheatreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheatreWriteServiceServer).UpdateTheatre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheatreWriteService_UpdateTheatre_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheatreWriteServiceServer).UpdateTheatre(ctx, req.(*UpdateTheatreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheatreWriteService_DeleteTheatre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTheatreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheatreWriteServiceServer).DeleteTheatre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheatreWriteService_DeleteTheatre_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheatreWriteServiceServer).DeleteTheatre(ctx, req.(*DeleteTheatreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheatreWriteService_CreateScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheatreWriteServiceServer).CreateScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheatreWriteService_CreateScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheatreWriteServiceServer).CreateScreen(ctx, req.(*CreateScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TheatreWriteService_ServiceDesc is the grpc.ServiceDesc for TheatreWriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TheatreWriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "theatre_service.write.TheatreWriteService",
	HandlerType: (*TheatreWriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTheatre",
			Handler:    _TheatreWriteService_CreateTheatre_Handler,
		},
		{
			MethodName: "UpdateTheatre",
			Handler:    _TheatreWriteService_UpdateTheatre_Handler,
		},
		{
			MethodName: "DeleteTheatre",
			Handler:    _TheatreWriteService_DeleteTheatre_Handler,
		},
		{
			MethodName: "CreateScreen",
			Handler:    _TheatreWriteService_CreateScreen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "theatre_service/theatre_write.proto",
}
