// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: theatre_service/theatre_read.proto

package theatre_read

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TheatreReadService_GetTheatres_FullMethodName       = "/theatre_service.read.TheatreReadService/GetTheatres"
	TheatreReadService_GetTheatreById_FullMethodName    = "/theatre_service.read.TheatreReadService/GetTheatreById"
	TheatreReadService_GetTheatreScreens_FullMethodName = "/theatre_service.read.TheatreReadService/GetTheatreScreens"
)

// TheatreReadServiceClient is the client API for TheatreReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TheatreReadServiceClient interface {
	// |--------------------------------------------------------------------------
	// | Get Theatres
	// |--------------------------------------------------------------------------
	// |
	// | Fetch all theatres.
	// |
	// | REST:
	// | GET /theatres
	// |
	GetTheatres(ctx context.Context, in *GetTheatresRequest, opts ...grpc.CallOption) (*GetTheatresResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Theatre By ID
	// |--------------------------------------------------------------------------
	// |
	// | Fetch single theatre details.
	// |
	// | REST:
	// | GET /theatres/{id}
	// |
	GetTheatreById(ctx context.Context, in *GetTheatreByIdRequest, opts ...grpc.CallOption) (*GetTheatreByIdResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Theatre Screens
	// |--------------------------------------------------------------------------
	// |
	// | Fetch all screens for theatre.
	// |
	// | REST:
	// | GET /theatres/{id}/screens
	// |
	GetTheatreScreens(ctx context.Context, in *GetTheatreScreensRequest, opts ...grpc.CallOption) (*GetTheatreScreensResponse, error)
}

type theatreReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTheatreReadServiceClient(cc grpc.ClientConnInterface) TheatreReadServiceClient {
	return &theatreReadServiceClient{cc}
}

func (c *theatreReadServiceClient) GetTheatres(ctx context.Context, in *GetTheatresRequest, opts ...grpc.CallOption) (*GetTheatresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTheatresResponse)
	err := c.cc.Invoke(ctx, TheatreReadService_GetTheatres_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theatreReadServiceClient) GetTheatreById(ctx context.Context, in *GetTheatreByIdRequest, opts ...grpc.CallOption) (*GetTheatreByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTheatreByIdResponse)
	err := c.cc.Invoke(ctx, TheatreReadService_GetTheatreById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theatreReadServiceClient) GetTheatreScreens(ctx context.Context, in *GetTheatreScreensRequest, opts ...grpc.CallOption) (*GetTheatreScreensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTheatreScreensResponse)
	err := c.cc.Invoke(ctx, TheatreReadService_GetTheatreScreens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TheatreReadServiceServer is the server API for TheatreReadService service.
// All implementations must embed UnimplementedTheatreReadServiceServer
// for forward compatibility.
type TheatreReadServiceServer interface {
	// |--------------------------------------------------------------------------
	// | Get Theatres
	// |--------------------------------------------------------------------------
	// |
	// | Fetch all theatres.
	// |
	// | REST:
	// | GET /theatres
	// |
	GetTheatres(context.Context, *GetTheatresRequest) (*GetTheatresResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Theatre By ID
	// |--------------------------------------------------------------------------
	// |
	// | Fetch single theatre details.
	// |
	// | REST:
	// | GET /theatres/{id}
	// |
	GetTheatreById(context.Context, *GetTheatreByIdRequest) (*GetTheatreByIdResponse, error)
	// |--------------------------------------------------------------------------
	// | Get Theatre Screens
	// |--------------------------------------------------------------------------
	// |
	// | Fetch all screens for theatre.
	// |
	// | REST:
	// | GET /theatres/{id}/screens
	// |
	GetTheatreScreens(context.Context, *GetTheatreScreensRequest) (*GetTheatreScreensResponse, error)
	mustEmbedUnimplementedTheatreReadServiceServer()
}

// UnimplementedTheatreReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTheatreReadServiceServer struct{}

func (UnimplementedTheatreReadServiceServer) GetTheatres(context.Context, *GetTheatresRequest) (*GetTheatresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTheatres not implemented")
}
func (UnimplementedTheatreReadServiceServer) GetTheatreById(context.Context, *GetTheatreByIdRequest) (*GetTheatreByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTheatreById not implemented")
}
func (UnimplementedTheatreReadServiceServer) GetTheatreScreens(context.Context, *GetTheatreScreensRequest) (*GetTheatreScreensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTheatreScreens not implemented")
}
func (UnimplementedTheatreReadServiceServer) mustEmbedUnimplementedTheatreReadServiceServer() {}
func (UnimplementedTheatreReadServiceServer) testEmbeddedByValue()                            {}

// UnsafeTheatreReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TheatreReadServiceServer will
// result in compilation errors.
type UnsafeTheatreReadServiceServer interface {
	mustEmbedUnimplementedTheatreReadServiceServer()
}

func RegisterTheatreReadServiceServer(s grpc.ServiceRegistrar, srv TheatreReadServiceServer) {
	// If the following call panics, it indicates UnimplementedTheatreReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TheatreReadService_ServiceDesc, srv)
}

func _TheatreReadService_GetTheatres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTheatresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheatreReadServiceServer).GetTheatres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheatreReadService_GetTheatres_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheatreReadServiceServer).GetTheatres(ctx, req.(*GetTheatresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheatreReadService_GetTheatreById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTheatreByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheatreReadServiceServer).GetTheatreById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheatreReadService_GetTheatreById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheatreReadServiceServer).GetTheatreById(ctx, req.(*GetTheatreByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheatreReadService_GetTheatreScreens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTheatreScreensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheatreReadServiceServer).GetTheatreScreens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheatreReadService_GetTheatreScreens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheatreReadServiceServer).GetTheatreScreens(ctx, req.(*GetTheatreScreensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TheatreReadService_ServiceDesc is the grpc.ServiceDesc for TheatreReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TheatreReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "theatre_service.read.TheatreReadService",
	HandlerType: (*TheatreReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTheatres",
			Handler:    _TheatreReadService_GetTheatres_Handler,
		},
		{
			MethodName: "GetTheatreById",
			Handler:    _TheatreReadService_GetTheatreById_Handler,
		},
		{
			MethodName: "GetTheatreScreens",
			Handler:    _TheatreReadService_GetTheatreScreens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "theatre_service/theatre_read.proto",
}
