// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: theatre_service/theatre_read.proto

package theatre_read

import (
	theatre_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/theatre_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Theatre Entity
// |--------------------------------------------------------------------------
type Theatre struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Theatre identifier
	TheatreId string `protobuf:"bytes,1,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	// Theatre name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Theatre description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Address line
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// City
	City string `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	// State
	State string `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	// Country
	Country string `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	// Postal code
	PostalCode string `protobuf:"bytes,8,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	// Contact number
	Phone string `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	// Theatre email
	Email string `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Theatre) Reset() {
	*x = Theatre{}
	mi := &file_theatre_service_theatre_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Theatre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theatre) ProtoMessage() {}

func (x *Theatre) ProtoReflect() protoreflect.Message {
	mi := &file_theatre_service_theatre_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theatre.ProtoReflect.Descriptor instead.
func (*Theatre) Descriptor() ([]byte, []int) {
	return file_theatre_service_theatre_read_proto_rawDescGZIP(), []int{0}
}

func (x *Theatre) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

func (x *Theatre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Theatre) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Theatre) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Theatre) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Theatre) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Theatre) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Theatre) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Theatre) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Theatre) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Theatre) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Theatre) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// |--------------------------------------------------------------------------
// | Screen Entity
// |--------------------------------------------------------------------------
type Screen struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Screen identifier
	ScreenId string `protobuf:"bytes,1,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	// Theatre identifier
	TheatreId string `protobuf:"bytes,2,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	// Screen name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Total seats
	TotalSeats uint32 `protobuf:"varint,4,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	// Screen type
	ScreenType theatre_service.ScreenType `protobuf:"varint,5,opt,name=screen_type,json=screenType,proto3,enum=theatre_service.screen_type.ScreenType" json:"screen_type,omitempty"`
	// Creation timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Screen) Reset() {
	*x = Screen{}
	mi := &file_theatre_service_theatre_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Screen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screen) ProtoMessage() {}

func (x *Screen) ProtoReflect() protoreflect.Message {
	mi := &file_theatre_service_theatre_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screen.ProtoReflect.Descriptor instead.
func (*Screen) Descriptor() ([]byte, []int) {
	return file_theatre_service_theatre_read_proto_rawDescGZIP(), []int{1}
}

func (x *Screen) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *Screen) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

func (x *Screen) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Screen) GetTotalSeats() uint32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *Screen) GetScreenType() theatre_service.ScreenType {
	if x != nil {
		return x.ScreenType
	}
	return theatre_service.ScreenType(0)
}

func (x *Screen) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetTheatresRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination limit
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Search keyword
	Search *string `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	// Filter by city
	City          *string `protobuf:"bytes,4,opt,name=city,proto3,oneof" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTheatresRequest) Reset() {
	*x = GetTheatresRequest{}
	mi := &file_theatre_service_theatre_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTheatresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatresRequest) ProtoMessage() {}

func (x *GetTheatresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_theatre_service_theatre_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatresRequest.ProtoReflect.Descriptor instead.
func (*GetTheatresRequest) Descriptor() ([]byte, []int) {
	return file_theatre_service_theatre_read_proto_rawDescGZIP(), []int{2}
}

func (x *GetTheatresRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTheatresRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetTheatresRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetTheatresRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

type GetTheatresResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Theatre list
	Theatres []*Theatre `protobuf:"bytes,1,rep,name=theatres,proto3" json:"theatres,omitempty"`
	// Total records
	Total uint64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// Pagination limit
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset
	Offset        uint32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTheatresResponse) Reset() {
	*x = GetTheatresResponse{}
	mi := &file_theatre_service_theatre_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTheatresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatresResponse) ProtoMessage() {}

func (x *GetTheatresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_theatre_service_theatre_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatresResponse.ProtoReflect.Descriptor instead.
func (*GetTheatresResponse) Descriptor() ([]byte, []int) {
	return file_theatre_service_theatre_read_proto_rawDescGZIP(), []int{3}
}

func (x *GetTheatresResponse) GetTheatres() []*Theatre {
	if x != nil {
		return x.Theatres
	}
	return nil
}

func (x *GetTheatresResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTheatresResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTheatresResponse) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTheatreByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Theatre identifier
	TheatreId     string `protobuf:"bytes,1,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTheatreByIdRequest) Reset() {
	*x = GetTheatreByIdRequest{}
	mi := &file_theatre_service_theatre_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTheatreByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatreByIdRequest) ProtoMessage() {}

func (x *GetTheatreByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_theatre_service_theatre_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatreByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTheatreByIdRequest) Descriptor() ([]byte, []int) {
	return file_theatre_service_theatre_read_proto_rawDescGZIP(), []int{4}
}

func (x *GetTheatreByIdRequest) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

type GetTheatreByIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Theatre entity
	Theatre       *Theatre `protobuf:"bytes,1,opt,name=theatre,proto3" json:"theatre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTheatreByIdResponse) Reset() {
	*x = GetTheatreByIdResponse{}
	mi := &file_theatre_service_theatre_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTheatreByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatreByIdResponse) ProtoMessage() {}

func (x *GetTheatreByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_theatre_service_theatre_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatreByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTheatreByIdResponse) Descriptor() ([]byte, []int) {
	return file_theatre_service_theatre_read_proto_rawDescGZIP(), []int{5}
}

func (x *GetTheatreByIdResponse) GetTheatre() *Theatre {
	if x != nil {
		return x.Theatre
	}
	return nil
}

type GetTheatreScreensRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Theatre identifier
	TheatreId     string `protobuf:"bytes,1,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTheatreScreensRequest) Reset() {
	*x = GetTheatreScreensRequest{}
	mi := &file_theatre_service_theatre_read_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTheatreScreensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatreScreensRequest) ProtoMessage() {}

func (x *GetTheatreScreensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_theatre_service_theatre_read_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatreScreensRequest.ProtoReflect.Descriptor instead.
func (*GetTheatreScreensRequest) Descriptor() ([]byte, []int) {
	return file_theatre_service_theatre_read_proto_rawDescGZIP(), []int{6}
}

func (x *GetTheatreScreensRequest) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

type GetTheatreScreensResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Screen list
	Screens       []*Screen `protobuf:"bytes,1,rep,name=screens,proto3" json:"screens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTheatreScreensResponse) Reset() {
	*x = GetTheatreScreensResponse{}
	mi := &file_theatre_service_theatre_read_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTheatreScreensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatreScreensResponse) ProtoMessage() {}

func (x *GetTheatreScreensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_theatre_service_theatre_read_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatreScreensResponse.ProtoReflect.Descriptor instead.
func (*GetTheatreScreensResponse) Descriptor() ([]byte, []int) {
	return file_theatre_service_theatre_read_proto_rawDescGZIP(), []int{7}
}

func (x *GetTheatreScreensResponse) GetScreens() []*Screen {
	if x != nil {
		return x.Screens
	}
	return nil
}

var File_theatre_service_theatre_read_proto protoreflect.FileDescriptor

const file_theatre_service_theatre_read_proto_rawDesc = "" +
	"\n" +
	"\"theatre_service/theatre_read.proto\x12\x14theatre_service.read\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)theatre_service/theatre_screen_type.proto\"\xff\x02\n" +
	"\aTheatre\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x01 \x01(\tR\ttheatreId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\b \x01(\tR\n" +
	"postalCode\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfe\x01\n" +
	"\x06Screen\x12\x1b\n" +
	"\tscreen_id\x18\x01 \x01(\tR\bscreenId\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x02 \x01(\tR\ttheatreId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vtotal_seats\x18\x04 \x01(\rR\n" +
	"totalSeats\x12H\n" +
	"\vscreen_type\x18\x05 \x01(\x0e2'.theatre_service.screen_type.ScreenTypeR\n" +
	"screenType\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8c\x01\n" +
	"\x12GetTheatresRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x1b\n" +
	"\x06search\x18\x03 \x01(\tH\x00R\x06search\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x04 \x01(\tH\x01R\x04city\x88\x01\x01B\t\n" +
	"\a_searchB\a\n" +
	"\x05_city\"\x94\x01\n" +
	"\x13GetTheatresResponse\x129\n" +
	"\btheatres\x18\x01 \x03(\v2\x1d.theatre_service.read.TheatreR\btheatres\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"6\n" +
	"\x15GetTheatreByIdRequest\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x01 \x01(\tR\ttheatreId\"Q\n" +
	"\x16GetTheatreByIdResponse\x127\n" +
	"\atheatre\x18\x01 \x01(\v2\x1d.theatre_service.read.TheatreR\atheatre\"9\n" +
	"\x18GetTheatreScreensRequest\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x01 \x01(\tR\ttheatreId\"S\n" +
	"\x19GetTheatreScreensResponse\x126\n" +
	"\ascreens\x18\x01 \x03(\v2\x1c.theatre_service.read.ScreenR\ascreens2\xdb\x02\n" +
	"\x12TheatreReadService\x12b\n" +
	"\vGetTheatres\x12(.theatre_service.read.GetTheatresRequest\x1a).theatre_service.read.GetTheatresResponse\x12k\n" +
	"\x0eGetTheatreById\x12+.theatre_service.read.GetTheatreByIdRequest\x1a,.theatre_service.read.GetTheatreByIdResponse\x12t\n" +
	"\x11GetTheatreScreens\x12..theatre_service.read.GetTheatreScreensRequest\x1a/.theatre_service.read.GetTheatreScreensResponseBfZdgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/theatre_service/read;theatre_readb\x06proto3"

var (
	file_theatre_service_theatre_read_proto_rawDescOnce sync.Once
	file_theatre_service_theatre_read_proto_rawDescData []byte
)

func file_theatre_service_theatre_read_proto_rawDescGZIP() []byte {
	file_theatre_service_theatre_read_proto_rawDescOnce.Do(func() {
		file_theatre_service_theatre_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_theatre_service_theatre_read_proto_rawDesc), len(file_theatre_service_theatre_read_proto_rawDesc)))
	})
	return file_theatre_service_theatre_read_proto_rawDescData
}

var file_theatre_service_theatre_read_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_theatre_service_theatre_read_proto_goTypes = []any{
	(*Theatre)(nil),                   // 0: theatre_service.read.Theatre
	(*Screen)(nil),                    // 1: theatre_service.read.Screen
	(*GetTheatresRequest)(nil),        // 2: theatre_service.read.GetTheatresRequest
	(*GetTheatresResponse)(nil),       // 3: theatre_service.read.GetTheatresResponse
	(*GetTheatreByIdRequest)(nil),     // 4: theatre_service.read.GetTheatreByIdRequest
	(*GetTheatreByIdResponse)(nil),    // 5: theatre_service.read.GetTheatreByIdResponse
	(*GetTheatreScreensRequest)(nil),  // 6: theatre_service.read.GetTheatreScreensRequest
	(*GetTheatreScreensResponse)(nil), // 7: theatre_service.read.GetTheatreScreensResponse
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
	(theatre_service.ScreenType)(0),   // 9: theatre_service.screen_type.ScreenType
}
var file_theatre_service_theatre_read_proto_depIdxs = []int32{
	8,  // 0: theatre_service.read.Theatre.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: theatre_service.read.Theatre.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: theatre_service.read.Screen.screen_type:type_name -> theatre_service.screen_type.ScreenType
	8,  // 3: theatre_service.read.Screen.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: theatre_service.read.GetTheatresResponse.theatres:type_name -> theatre_service.read.Theatre
	0,  // 5: theatre_service.read.GetTheatreByIdResponse.theatre:type_name -> theatre_service.read.Theatre
	1,  // 6: theatre_service.read.GetTheatreScreensResponse.screens:type_name -> theatre_service.read.Screen
	2,  // 7: theatre_service.read.TheatreReadService.GetTheatres:input_type -> theatre_service.read.GetTheatresRequest
	4,  // 8: theatre_service.read.TheatreReadService.GetTheatreById:input_type -> theatre_service.read.GetTheatreByIdRequest
	6,  // 9: theatre_service.read.TheatreReadService.GetTheatreScreens:input_type -> theatre_service.read.GetTheatreScreensRequest
	3,  // 10: theatre_service.read.TheatreReadService.GetTheatres:output_type -> theatre_service.read.GetTheatresResponse
	5,  // 11: theatre_service.read.TheatreReadService.GetTheatreById:output_type -> theatre_service.read.GetTheatreByIdResponse
	7,  // 12: theatre_service.read.TheatreReadService.GetTheatreScreens:output_type -> theatre_service.read.GetTheatreScreensResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_theatre_service_theatre_read_proto_init() }
func file_theatre_service_theatre_read_proto_init() {
	if File_theatre_service_theatre_read_proto != nil {
		return
	}
	file_theatre_service_theatre_read_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_theatre_service_theatre_read_proto_rawDesc), len(file_theatre_service_theatre_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_theatre_service_theatre_read_proto_goTypes,
		DependencyIndexes: file_theatre_service_theatre_read_proto_depIdxs,
		MessageInfos:      file_theatre_service_theatre_read_proto_msgTypes,
	}.Build()
	File_theatre_service_theatre_read_proto = out.File
	file_theatre_service_theatre_read_proto_goTypes = nil
	file_theatre_service_theatre_read_proto_depIdxs = nil
}
