// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ticket_service/ticket_status.proto

package ticket_status

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Ticket Status
// |--------------------------------------------------------------------------
type TicketStatus int32

const (
	TicketStatus_TICKET_STATUS_UNSPECIFIED TicketStatus = 0
	TicketStatus_TICKET_STATUS_PENDING     TicketStatus = 1
	TicketStatus_TICKET_STATUS_HELD        TicketStatus = 2
	TicketStatus_TICKET_STATUS_CONFIRMED   TicketStatus = 3
	TicketStatus_TICKET_STATUS_CANCELLED   TicketStatus = 4
	TicketStatus_TICKET_STATUS_EXPIRED     TicketStatus = 5
)

// Enum value maps for TicketStatus.
var (
	TicketStatus_name = map[int32]string{
		0: "TICKET_STATUS_UNSPECIFIED",
		1: "TICKET_STATUS_PENDING",
		2: "TICKET_STATUS_HELD",
		3: "TICKET_STATUS_CONFIRMED",
		4: "TICKET_STATUS_CANCELLED",
		5: "TICKET_STATUS_EXPIRED",
	}
	TicketStatus_value = map[string]int32{
		"TICKET_STATUS_UNSPECIFIED": 0,
		"TICKET_STATUS_PENDING":     1,
		"TICKET_STATUS_HELD":        2,
		"TICKET_STATUS_CONFIRMED":   3,
		"TICKET_STATUS_CANCELLED":   4,
		"TICKET_STATUS_EXPIRED":     5,
	}
)

func (x TicketStatus) Enum() *TicketStatus {
	p := new(TicketStatus)
	*p = x
	return p
}

func (x TicketStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ticket_service_ticket_status_proto_enumTypes[0].Descriptor()
}

func (TicketStatus) Type() protoreflect.EnumType {
	return &file_ticket_service_ticket_status_proto_enumTypes[0]
}

func (x TicketStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketStatus.Descriptor instead.
func (TicketStatus) EnumDescriptor() ([]byte, []int) {
	return file_ticket_service_ticket_status_proto_rawDescGZIP(), []int{0}
}

var File_ticket_service_ticket_status_proto protoreflect.FileDescriptor

const file_ticket_service_ticket_status_proto_rawDesc = "" +
	"\n" +
	"\"ticket_service/ticket_status.proto\x12\x15ticket_service.status*\xb5\x01\n" +
	"\fTicketStatus\x12\x1d\n" +
	"\x19TICKET_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TICKET_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12TICKET_STATUS_HELD\x10\x02\x12\x1b\n" +
	"\x17TICKET_STATUS_CONFIRMED\x10\x03\x12\x1b\n" +
	"\x17TICKET_STATUS_CANCELLED\x10\x04\x12\x19\n" +
	"\x15TICKET_STATUS_EXPIRED\x10\x05BbZ`github.com/movie-reservation-system-ms/movie_reservation_proto_lib/ticket_service/;ticket_statusb\x06proto3"

var (
	file_ticket_service_ticket_status_proto_rawDescOnce sync.Once
	file_ticket_service_ticket_status_proto_rawDescData []byte
)

func file_ticket_service_ticket_status_proto_rawDescGZIP() []byte {
	file_ticket_service_ticket_status_proto_rawDescOnce.Do(func() {
		file_ticket_service_ticket_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticket_service_ticket_status_proto_rawDesc), len(file_ticket_service_ticket_status_proto_rawDesc)))
	})
	return file_ticket_service_ticket_status_proto_rawDescData
}

var file_ticket_service_ticket_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ticket_service_ticket_status_proto_goTypes = []any{
	(TicketStatus)(0), // 0: ticket_service.status.TicketStatus
}
var file_ticket_service_ticket_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ticket_service_ticket_status_proto_init() }
func file_ticket_service_ticket_status_proto_init() {
	if File_ticket_service_ticket_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticket_service_ticket_status_proto_rawDesc), len(file_ticket_service_ticket_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ticket_service_ticket_status_proto_goTypes,
		DependencyIndexes: file_ticket_service_ticket_status_proto_depIdxs,
		EnumInfos:         file_ticket_service_ticket_status_proto_enumTypes,
	}.Build()
	File_ticket_service_ticket_status_proto = out.File
	file_ticket_service_ticket_status_proto_goTypes = nil
	file_ticket_service_ticket_status_proto_depIdxs = nil
}
