// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ticket_service/ticket_write.proto

package ticket_write

import (
	ticket_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/ticket_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookTicketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Booking identifier
	BookingId string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	// User identifier
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Show identifier
	ShowId string `protobuf:"bytes,3,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	// Seat identifiers
	SeatIds []string `protobuf:"bytes,4,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	// Total amount
	TotalAmount   float64 `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookTicketRequest) Reset() {
	*x = BookTicketRequest{}
	mi := &file_ticket_service_ticket_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTicketRequest) ProtoMessage() {}

func (x *BookTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTicketRequest.ProtoReflect.Descriptor instead.
func (*BookTicketRequest) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_write_proto_rawDescGZIP(), []int{0}
}

func (x *BookTicketRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookTicketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookTicketRequest) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *BookTicketRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *BookTicketRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type BookTicketResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created ticket identifier
	TicketId string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	// Ticket status
	Status ticket_service.TicketStatus `protobuf:"varint,2,opt,name=status,proto3,enum=ticket_service.status.TicketStatus" json:"status,omitempty"`
	// Ticket creation timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookTicketResponse) Reset() {
	*x = BookTicketResponse{}
	mi := &file_ticket_service_ticket_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTicketResponse) ProtoMessage() {}

func (x *BookTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTicketResponse.ProtoReflect.Descriptor instead.
func (*BookTicketResponse) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_write_proto_rawDescGZIP(), []int{1}
}

func (x *BookTicketResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *BookTicketResponse) GetStatus() ticket_service.TicketStatus {
	if x != nil {
		return x.Status
	}
	return ticket_service.TicketStatus(0)
}

func (x *BookTicketResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type HoldTicketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticket identifier
	TicketId string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	// Hold expiration timestamp
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldTicketRequest) Reset() {
	*x = HoldTicketRequest{}
	mi := &file_ticket_service_ticket_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldTicketRequest) ProtoMessage() {}

func (x *HoldTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldTicketRequest.ProtoReflect.Descriptor instead.
func (*HoldTicketRequest) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_write_proto_rawDescGZIP(), []int{2}
}

func (x *HoldTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *HoldTicketRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type HoldTicketResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticket identifier
	TicketId string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	// Ticket status
	Status ticket_service.TicketStatus `protobuf:"varint,2,opt,name=status,proto3,enum=ticket_service.status.TicketStatus" json:"status,omitempty"`
	// Hold expiration timestamp
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldTicketResponse) Reset() {
	*x = HoldTicketResponse{}
	mi := &file_ticket_service_ticket_write_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldTicketResponse) ProtoMessage() {}

func (x *HoldTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_write_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldTicketResponse.ProtoReflect.Descriptor instead.
func (*HoldTicketResponse) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_write_proto_rawDescGZIP(), []int{3}
}

func (x *HoldTicketResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *HoldTicketResponse) GetStatus() ticket_service.TicketStatus {
	if x != nil {
		return x.Status
	}
	return ticket_service.TicketStatus(0)
}

func (x *HoldTicketResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ConfirmTicketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticket identifier
	TicketId      string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTicketRequest) Reset() {
	*x = ConfirmTicketRequest{}
	mi := &file_ticket_service_ticket_write_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTicketRequest) ProtoMessage() {}

func (x *ConfirmTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_write_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTicketRequest.ProtoReflect.Descriptor instead.
func (*ConfirmTicketRequest) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_write_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type ConfirmTicketResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticket identifier
	TicketId string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	// Ticket status
	Status ticket_service.TicketStatus `protobuf:"varint,2,opt,name=status,proto3,enum=ticket_service.status.TicketStatus" json:"status,omitempty"`
	// Confirmation timestamp
	ConfirmedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTicketResponse) Reset() {
	*x = ConfirmTicketResponse{}
	mi := &file_ticket_service_ticket_write_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTicketResponse) ProtoMessage() {}

func (x *ConfirmTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_write_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTicketResponse.ProtoReflect.Descriptor instead.
func (*ConfirmTicketResponse) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_write_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmTicketResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ConfirmTicketResponse) GetStatus() ticket_service.TicketStatus {
	if x != nil {
		return x.Status
	}
	return ticket_service.TicketStatus(0)
}

func (x *ConfirmTicketResponse) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

type CancelTicketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticket identifier
	TicketId string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	// Cancellation reason
	Reason        *string `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTicketRequest) Reset() {
	*x = CancelTicketRequest{}
	mi := &file_ticket_service_ticket_write_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTicketRequest) ProtoMessage() {}

func (x *CancelTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_write_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTicketRequest.ProtoReflect.Descriptor instead.
func (*CancelTicketRequest) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_write_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *CancelTicketRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type CancelTicketResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Ticket status
	Status ticket_service.TicketStatus `protobuf:"varint,2,opt,name=status,proto3,enum=ticket_service.status.TicketStatus" json:"status,omitempty"`
	// Cancellation timestamp
	CancelledAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTicketResponse) Reset() {
	*x = CancelTicketResponse{}
	mi := &file_ticket_service_ticket_write_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTicketResponse) ProtoMessage() {}

func (x *CancelTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_write_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTicketResponse.ProtoReflect.Descriptor instead.
func (*CancelTicketResponse) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_write_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTicketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTicketResponse) GetStatus() ticket_service.TicketStatus {
	if x != nil {
		return x.Status
	}
	return ticket_service.TicketStatus(0)
}

func (x *CancelTicketResponse) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

var File_ticket_service_ticket_write_proto protoreflect.FileDescriptor

const file_ticket_service_ticket_write_proto_rawDesc = "" +
	"\n" +
	"!ticket_service/ticket_write.proto\x12\x14ticket_service.write\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"ticket_service/ticket_status.proto\"\xa2\x01\n" +
	"\x11BookTicketRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\ashow_id\x18\x03 \x01(\tR\x06showId\x12\x19\n" +
	"\bseat_ids\x18\x04 \x03(\tR\aseatIds\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\"\xa9\x01\n" +
	"\x12BookTicketResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.ticket_service.status.TicketStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"k\n" +
	"\x11HoldTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xa9\x01\n" +
	"\x12HoldTicketResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.ticket_service.status.TicketStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"3\n" +
	"\x14ConfirmTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"\xb0\x01\n" +
	"\x15ConfirmTicketResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.ticket_service.status.TicketStatusR\x06status\x12=\n" +
	"\fconfirmed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\"Z\n" +
	"\x13CancelTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\xac\x01\n" +
	"\x14CancelTicketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.ticket_service.status.TicketStatusR\x06status\x12=\n" +
	"\fcancelled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt2\xa7\x03\n" +
	"\x12TicketWriteService\x12_\n" +
	"\n" +
	"BookTicket\x12'.ticket_service.write.BookTicketRequest\x1a(.ticket_service.write.BookTicketResponse\x12_\n" +
	"\n" +
	"HoldTicket\x12'.ticket_service.write.HoldTicketRequest\x1a(.ticket_service.write.HoldTicketResponse\x12h\n" +
	"\rConfirmTicket\x12*.ticket_service.write.ConfirmTicketRequest\x1a+.ticket_service.write.ConfirmTicketResponse\x12e\n" +
	"\fCancelTicket\x12).ticket_service.write.CancelTicketRequest\x1a*.ticket_service.write.CancelTicketResponseBfZdgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/ticket_service/write;ticket_writeb\x06proto3"

var (
	file_ticket_service_ticket_write_proto_rawDescOnce sync.Once
	file_ticket_service_ticket_write_proto_rawDescData []byte
)

func file_ticket_service_ticket_write_proto_rawDescGZIP() []byte {
	file_ticket_service_ticket_write_proto_rawDescOnce.Do(func() {
		file_ticket_service_ticket_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticket_service_ticket_write_proto_rawDesc), len(file_ticket_service_ticket_write_proto_rawDesc)))
	})
	return file_ticket_service_ticket_write_proto_rawDescData
}

var file_ticket_service_ticket_write_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ticket_service_ticket_write_proto_goTypes = []any{
	(*BookTicketRequest)(nil),        // 0: ticket_service.write.BookTicketRequest
	(*BookTicketResponse)(nil),       // 1: ticket_service.write.BookTicketResponse
	(*HoldTicketRequest)(nil),        // 2: ticket_service.write.HoldTicketRequest
	(*HoldTicketResponse)(nil),       // 3: ticket_service.write.HoldTicketResponse
	(*ConfirmTicketRequest)(nil),     // 4: ticket_service.write.ConfirmTicketRequest
	(*ConfirmTicketResponse)(nil),    // 5: ticket_service.write.ConfirmTicketResponse
	(*CancelTicketRequest)(nil),      // 6: ticket_service.write.CancelTicketRequest
	(*CancelTicketResponse)(nil),     // 7: ticket_service.write.CancelTicketResponse
	(ticket_service.TicketStatus)(0), // 8: ticket_service.status.TicketStatus
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
}
var file_ticket_service_ticket_write_proto_depIdxs = []int32{
	8,  // 0: ticket_service.write.BookTicketResponse.status:type_name -> ticket_service.status.TicketStatus
	9,  // 1: ticket_service.write.BookTicketResponse.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: ticket_service.write.HoldTicketRequest.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 3: ticket_service.write.HoldTicketResponse.status:type_name -> ticket_service.status.TicketStatus
	9,  // 4: ticket_service.write.HoldTicketResponse.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 5: ticket_service.write.ConfirmTicketResponse.status:type_name -> ticket_service.status.TicketStatus
	9,  // 6: ticket_service.write.ConfirmTicketResponse.confirmed_at:type_name -> google.protobuf.Timestamp
	8,  // 7: ticket_service.write.CancelTicketResponse.status:type_name -> ticket_service.status.TicketStatus
	9,  // 8: ticket_service.write.CancelTicketResponse.cancelled_at:type_name -> google.protobuf.Timestamp
	0,  // 9: ticket_service.write.TicketWriteService.BookTicket:input_type -> ticket_service.write.BookTicketRequest
	2,  // 10: ticket_service.write.TicketWriteService.HoldTicket:input_type -> ticket_service.write.HoldTicketRequest
	4,  // 11: ticket_service.write.TicketWriteService.ConfirmTicket:input_type -> ticket_service.write.ConfirmTicketRequest
	6,  // 12: ticket_service.write.TicketWriteService.CancelTicket:input_type -> ticket_service.write.CancelTicketRequest
	1,  // 13: ticket_service.write.TicketWriteService.BookTicket:output_type -> ticket_service.write.BookTicketResponse
	3,  // 14: ticket_service.write.TicketWriteService.HoldTicket:output_type -> ticket_service.write.HoldTicketResponse
	5,  // 15: ticket_service.write.TicketWriteService.ConfirmTicket:output_type -> ticket_service.write.ConfirmTicketResponse
	7,  // 16: ticket_service.write.TicketWriteService.CancelTicket:output_type -> ticket_service.write.CancelTicketResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ticket_service_ticket_write_proto_init() }
func file_ticket_service_ticket_write_proto_init() {
	if File_ticket_service_ticket_write_proto != nil {
		return
	}
	file_ticket_service_ticket_write_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticket_service_ticket_write_proto_rawDesc), len(file_ticket_service_ticket_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_service_ticket_write_proto_goTypes,
		DependencyIndexes: file_ticket_service_ticket_write_proto_depIdxs,
		MessageInfos:      file_ticket_service_ticket_write_proto_msgTypes,
	}.Build()
	File_ticket_service_ticket_write_proto = out.File
	file_ticket_service_ticket_write_proto_goTypes = nil
	file_ticket_service_ticket_write_proto_depIdxs = nil
}
