// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ticket_service/ticket_read.proto

package ticket_read

import (
	ticket_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/ticket_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Ticket Entity
// |--------------------------------------------------------------------------
type Ticket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticket identifier
	TicketId string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	// Booking identifier
	BookingId string `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	// User identifier
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Movie identifier
	MovieId string `protobuf:"bytes,4,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// Theatre identifier
	TheatreId string `protobuf:"bytes,5,opt,name=theatre_id,json=theatreId,proto3" json:"theatre_id,omitempty"`
	// Show identifier
	ShowId string `protobuf:"bytes,6,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	// Screen identifier
	ScreenId string `protobuf:"bytes,7,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	// Seat identifiers
	SeatIds []string `protobuf:"bytes,8,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	// Total ticket amount
	TotalAmount float64 `protobuf:"fixed64,9,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// Current ticket status
	Status ticket_service.TicketStatus `protobuf:"varint,10,opt,name=status,proto3,enum=ticket_service.status.TicketStatus" json:"status,omitempty"`
	// Ticket issue timestamp
	IssuedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// Ticket update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_ticket_service_ticket_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_read_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *Ticket) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *Ticket) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Ticket) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Ticket) GetTheatreId() string {
	if x != nil {
		return x.TheatreId
	}
	return ""
}

func (x *Ticket) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *Ticket) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *Ticket) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *Ticket) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Ticket) GetStatus() ticket_service.TicketStatus {
	if x != nil {
		return x.Status
	}
	return ticket_service.TicketStatus(0)
}

func (x *Ticket) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Ticket) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetTicketByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticket identifier
	TicketId      string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketByIdRequest) Reset() {
	*x = GetTicketByIdRequest{}
	mi := &file_ticket_service_ticket_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketByIdRequest) ProtoMessage() {}

func (x *GetTicketByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTicketByIdRequest) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_read_proto_rawDescGZIP(), []int{1}
}

func (x *GetTicketByIdRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type GetTicketByIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticket entity
	Ticket        *Ticket `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketByIdResponse) Reset() {
	*x = GetTicketByIdResponse{}
	mi := &file_ticket_service_ticket_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketByIdResponse) ProtoMessage() {}

func (x *GetTicketByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTicketByIdResponse) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_read_proto_rawDescGZIP(), []int{2}
}

func (x *GetTicketByIdResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type GetUserTicketsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User identifier
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Pagination limit
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset
	Offset        uint32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTicketsRequest) Reset() {
	*x = GetUserTicketsRequest{}
	mi := &file_ticket_service_ticket_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTicketsRequest) ProtoMessage() {}

func (x *GetUserTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTicketsRequest.ProtoReflect.Descriptor instead.
func (*GetUserTicketsRequest) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_read_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserTicketsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserTicketsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserTicketsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUserTicketsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticket list
	Tickets []*Ticket `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	// Total records
	Total uint64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// Pagination limit
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset
	Offset        uint32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTicketsResponse) Reset() {
	*x = GetUserTicketsResponse{}
	mi := &file_ticket_service_ticket_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTicketsResponse) ProtoMessage() {}

func (x *GetUserTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_service_ticket_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTicketsResponse.ProtoReflect.Descriptor instead.
func (*GetUserTicketsResponse) Descriptor() ([]byte, []int) {
	return file_ticket_service_ticket_read_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *GetUserTicketsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUserTicketsResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserTicketsResponse) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_ticket_service_ticket_read_proto protoreflect.FileDescriptor

const file_ticket_service_ticket_read_proto_rawDesc = "" +
	"\n" +
	" ticket_service/ticket_read.proto\x12\x13ticket_service.read\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"ticket_service/ticket_status.proto\"\xbc\x03\n" +
	"\x06Ticket\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x04 \x01(\tR\amovieId\x12\x1d\n" +
	"\n" +
	"theatre_id\x18\x05 \x01(\tR\ttheatreId\x12\x17\n" +
	"\ashow_id\x18\x06 \x01(\tR\x06showId\x12\x1b\n" +
	"\tscreen_id\x18\a \x01(\tR\bscreenId\x12\x19\n" +
	"\bseat_ids\x18\b \x03(\tR\aseatIds\x12!\n" +
	"\ftotal_amount\x18\t \x01(\x01R\vtotalAmount\x12;\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2#.ticket_service.status.TicketStatusR\x06status\x127\n" +
	"\tissued_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"3\n" +
	"\x14GetTicketByIdRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"L\n" +
	"\x15GetTicketByIdResponse\x123\n" +
	"\x06ticket\x18\x01 \x01(\v2\x1b.ticket_service.read.TicketR\x06ticket\"^\n" +
	"\x15GetUserTicketsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"\x93\x01\n" +
	"\x16GetUserTicketsResponse\x125\n" +
	"\atickets\x18\x01 \x03(\v2\x1b.ticket_service.read.TicketR\atickets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset2\xe6\x01\n" +
	"\x11TicketReadService\x12f\n" +
	"\rGetTicketById\x12).ticket_service.read.GetTicketByIdRequest\x1a*.ticket_service.read.GetTicketByIdResponse\x12i\n" +
	"\x0eGetUserTickets\x12*.ticket_service.read.GetUserTicketsRequest\x1a+.ticket_service.read.GetUserTicketsResponseBdZbgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/ticket_service/read;ticket_readb\x06proto3"

var (
	file_ticket_service_ticket_read_proto_rawDescOnce sync.Once
	file_ticket_service_ticket_read_proto_rawDescData []byte
)

func file_ticket_service_ticket_read_proto_rawDescGZIP() []byte {
	file_ticket_service_ticket_read_proto_rawDescOnce.Do(func() {
		file_ticket_service_ticket_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticket_service_ticket_read_proto_rawDesc), len(file_ticket_service_ticket_read_proto_rawDesc)))
	})
	return file_ticket_service_ticket_read_proto_rawDescData
}

var file_ticket_service_ticket_read_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ticket_service_ticket_read_proto_goTypes = []any{
	(*Ticket)(nil),                   // 0: ticket_service.read.Ticket
	(*GetTicketByIdRequest)(nil),     // 1: ticket_service.read.GetTicketByIdRequest
	(*GetTicketByIdResponse)(nil),    // 2: ticket_service.read.GetTicketByIdResponse
	(*GetUserTicketsRequest)(nil),    // 3: ticket_service.read.GetUserTicketsRequest
	(*GetUserTicketsResponse)(nil),   // 4: ticket_service.read.GetUserTicketsResponse
	(ticket_service.TicketStatus)(0), // 5: ticket_service.status.TicketStatus
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_ticket_service_ticket_read_proto_depIdxs = []int32{
	5, // 0: ticket_service.read.Ticket.status:type_name -> ticket_service.status.TicketStatus
	6, // 1: ticket_service.read.Ticket.issued_at:type_name -> google.protobuf.Timestamp
	6, // 2: ticket_service.read.Ticket.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: ticket_service.read.GetTicketByIdResponse.ticket:type_name -> ticket_service.read.Ticket
	0, // 4: ticket_service.read.GetUserTicketsResponse.tickets:type_name -> ticket_service.read.Ticket
	1, // 5: ticket_service.read.TicketReadService.GetTicketById:input_type -> ticket_service.read.GetTicketByIdRequest
	3, // 6: ticket_service.read.TicketReadService.GetUserTickets:input_type -> ticket_service.read.GetUserTicketsRequest
	2, // 7: ticket_service.read.TicketReadService.GetTicketById:output_type -> ticket_service.read.GetTicketByIdResponse
	4, // 8: ticket_service.read.TicketReadService.GetUserTickets:output_type -> ticket_service.read.GetUserTicketsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ticket_service_ticket_read_proto_init() }
func file_ticket_service_ticket_read_proto_init() {
	if File_ticket_service_ticket_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticket_service_ticket_read_proto_rawDesc), len(file_ticket_service_ticket_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_service_ticket_read_proto_goTypes,
		DependencyIndexes: file_ticket_service_ticket_read_proto_depIdxs,
		MessageInfos:      file_ticket_service_ticket_read_proto_msgTypes,
	}.Build()
	File_ticket_service_ticket_read_proto = out.File
	file_ticket_service_ticket_read_proto_goTypes = nil
	file_ticket_service_ticket_read_proto_depIdxs = nil
}
