// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payment_service/payment_read.proto

package payment_read

import (
	payment_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/payment_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Payment Entity
// |--------------------------------------------------------------------------
type Payment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payment identifier
	PaymentId string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// Booking identifier
	BookingId string `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	// User identifier
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Payment amount
	Amount float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// Currency
	//
	// Example:
	// INR
	// USD
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// Payment provider
	//
	// Example:
	// Razorpay
	// Stripe
	// PayPal
	Provider string `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	// Provider transaction identifier
	TransactionId string `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Current payment status
	Status payment_service.PaymentStatus `protobuf:"varint,8,opt,name=status,proto3,enum=payment_service.status.PaymentStatus" json:"status,omitempty"`
	// Payment creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Payment update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_service_payment_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_read_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Payment) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetStatus() payment_service.PaymentStatus {
	if x != nil {
		return x.Status
	}
	return payment_service.PaymentStatus(0)
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetPaymentByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payment identifier
	PaymentId     string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByIdRequest) Reset() {
	*x = GetPaymentByIdRequest{}
	mi := &file_payment_service_payment_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByIdRequest) ProtoMessage() {}

func (x *GetPaymentByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByIdRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_read_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentByIdRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetPaymentByIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payment entity
	Payment       *Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByIdResponse) Reset() {
	*x = GetPaymentByIdResponse{}
	mi := &file_payment_service_payment_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByIdResponse) ProtoMessage() {}

func (x *GetPaymentByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentByIdResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_read_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentByIdResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

var File_payment_service_payment_read_proto protoreflect.FileDescriptor

const file_payment_service_payment_read_proto_rawDesc = "" +
	"\n" +
	"\"payment_service/payment_read.proto\x12\x14payment_service.read\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$payment_service/payment_status.proto\"\x8c\x03\n" +
	"\aPayment\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12%\n" +
	"\x0etransaction_id\x18\a \x01(\tR\rtransactionId\x12=\n" +
	"\x06status\x18\b \x01(\x0e2%.payment_service.status.PaymentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"6\n" +
	"\x15GetPaymentByIdRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"Q\n" +
	"\x16GetPaymentByIdResponse\x127\n" +
	"\apayment\x18\x01 \x01(\v2\x1d.payment_service.read.PaymentR\apayment2\x81\x01\n" +
	"\x12PaymentReadService\x12k\n" +
	"\x0eGetPaymentById\x12+.payment_service.read.GetPaymentByIdRequest\x1a,.payment_service.read.GetPaymentByIdResponseBfZdgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/payment_service/read;payment_readb\x06proto3"

var (
	file_payment_service_payment_read_proto_rawDescOnce sync.Once
	file_payment_service_payment_read_proto_rawDescData []byte
)

func file_payment_service_payment_read_proto_rawDescGZIP() []byte {
	file_payment_service_payment_read_proto_rawDescOnce.Do(func() {
		file_payment_service_payment_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_payment_read_proto_rawDesc), len(file_payment_service_payment_read_proto_rawDesc)))
	})
	return file_payment_service_payment_read_proto_rawDescData
}

var file_payment_service_payment_read_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payment_service_payment_read_proto_goTypes = []any{
	(*Payment)(nil),                    // 0: payment_service.read.Payment
	(*GetPaymentByIdRequest)(nil),      // 1: payment_service.read.GetPaymentByIdRequest
	(*GetPaymentByIdResponse)(nil),     // 2: payment_service.read.GetPaymentByIdResponse
	(payment_service.PaymentStatus)(0), // 3: payment_service.status.PaymentStatus
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
}
var file_payment_service_payment_read_proto_depIdxs = []int32{
	3, // 0: payment_service.read.Payment.status:type_name -> payment_service.status.PaymentStatus
	4, // 1: payment_service.read.Payment.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: payment_service.read.Payment.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: payment_service.read.GetPaymentByIdResponse.payment:type_name -> payment_service.read.Payment
	1, // 4: payment_service.read.PaymentReadService.GetPaymentById:input_type -> payment_service.read.GetPaymentByIdRequest
	2, // 5: payment_service.read.PaymentReadService.GetPaymentById:output_type -> payment_service.read.GetPaymentByIdResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_payment_service_payment_read_proto_init() }
func file_payment_service_payment_read_proto_init() {
	if File_payment_service_payment_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_payment_read_proto_rawDesc), len(file_payment_service_payment_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_payment_read_proto_goTypes,
		DependencyIndexes: file_payment_service_payment_read_proto_depIdxs,
		MessageInfos:      file_payment_service_payment_read_proto_msgTypes,
	}.Build()
	File_payment_service_payment_read_proto = out.File
	file_payment_service_payment_read_proto_goTypes = nil
	file_payment_service_payment_read_proto_depIdxs = nil
}
