// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: payment_service/payment_read.proto

package payment_read

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentReadService_GetPaymentById_FullMethodName = "/payment_service.read.PaymentReadService/GetPaymentById"
)

// PaymentReadServiceClient is the client API for PaymentReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentReadServiceClient interface {
	// |--------------------------------------------------------------------------
	// | Get Payment By ID
	// |--------------------------------------------------------------------------
	// |
	// | Fetch payment details and status.
	// |
	// | REST:
	// | GET /payments/{id}
	// |
	GetPaymentById(ctx context.Context, in *GetPaymentByIdRequest, opts ...grpc.CallOption) (*GetPaymentByIdResponse, error)
}

type paymentReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentReadServiceClient(cc grpc.ClientConnInterface) PaymentReadServiceClient {
	return &paymentReadServiceClient{cc}
}

func (c *paymentReadServiceClient) GetPaymentById(ctx context.Context, in *GetPaymentByIdRequest, opts ...grpc.CallOption) (*GetPaymentByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentByIdResponse)
	err := c.cc.Invoke(ctx, PaymentReadService_GetPaymentById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentReadServiceServer is the server API for PaymentReadService service.
// All implementations must embed UnimplementedPaymentReadServiceServer
// for forward compatibility.
type PaymentReadServiceServer interface {
	// |--------------------------------------------------------------------------
	// | Get Payment By ID
	// |--------------------------------------------------------------------------
	// |
	// | Fetch payment details and status.
	// |
	// | REST:
	// | GET /payments/{id}
	// |
	GetPaymentById(context.Context, *GetPaymentByIdRequest) (*GetPaymentByIdResponse, error)
	mustEmbedUnimplementedPaymentReadServiceServer()
}

// UnimplementedPaymentReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentReadServiceServer struct{}

func (UnimplementedPaymentReadServiceServer) GetPaymentById(context.Context, *GetPaymentByIdRequest) (*GetPaymentByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentById not implemented")
}
func (UnimplementedPaymentReadServiceServer) mustEmbedUnimplementedPaymentReadServiceServer() {}
func (UnimplementedPaymentReadServiceServer) testEmbeddedByValue()                            {}

// UnsafePaymentReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentReadServiceServer will
// result in compilation errors.
type UnsafePaymentReadServiceServer interface {
	mustEmbedUnimplementedPaymentReadServiceServer()
}

func RegisterPaymentReadServiceServer(s grpc.ServiceRegistrar, srv PaymentReadServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentReadService_ServiceDesc, srv)
}

func _PaymentReadService_GetPaymentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentReadServiceServer).GetPaymentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentReadService_GetPaymentById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentReadServiceServer).GetPaymentById(ctx, req.(*GetPaymentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentReadService_ServiceDesc is the grpc.ServiceDesc for PaymentReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment_service.read.PaymentReadService",
	HandlerType: (*PaymentReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaymentById",
			Handler:    _PaymentReadService_GetPaymentById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_service/payment_read.proto",
}
