// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payment_service/payment_status.proto

package payment_status

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// |--------------------------------------------------------------------------
// | Payment Status
// |--------------------------------------------------------------------------
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PROCESSING  PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_SUCCESS     PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 5
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PROCESSING",
		3: "PAYMENT_STATUS_SUCCESS",
		4: "PAYMENT_STATUS_FAILED",
		5: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PROCESSING":  2,
		"PAYMENT_STATUS_SUCCESS":     3,
		"PAYMENT_STATUS_FAILED":      4,
		"PAYMENT_STATUS_REFUNDED":    5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_service_payment_status_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_service_payment_status_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_service_payment_status_proto_rawDescGZIP(), []int{0}
}

var File_payment_service_payment_status_proto protoreflect.FileDescriptor

const file_payment_service_payment_status_proto_rawDesc = "" +
	"\n" +
	"$payment_service/payment_status.proto\x12\x16payment_service.status*\xbe\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12\x1a\n" +
	"\x16PAYMENT_STATUS_SUCCESS\x10\x03\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x05BdZbgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/payment_service/;payment_statusb\x06proto3"

var (
	file_payment_service_payment_status_proto_rawDescOnce sync.Once
	file_payment_service_payment_status_proto_rawDescData []byte
)

func file_payment_service_payment_status_proto_rawDescGZIP() []byte {
	file_payment_service_payment_status_proto_rawDescOnce.Do(func() {
		file_payment_service_payment_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_payment_status_proto_rawDesc), len(file_payment_service_payment_status_proto_rawDesc)))
	})
	return file_payment_service_payment_status_proto_rawDescData
}

var file_payment_service_payment_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_service_payment_status_proto_goTypes = []any{
	(PaymentStatus)(0), // 0: payment_service.status.PaymentStatus
}
var file_payment_service_payment_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_service_payment_status_proto_init() }
func file_payment_service_payment_status_proto_init() {
	if File_payment_service_payment_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_payment_status_proto_rawDesc), len(file_payment_service_payment_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_service_payment_status_proto_goTypes,
		DependencyIndexes: file_payment_service_payment_status_proto_depIdxs,
		EnumInfos:         file_payment_service_payment_status_proto_enumTypes,
	}.Build()
	File_payment_service_payment_status_proto = out.File
	file_payment_service_payment_status_proto_goTypes = nil
	file_payment_service_payment_status_proto_depIdxs = nil
}
