// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payment_service/payment_write.proto

package payment_write

import (
	payment_service "github.com/movie-reservation-system-ms/movie_reservation_proto_lib/payment_service/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiatePaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Booking identifier
	BookingId string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	// User identifier
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Payment amount
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Currency
	//
	// Example:
	// INR
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// Payment provider
	//
	// Example:
	// Razorpay
	// Stripe
	Provider      string `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePaymentRequest) Reset() {
	*x = InitiatePaymentRequest{}
	mi := &file_payment_service_payment_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentRequest) ProtoMessage() {}

func (x *InitiatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentRequest.ProtoReflect.Descriptor instead.
func (*InitiatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_write_proto_rawDescGZIP(), []int{0}
}

func (x *InitiatePaymentRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InitiatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *InitiatePaymentRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type InitiatePaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payment identifier
	PaymentId string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// Provider order identifier
	ProviderOrderId string `protobuf:"bytes,2,opt,name=provider_order_id,json=providerOrderId,proto3" json:"provider_order_id,omitempty"`
	// Payment status
	Status payment_service.PaymentStatus `protobuf:"varint,3,opt,name=status,proto3,enum=payment_service.status.PaymentStatus" json:"status,omitempty"`
	// Payment URL
	PaymentUrl string `protobuf:"bytes,4,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	// Creation timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePaymentResponse) Reset() {
	*x = InitiatePaymentResponse{}
	mi := &file_payment_service_payment_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentResponse) ProtoMessage() {}

func (x *InitiatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentResponse.ProtoReflect.Descriptor instead.
func (*InitiatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_write_proto_rawDescGZIP(), []int{1}
}

func (x *InitiatePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *InitiatePaymentResponse) GetProviderOrderId() string {
	if x != nil {
		return x.ProviderOrderId
	}
	return ""
}

func (x *InitiatePaymentResponse) GetStatus() payment_service.PaymentStatus {
	if x != nil {
		return x.Status
	}
	return payment_service.PaymentStatus(0)
}

func (x *InitiatePaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *InitiatePaymentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type VerifyPaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payment identifier
	PaymentId string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// Provider transaction identifier
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Provider signature
	Signature     string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentRequest) Reset() {
	*x = VerifyPaymentRequest{}
	mi := &file_payment_service_payment_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentRequest) ProtoMessage() {}

func (x *VerifyPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentRequest.ProtoReflect.Descriptor instead.
func (*VerifyPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_write_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *VerifyPaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VerifyPaymentRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type VerifyPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payment identifier
	PaymentId string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// Payment status
	Status payment_service.PaymentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=payment_service.status.PaymentStatus" json:"status,omitempty"`
	// Verification timestamp
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentResponse) Reset() {
	*x = VerifyPaymentResponse{}
	mi := &file_payment_service_payment_write_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentResponse) ProtoMessage() {}

func (x *VerifyPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_write_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentResponse.ProtoReflect.Descriptor instead.
func (*VerifyPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_write_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *VerifyPaymentResponse) GetStatus() payment_service.PaymentStatus {
	if x != nil {
		return x.Status
	}
	return payment_service.PaymentStatus(0)
}

func (x *VerifyPaymentResponse) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

type RefundPaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payment identifier
	PaymentId string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// Refund reason
	Reason        *string `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_payment_service_payment_write_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_write_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_write_proto_rawDescGZIP(), []int{4}
}

func (x *RefundPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundPaymentRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type RefundPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payment identifier
	PaymentId string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// Payment status
	Status payment_service.PaymentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=payment_service.status.PaymentStatus" json:"status,omitempty"`
	// Refund timestamp
	RefundedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentResponse) Reset() {
	*x = RefundPaymentResponse{}
	mi := &file_payment_service_payment_write_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentResponse) ProtoMessage() {}

func (x *RefundPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_write_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentResponse.ProtoReflect.Descriptor instead.
func (*RefundPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_write_proto_rawDescGZIP(), []int{5}
}

func (x *RefundPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundPaymentResponse) GetStatus() payment_service.PaymentStatus {
	if x != nil {
		return x.Status
	}
	return payment_service.PaymentStatus(0)
}

func (x *RefundPaymentResponse) GetRefundedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefundedAt
	}
	return nil
}

type HandlePaymentWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider name
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Event type
	//
	// Example:
	// payment.success
	// payment.failed
	Event string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// Provider payload
	Payload string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Provider signature
	Signature     string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePaymentWebhookRequest) Reset() {
	*x = HandlePaymentWebhookRequest{}
	mi := &file_payment_service_payment_write_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePaymentWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePaymentWebhookRequest) ProtoMessage() {}

func (x *HandlePaymentWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_write_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePaymentWebhookRequest.ProtoReflect.Descriptor instead.
func (*HandlePaymentWebhookRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_write_proto_rawDescGZIP(), []int{6}
}

func (x *HandlePaymentWebhookRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *HandlePaymentWebhookRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *HandlePaymentWebhookRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *HandlePaymentWebhookRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type HandlePaymentWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation result
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePaymentWebhookResponse) Reset() {
	*x = HandlePaymentWebhookResponse{}
	mi := &file_payment_service_payment_write_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePaymentWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePaymentWebhookResponse) ProtoMessage() {}

func (x *HandlePaymentWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_payment_write_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePaymentWebhookResponse.ProtoReflect.Descriptor instead.
func (*HandlePaymentWebhookResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_payment_write_proto_rawDescGZIP(), []int{7}
}

func (x *HandlePaymentWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_payment_service_payment_write_proto protoreflect.FileDescriptor

const file_payment_service_payment_write_proto_rawDesc = "" +
	"\n" +
	"#payment_service/payment_write.proto\x12\x15payment_service.write\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$payment_service/payment_status.proto\"\xa0\x01\n" +
	"\x16InitiatePaymentRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\"\xff\x01\n" +
	"\x17InitiatePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12*\n" +
	"\x11provider_order_id\x18\x02 \x01(\tR\x0fproviderOrderId\x12=\n" +
	"\x06status\x18\x03 \x01(\x0e2%.payment_service.status.PaymentStatusR\x06status\x12\x1f\n" +
	"\vpayment_url\x18\x04 \x01(\tR\n" +
	"paymentUrl\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"z\n" +
	"\x14VerifyPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"\xb2\x01\n" +
	"\x15VerifyPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.payment_service.status.PaymentStatusR\x06status\x12;\n" +
	"\vverified_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\"]\n" +
	"\x14RefundPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\xb2\x01\n" +
	"\x15RefundPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.payment_service.status.PaymentStatusR\x06status\x12;\n" +
	"\vrefunded_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"refundedAt\"\x87\x01\n" +
	"\x1bHandlePaymentWebhookRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"8\n" +
	"\x1cHandlePaymentWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe0\x03\n" +
	"\x13PaymentWriteService\x12p\n" +
	"\x0fInitiatePayment\x12-.payment_service.write.InitiatePaymentRequest\x1a..payment_service.write.InitiatePaymentResponse\x12j\n" +
	"\rVerifyPayment\x12+.payment_service.write.VerifyPaymentRequest\x1a,.payment_service.write.VerifyPaymentResponse\x12j\n" +
	"\rRefundPayment\x12+.payment_service.write.RefundPaymentRequest\x1a,.payment_service.write.RefundPaymentResponse\x12\x7f\n" +
	"\x14HandlePaymentWebhook\x122.payment_service.write.HandlePaymentWebhookRequest\x1a3.payment_service.write.HandlePaymentWebhookResponseBhZfgithub.com/movie-reservation-system-ms/movie_reservation_proto_lib/payment_service/write;payment_writeb\x06proto3"

var (
	file_payment_service_payment_write_proto_rawDescOnce sync.Once
	file_payment_service_payment_write_proto_rawDescData []byte
)

func file_payment_service_payment_write_proto_rawDescGZIP() []byte {
	file_payment_service_payment_write_proto_rawDescOnce.Do(func() {
		file_payment_service_payment_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_payment_write_proto_rawDesc), len(file_payment_service_payment_write_proto_rawDesc)))
	})
	return file_payment_service_payment_write_proto_rawDescData
}

var file_payment_service_payment_write_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payment_service_payment_write_proto_goTypes = []any{
	(*InitiatePaymentRequest)(nil),       // 0: payment_service.write.InitiatePaymentRequest
	(*InitiatePaymentResponse)(nil),      // 1: payment_service.write.InitiatePaymentResponse
	(*VerifyPaymentRequest)(nil),         // 2: payment_service.write.VerifyPaymentRequest
	(*VerifyPaymentResponse)(nil),        // 3: payment_service.write.VerifyPaymentResponse
	(*RefundPaymentRequest)(nil),         // 4: payment_service.write.RefundPaymentRequest
	(*RefundPaymentResponse)(nil),        // 5: payment_service.write.RefundPaymentResponse
	(*HandlePaymentWebhookRequest)(nil),  // 6: payment_service.write.HandlePaymentWebhookRequest
	(*HandlePaymentWebhookResponse)(nil), // 7: payment_service.write.HandlePaymentWebhookResponse
	(payment_service.PaymentStatus)(0),   // 8: payment_service.status.PaymentStatus
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
}
var file_payment_service_payment_write_proto_depIdxs = []int32{
	8,  // 0: payment_service.write.InitiatePaymentResponse.status:type_name -> payment_service.status.PaymentStatus
	9,  // 1: payment_service.write.InitiatePaymentResponse.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: payment_service.write.VerifyPaymentResponse.status:type_name -> payment_service.status.PaymentStatus
	9,  // 3: payment_service.write.VerifyPaymentResponse.verified_at:type_name -> google.protobuf.Timestamp
	8,  // 4: payment_service.write.RefundPaymentResponse.status:type_name -> payment_service.status.PaymentStatus
	9,  // 5: payment_service.write.RefundPaymentResponse.refunded_at:type_name -> google.protobuf.Timestamp
	0,  // 6: payment_service.write.PaymentWriteService.InitiatePayment:input_type -> payment_service.write.InitiatePaymentRequest
	2,  // 7: payment_service.write.PaymentWriteService.VerifyPayment:input_type -> payment_service.write.VerifyPaymentRequest
	4,  // 8: payment_service.write.PaymentWriteService.RefundPayment:input_type -> payment_service.write.RefundPaymentRequest
	6,  // 9: payment_service.write.PaymentWriteService.HandlePaymentWebhook:input_type -> payment_service.write.HandlePaymentWebhookRequest
	1,  // 10: payment_service.write.PaymentWriteService.InitiatePayment:output_type -> payment_service.write.InitiatePaymentResponse
	3,  // 11: payment_service.write.PaymentWriteService.VerifyPayment:output_type -> payment_service.write.VerifyPaymentResponse
	5,  // 12: payment_service.write.PaymentWriteService.RefundPayment:output_type -> payment_service.write.RefundPaymentResponse
	7,  // 13: payment_service.write.PaymentWriteService.HandlePaymentWebhook:output_type -> payment_service.write.HandlePaymentWebhookResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_payment_service_payment_write_proto_init() }
func file_payment_service_payment_write_proto_init() {
	if File_payment_service_payment_write_proto != nil {
		return
	}
	file_payment_service_payment_write_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_payment_write_proto_rawDesc), len(file_payment_service_payment_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_payment_write_proto_goTypes,
		DependencyIndexes: file_payment_service_payment_write_proto_depIdxs,
		MessageInfos:      file_payment_service_payment_write_proto_msgTypes,
	}.Build()
	File_payment_service_payment_write_proto = out.File
	file_payment_service_payment_write_proto_goTypes = nil
	file_payment_service_payment_write_proto_depIdxs = nil
}
